### ISSUE TITLE
Bearer Schema

### ISSUE THREAD

**Issue by leocaseiro** [lcobucci/jwt#100]
Hi,

Thanks for this nice library.

I'd like to Parse a `jwt` with Bearer, but it's not working. Is there a proper way to do it?

My issue is here:
```php
$tokenString = 'Bearer xxxxx.xxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxx'; //Comes from Angular
$token = (new Parser())->parse((string) $tokenString); // Parses from a string
```

However, I'm getting error:
> "Error while decoding to JSON: Malformed UTF-8 characters, possibly incorrectly encoded"

If I remove `Bearer` from my token, works just fine. Do I need to remove it before parse or there's a way to set a prefix for my token?

I couldn't find it.

Thanks

**Comment by lcobucci** [comment]
@leocaseiro thanks for using it :smile:

Although JWTs are quite useful for authentication that's not the only use case of it. So the `Parser` always consider that you're using just the token string, nothing more and nothing less.

**Comment by lcobucci** [comment]
Will close this, if need more information please let me know

**Comment by leocaseiro** [comment]
No worries, thanks for your quick reply 👍 

I'll replace before send to parser, though.
