### ISSUE TITLE
Uncaught Error: Class "Lcobucci\JWT\JwtFacade" not found

### ISSUE THREAD

**Issue by juggernautsei** [lcobucci/jwt#1005]
Hi,
I created a clean directory. I ran composer to install the package. I copied and pasted the code from the quick start into a file I named index.php. In my IDE, line 23 use Lcobucci\JWT\JwtFacade; It warns me that JwtFacade class can not be found. What should I do?

![image](https://user-images.githubusercontent.com/834958/227716723-59379b8d-20e8-4ad5-970e-7ebf70a99e2b.png)

E:\Development\MedBoss_v7\interface\modules\custom_modules\oe-module-telehealth-8x8>composer require lcobucci/jwt
No composer.json in current directory, do you want to use the one at E:\Development\MedBoss_v7? [Y,n]? n
Info from https://repo.packagist.org: #StandWithUkraine
Using version ^4.0 for lcobucci/jwt
./composer.json has been created
Running composer update lcobucci/jwt
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking lcobucci/clock (2.0.0)
  - Locking lcobucci/jwt (4.0.4)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Downloading lcobucci/clock (2.0.0)
  - Downloading lcobucci/jwt (4.0.4)
  - Installing lcobucci/clock (2.0.0): Extracting archive
  - Installing lcobucci/jwt (4.0.4): Extracting archive
Generating autoload files
2 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

**Comment by Ocramius** [comment]
I think the facade is available on `4.1.0` or `4.2.0`: you are on `4.0.4`, where the feature wasn't introduced yet.
