### ISSUE TITLE
error Undefined method 'claims'.

### ISSUE THREAD

**Issue by linxue** [lcobucci/jwt#1008]
error: 
Undefined method 'claims'.

php code : 
$jwtData['created'] = $jwtParseRes->claims()->get('created');

suggest:
in file lcobucci/jwt/src/Token.php , add these code: 

    /**
     * return claims DataSet
     */
    public function claims(): DataSet;

**Comment by lcobucci** [comment]
Duplicate of https://github.com/lcobucci/jwt/issues/611?
