### ISSUE TITLE
Missing Configuration.php in Branch 3.1 ?

### ISSUE THREAD

**Issue by bytetonight** [lcobucci/jwt#101]
Installing via composer require lcobucci/jwt installs 3.1 and does not include Configuration.php as mentioned in your example.

**Comment by geggleto** [comment]
The example on the home page refers to the master branch... The master branch is not 3.1. You will want this page. https://github.com/lcobucci/jwt/tree/3.1 for example code.

**Comment by bytetonight** [comment]
You're right. I misread that part. Sorry.
