### ISSUE TITLE
Suggestion: Make Parser methods public

### ISSUE THREAD

**Issue by panigrc** [lcobucci/jwt#1013]
Hi,
the `Lcobucci\JWT\Token\Parser` is final and it's methods are private, which means that there is no way to use these methods externally.

Would it make sense to make methods `splitJwt()`, `parseHeader()`, `parseClaims()`, `parseSignature()` public? 

Thanks in advance.

**Comment by Ocramius** [comment]
If you want these public, they should be on a separate interface: they are an implementation detail on purpose, to allow future changes in here, without BC issues.

**Comment by panigrc** [comment]
I assume, I could do that too, thanks for the quick response!

**Comment by lcobucci** [comment]
@panigrc please provide some explation on why you are proposing that.

It's extremely helpful to understand where you are trying to achieve, mainly to balance the trade-offs of the expansion of the public API of this package 👍

**Comment by panigrc** [comment]
@lcobucci well the main reason is to not have to "reinvent" the wheel, in case i.e. I need to split the token I would use the `splitJwt()`. The only way now to do so is to use the `parse()` method, but that will try to do "everything" which it's not always needed.

**Comment by Ocramius** [comment]
@panigrc copy-paste (**WITH TESTS**) is OK there, FWIW.

**Comment by lcobucci** [comment]
> @lcobucci well the main reason is to not have to "reinvent" the wheel, in case i.e. I need to split the token I would use the `splitJwt()`. The only way now to do so is to use the `parse()` method, but that will try to do "everything" which it's not always needed.

What I would like to understand is why you need to only split the token. What's your concrete use case.

I'm asking that, because exposing that method on the public API makes its evolution harder (e.g. bc breaks guarantees).
