### ISSUE TITLE
It was not possible to parse your key, reason: error:0480006C:PEM routines::no start line

### ISSUE THREAD

**Issue by papac** [lcobucci/jwt#1014]
Good morning,

Can I get the configuration example using RS256 alg from:

```php
$builder = new Builder();
$builder->sign(new \Lcobucci\JWT\Signer\Rsa\Sha256(), new Key('signkey.pem'));
```

**Comment by lcobucci** [comment]
@papac I'm not sure of the context here... are you migrating from v3?

If so, have you checked https://lcobucci-jwt.readthedocs.io/en/stable/upgrading/#use-new-key-objects?

**Comment by lcobucci** [comment]
Even on v3, `new Key('signkey.pem')` is invalid - the file will never be read and `signkey.pem` would be used as the raw content of the key.
