### ISSUE TITLE
Class "Lcobucci\JWT\Validation\Constraint\LooseValidAt" not found

### ISSUE THREAD

**Issue by arabnewscms** [lcobucci/jwt#1021]
after install this package i face this problem 
this package using wiith login with apple but i can't solve this problem !

**Comment by arabnewscms** [comment]
laravel v 10 
php => 8.1

**Comment by lcobucci** [comment]
@arabnewscms I'm sorry, you're not giving any information that we can work with to help.

What version of this lib did you install? How are you using it? Did you check your vendor folder?

**Comment by arabnewscms** [comment]
Im sorry I've got this error
Just i upgrade package to v 4.4 and install sodium ext 
it was fixed thank you for your help

**Comment by lcobucci** [comment]
> Im sorry I've got this error
> Just i upgrade package to v 4.4 and install sodium ext 
> it was fixed thank you for your help

Alright, so it's all good now? I'll close it then!
