### ISSUE TITLE
Wrong timezone while parsing jet

### ISSUE THREAD

**Issue by sultz8** [lcobucci/jwt#1034]
I've faced the problem, while parsing jwt token. Parser returns wrong timezone. 
below code shows the way I set timezone.
`$now = new \DateTimeImmutable(timezone: new \DateTimeZone('Asia/Tashkent'));`
However when I try to parse jet Parse::parse($jwt), timezone in result is UTC+0
Also I noticed in your source code, that timezone is not considered.
```php
private function convertDate(int|float|string $timestamp): DateTimeImmutable
    {
        if (! is_numeric($timestamp)) {
            throw InvalidTokenStructure::dateIsNotParseable($timestamp);
        }

        $normalizedTimestamp = number_format((float) $timestamp, self::MICROSECOND_PRECISION, '.', '');

        $date = DateTimeImmutable::createFromFormat('U.u', $normalizedTimestamp);

        if ($date === false) {
            throw InvalidTokenStructure::dateIsNotParseable($normalizedTimestamp);
        }

        return $date;
    }
```

**Comment by lcobucci** [comment]
@sultz8 timestamps are always in UTC, you may call `DateTimeImmutable::setTimezone()` and PHP will calculate the difference for you (if you want to format it, sure).

If you are just using the library for issuing and parsing/validating tokens, the timezone will be irrelevant (to put it in a simplistic way: php compares DateTimeImmutable objects using their Unix timestamp values).
