### ISSUE TITLE
Uncaught Error: Class "Lcobucci\JWT\JwtFacade" not found in version 5.1

### ISSUE THREAD

**Issue by Dtuzzy** [lcobucci/jwt#1036]
I encountered an error while using the lcobucci/jwt library in my PHP project. The error message I received is as follows:
Uncaught Error: Class "Lcobucci\JWT\JwtFacade" currently using version 5.1

**Comment by Ocramius** [comment]
It's there: https://github.com/lcobucci/jwt/blob/f0031c07b96db6a0ca649206e7eacddb7e9d5908/src/JwtFacade.php#L19

I suggest checking your `composer.lock` carefully :)

**Comment by Dtuzzy** [comment]
I guess I had issues updating my composer.  however, I cloned and updated the src so it's fine now. thanks for the prompt respose
