### ISSUE TITLE
JWT token signature is not validated when parsing from configuration

### ISSUE THREAD

**Issue by BernhardK91** [lcobucci/jwt#1038]
We had the following code in our project and expected that the JWT token's signature would be validated, as it was provided to the configurator. Unfortunately, it was not, and we discovered this as a security issue in our project. Every JWT token was valid, not matter what key was used to sign the token.

```php
$configuration = Configuration::forSymmetricSigner(
    new Sha256(),
    InMemory::plainText(/* SECRET TOKEN */)
);

if (! empty($token)) {
    /** @var UnencryptedToken */
    $token = $configuration->parser()->parse($token);
}

return $token ? $token->claims()->all() : [];
```

We fixed this with the following code:

```php
try {
    $token = (new JwtFacade())->parse(
        $jwt,
        new SignedWith(new Sha256(), InMemory::plainText(/* SECRET TOKEN */)),
        new LooseValidAt(
            new FrozenClock(now()->toImmutable())
        )
    );
} catch (RequiredConstraintsViolated $exception) {
    if ($exception->violations()[0]->constraint === SignedWith::class) {
        abort(401, 'Invalid token signature!');
    }

    if ($exception->violations()[0]->constraint === LooseValidAt::class) {
        abort(401, 'Token has been expired!');
    }
}
```

I am not sure, if this is a security issue in this package, but I wanted to report it anyway because of our expectation of a different behavior what resulted in a security issue. 

Best regards,
Bernhard

**Comment by Slamdunk** [comment]
Parsing and validating a token are two separate steps that only advanced users should bother to deep into.

The official documentation indeed recommends in the [Quick start](https://lcobucci-jwt.readthedocs.io/en/stable/quick-start/) to only deal with the `JwtFacade`

**Comment by lcobucci** [comment]
Exactly, [here](https://lcobucci-jwt.readthedocs.io/en/stable/validating-tokens/) you can find all the information about validation constraints too - which can also be used in the facade.

Feel free to share ideas on improving the documentation (PRs are really appreciated 👍).

P.S.: I noticed the usage of `FrozenClock` on your snippet, be mindful that it's mainly designed for tests. In your case, the impact is contained as the facade instance is likely not reused but if you do reuse it, it might not detect token expiration properly (your "now" is pointing to a fixed value).

**Comment by lcobucci** [comment]
Closing as question since it's not an issue on the lib.
