### ISSUE TITLE
Class Lcobucci\JWT\Signer\Key\InMemory may not inherit from final class

### ISSUE THREAD

**Issue by MRSAIHAIK** [lcobucci/jwt#1043]
Hi @lcobucci  

Would like to check with you, is V 3.4.x still working with PHP 7.xx 

coz i face the issue with 

Class Lcobucci\JWT\Signer\Key\InMemory may not inherit from final class (Lcobucci\JWT\Signer\Key)

**Comment by Ocramius** [comment]
What's the full trace?

**Comment by MRSAIHAIK** [comment]
facing issue on callback 

Severity: Compile Error

Message: Class Lcobucci\JWT\Signer\Key\InMemory may not inherit from final class (Lcobucci\JWT\Signer\Key)

Filename: Key/InMemory.php

Line Number: 10

**Comment by lcobucci** [comment]
Yeap, nothing changed, as v3.x and v4.x are pretty much in security-only mode.

It seems like you're facing the same thing as https://github.com/lcobucci/jwt/issues/838. Have you checked it?

**Comment by MRSAIHAIK** [comment]
Ok Thanks 

Yes after update the version of auth0/php-jwt it working. But seems another issue come up. 

An uncaught Exception was encountered
Type: Lcobucci\JWT\Signer\Key\FileCouldNotBeRead

Message: The path "https://icanread.test/AuthKey_K6A3CSB725.p8" does not contain a valid key file

can pls advise this will due to version issue or key issue. 

Keys was export out from apple p8 file

**Comment by lcobucci** [comment]
You need to either use this lib or the fork. Having both at the same time lead to unexpected behaviours.

Check the other issues/discussions around the usage of p8 certs from Apple.  They probably will give you a way out 👍

**Comment by MRSAIHAIK** [comment]
Ok thanks let me check through there and close this ticket

**Comment by erickcrus** [comment]
how to solve this error in version 3.4.x?

**Comment by SvenRtbg** [comment]
IIRC, it has always been a mixup of some dependencies providing copies of the original library. Find out what files are available and identify why they are there. Then decide which copy to keep.
