### ISSUE TITLE
Remove UnifyAudience ClaimFormatter

### ISSUE THREAD

**Issue by ostrolucky** [lcobucci/jwt#1049]
We had a subtle issue here that took us a long time to pin point, since it was seemingly random. In the end it turned out that if we set `list<string>` with single element in `aud` property, https://github.com/lcobucci/jwt/blob/0c37d7ea7c2061ba5189bd6545bb6431914555cc/src/Encoding/UnifyAudience.php#L25 will turn it into `string`. This is something our Frontend was not handling, because that's a rare case. They were always assuming `aud` = `list<string>`

Not sure why this library is automatically doing this, since it should primarily be an array and only in exceptional cases it may be string. From [RFC](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3):

> In the general case, the "aud" value is an array of case-
   sensitive strings, each containing a StringOrURI value.  In the
   special case when the JWT has one audience, the "aud" value MAY be a
   single case-sensitive string containing a StringOrURI value.

**Comment by lcobucci** [comment]
~You missed the rest of the quote...~

> ~In the general case, the "aud" value is an array of case-sensitive strings, each containing a StringOrURI value.  **In the special case when the JWT has one audience, the "aud" value MAY be a single case-sensitive string containing a StringOrURI value.**~

~Nevertheless~ You can compose your formatting chain the way you want: https://lcobucci-jwt.readthedocs.io/en/stable/extending-the-library/#claims-formatter

**Comment by lcobucci** [comment]
Closed as the library's behaviour follows the RFC and users have the means to tweak it according to their own needs.

**Comment by ostrolucky** [comment]
I didn't skip it though. It says MAY be a single string. Why are you enforcing it? You are making it MUST be.

**Comment by lcobucci** [comment]
You're welcome not to use the defaults.

They are meant for interoperability with other implementations (and backwards compatibility with previous versions that lacked support to multiple audience).

**Comment by lcobucci** [comment]
Just to be clear here: what you're referring to isn't an issue, that's why it got closed.

Feel free to rephrase things in a **discussion** and then let's see what other people have to say about it 👍
