### ISSUE TITLE
RSA signer does not validate openssl_* errors.

### ISSUE THREAD

**Issue by aramonc** [lcobucci/jwt#105]
It's possibly for `openssl_get_privatekey` or `openssl_get_publickey` to fail & return `false` In which case [`validateKey`](https://github.com/lcobucci/jwt/blob/master/src/Signer/Rsa.php#L54-L56) raises a warning because `openssl_pkey_get_details` expects a resource & receives a boolean.

I believe further validation should be done in `validateKey` & raise an exception if the value is `false`. It should also use [`openssl_error_string`](http://php.net/manual/en/function.openssl-error-string.php) to forwards the OpenSSL errors.

I encountered this when the public key's file contents are a non-PEM formatted key.

If you agree I can probably submit a PR tomorrow.

**Comment by lcobucci** [comment]
Good catch @aramonc! Please create a branch from 3.1 and send your PR :wink:

**Comment by lcobucci** [comment]
Fixed, thanks @aramonc!
