### ISSUE TITLE
Sha256::create() method doesn't exist

### ISSUE THREAD

**Issue by Ssionn** [lcobucci/jwt#1054]
Since this method doesn't exist, what is the alternative for this?

![CleanShot 2024-04-10 at 11 02 09@2x](https://github.com/lcobucci/jwt/assets/90753599/a0a38344-4b12-480a-9962-447ca86e9544)

**Comment by Ocramius** [comment]
You probably have the wrong version of this library installed

**Comment by Ssionn** [comment]
Update:

I've instantiated the class and it seems to work fine.

**Comment by lcobucci** [comment]
Thank you for the update.
Let's close this one, then.
