### ISSUE TITLE
 Cannot instantiate interface Lcobucci\JWT\Signer\Ecdsa\SignatureConverter

### ISSUE THREAD

**Issue by Razorholt** [lcobucci/jwt#1058]
I get an error while trying to create a token for coinbase api. here is the code:
```php
use Lcobucci\JWT\Configuration;
use Lcobucci\JWT\Signer\Key\InMemory;
use Lcobucci\JWT\Signer\Ecdsa\Sha256;
use Lcobucci\JWT\Signer\Ecdsa\SignatureConverter;

$keyName = 'organizations/b0f974e6-b494{redacted}591eb6d';
$keySecret = "-----BEGIN EC PRIVATE KEY-----\nMHcCAQE{redacted}HEzMVwDhg==\n-----END EC PRIVATE KEY-----\n";

function buildJwt($uri, $keyName, $keySecret) {
    $privateKey = InMemory::plainText($keySecret);
	$signatureConverter = new SignatureConverter();
    $signer = new Sha256($signatureConverter, $privateKey);
    $config = Configuration::forAsymmetricSigner(
        $signer,
        $privateKey,
        null // Public key not needed here
    );

    $time = new \DateTimeImmutable();
    $nonce = bin2hex(random_bytes(16)); // Generate a 32-character hexadecimal nonce

    $token = $config->builder()
        ->issuedBy('coinbase-cloud') // Configures the issuer (iss claim)
        ->permittedFor($uri) // Configures the audience (aud claim)
        ->identifiedBy($keyName) // Configures the ID (jti claim), using keyName as unique identifier
        ->issuedAt($time) // Configures the time that the token was issue (iat claim)
        ->canOnlyBeUsedAfter($time) // Configures the time before which the token cannot be accepted (nbf claim)
        ->expiresAt($time->modify('+2 minutes')) // Configures the expiration time of the token (exp claim)
        ->withClaim('nonce', $nonce) // Configures a new claim, called 'nonce'
        ->getToken($config->signer(), $config->signingKey()); // Retrieves the generated token

    return $token->toString();
}

function main() {
    global $requestMethod, $requestHost, $requestPath, $keyName, $keySecret;

    $uri = "{$requestMethod} {$requestHost}{$requestPath}";
    $jwtToken = buildJwt($uri, $keyName, $keySecret);
    echo "JWT=$jwtToken\n";
}

main();
```

here is the error message:
` Cannot instantiate interface Lcobucci\JWT\Signer\Ecdsa\SignatureConverter`

**Comment by SvenRtbg** [comment]
That error message seems to be correct: You are trying to instantiate this interface in line 2 of your first function: `$signatureConverter = new SignatureConverter();`

Why do you think you need it?

**Comment by Razorholt** [comment]
If I remove it I get this and go with
`$signer = new Sha256($privateKey);`
I get this
`Uncaught TypeError: Lcobucci\JWT\Signer\Ecdsa::__construct(): Argument #1 ($converter) must be of type Lcobucci\JWT\Signer\Ecdsa\SignatureConverter, Lcobucci\JWT\Signer\Key\InMemory given`

**Comment by SvenRtbg** [comment]
Well, `final class Lcobucci\JWT\Signer\Ecdsa\Sha256 extends Lcobucci\JWT\Signer\Ecdsa`, and that class only allows one parameter for the constructor of said type, which defaults to `Lcobucci\JWT\Signer\Ecdsa\MultibyteStringConverter`, and there is no parameter for any key. So I would assume your attempt to pass a key is wrong.

**Comment by Razorholt** [comment]
well, I'm stuck then

**Comment by SvenRtbg** [comment]
Then reset and try to answer the basic questions for reporting issues:
- What are you trying to do? (For example illustrate why your code is the way it is - was there a tutorial or some AI code writer influencing it?)
- What do you expect happens? (that one is missing for sure)
- What do you get instead, and how does it differ from what you expect? (if it isn't obvious)

And please state which version of this library you are using, currently it is guessing you are using the latest 5.x.

**Comment by Razorholt** [comment]
Alright. What I'm trying to achieve is creating a JWT token with PHP to be used with Coinbase API. They have a doc explaining how to generate the token in Python, Go and Javascript but nothing in PHP. Here is the link: https://docs.cloud.coinbase.com/advanced-trade-api/docs/rest-api-auth

I first tried with Firebase JWT but with no avail. The key generated failed validations. So I thought I would try with your library. I installed the version 4. Here are the details:
```
  - Installing psr/clock (1.0.0): Extracting archive
  - Installing stella-maris/clock (0.1.7): Extracting archive
  - Installing lcobucci/clock (2.3.0): Extracting archive
  - Installing lcobucci/jwt (4.0.4): Extracting archive
```

Then, I turned to chatGPT and it got me the code I pasted earlier.

I apreciate your help in this matter. Coinbase devs are totally clueless.

**Comment by SvenRtbg** [comment]
So from your link I can extract this python example snippet that illustrates what info has to go into that JWT:

    jwt_payload = {
        'sub': key_name,
        'iss': "coinbase-cloud",
        'nbf': int(time.time()),
        'exp': int(time.time()) + 120,
        'uri': uri,
    }

Comparing that with what you added into the token: You added a lot more.

          ->issuedBy('coinbase-cloud') // Configures the issuer (iss claim) (correct)
        ->permittedFor($uri) // Configures the audience (aud claim) (there is no audience required, that custom claim should be "uri")
        ->identifiedBy($keyName) // Configures the ID (jti claim), using keyName as unique identifier (not required)
        ->issuedAt($time) // Configures the time that the token was issue (iat claim) (not required)
          ->canOnlyBeUsedAfter($time) // Configures the time before which the token cannot be accepted (nbf claim) (correct)
          ->expiresAt($time->modify('+2 minutes')) // Configures the expiration time of the token (exp claim) (correct)
        ->withClaim('nonce', $nonce) // Configures a new claim, called 'nonce' (not to be put into the claim, but into the headers)

I don't know if additional claims would simply be ignored, but there are missing claims ("uri") and missing header fields ("nonce", probably "kid").

The manual has some examples here for 4.0.x: https://lcobucci-jwt.readthedocs.io/en/4.0.x/issuing-tokens/

Individual headers can be set using `->withHeader($key, $value)`, so you probably need to pass `nonce` and `kid` for the nonce and the key name. Have a try. The manual is there for a reason, once you understand what info the API wants to know.

Also, consider updating to some later 4.x or upgrade to 5.x versions. 4.0.4 is quite old already. If you are not forced to use PHP 7.x or 8.0, the 5.x series is highly recommended.

**Comment by Razorholt** [comment]
OK, I upgraded to v5 and managed to generate a key with this code, but both debuggers ( https://jwt.io/ and  https://token.dev/) say the key is invalid...
```
use Lcobucci\JWT\Encoding\ChainedFormatter;
use Lcobucci\JWT\Encoding\JoseEncoder;
use Lcobucci\JWT\Signer\Key\InMemory;
use Lcobucci\JWT\Signer\Ecdsa\Sha256;
use Lcobucci\JWT\Token\Builder;


	$tokenBuilder = (new Builder(new JoseEncoder(), ChainedFormatter::default()));
	$algorithm    = new Sha256();
	$signingKey   = InMemory::plainText($keySecret);
	$nonce = bin2hex(random_bytes(16));

	$now   = new DateTimeImmutable();
	$token = $tokenBuilder
		// Configures the issuer (iss claim)
		->issuedBy('coinbase-cloud')
		// Configures the audience (aud claim)
		->permittedFor('retail_rest_api_proxy')
		// Configures the subject of the token (sub claim)
		->relatedTo($keyName)
		// Configures the id (jti claim)
		// Configures the time that the token was issue (iat claim)
		->issuedAt($now)
		// Configures the time that the token can be used (nbf claim)
		->canOnlyBeUsedAfter($now)
		// Configures the expiration time of the token (exp claim)
		->expiresAt($now->modify('+1 hour'))
		// Configures a new header, called "foo"
		->withHeader('kid', $keyName)
		->withHeader('nonce', $nonce)
		->withHeader('typ', 'JWT')
		->withHeader('alg', 'ES256')
		// Builds a new token
		->getToken($algorithm, $signingKey);

	echo $token->toString();
```

**Comment by Razorholt** [comment]
oh, i forgot to add the 'uri'. What would be the claim?

I added:
`->withClaim('uri',$uri)`
but still no luck.

**Comment by SvenRtbg** [comment]
No luck in terms of "it does not work with coinbase", or "validators don't like it"? And if the latter: What is the error given?

**Comment by Ocramius** [comment]
@SvenRtbg I'm closing this: as much as I appreciate you trying to help, it is clear that @Razorholt didn't do their homework, and instead is copy-pasting stuff from ChatGPT/LLM, and then turning to the community to get their job done by others.

This is extremely disrespectful of everyone's time, and should not be endorsed, promoted nor aided in any way.

**Comment by Razorholt** [comment]
> No luck in terms of "it does not work with coinbase", or "validators don't like it"? And if the latter: What is the error given?

The signature works now. I think it's because the sodium package wasn't installed properly. Thank you so much for your help!

**Comment by Razorholt** [comment]
> @SvenRtbg I'm closing this: as much as I appreciate you trying to help, it is clear that @Razorholt didn't do their homework, and instead is copy-pasting stuff from ChatGPT/LLM, and then turning to the community to get their job done by others.
> 
> This is extremely disrespectful of everyone's time, and should not be endorsed, promoted nor aided in any way.

pound sand

**Comment by Ocramius** [comment]
Amazing response. Locking.

@lcobucci please ban this guy from the repo.
