### ISSUE TITLE
Sha256::create()

### ISSUE THREAD

**Issue by bradders** [lcobucci/jwt#1060]
Howdy! I'm setting up laravel with Apple Login, and one step of that is creating a sha256 hash with your package...

```
use Lcobucci\\JWT\\Configuration;
use Lcobucci\\JWT\\Signer\\Ecdsa\\Sha256;
use Lcobucci\\JWT\\Signer\\Key\\InMemory;

// ..
$this->app->bind(Configuration::class,
  fn() => Configuration::forSymmetricSigner(
        Sha256::create(),
        InMemory::plainText(config("services.apple.private\_key"))
  )
);
```

I'm getting an error: `Call to undefined method Lcobucci\JWT\Signer\Ecdsa\Sha256::create()`

I'm on v5.3, I had a quick dig around the source files in vendor and couldn't see a create function, but maybe it's supposed to be available from another file? 

@lcobucci Any tips/pointers would be well received! Is there another function I can call to get the same result?

**Comment by lcobucci** [comment]
Sure, that's documented [here](https://lcobucci-jwt.readthedocs.io/en/stable/upgrading/#removal-of-ecdsacreate)
