### ISSUE TITLE
Key parse: error:1E08010C:DECODER routines::unsupported

### ISSUE THREAD

**Issue by bradders** [lcobucci/jwt#1061]
I'm following along with this guide to get laravel working with Apple login: https://bannister.me/blog/generating-a-client-secret-for-sign-in-with-apple-on-each-request

I get a `Lcobucci\JWT\Signer\InvalidKeyProvided` ... `It was not possible to parse your key, reason: * error:1E08010C:DECODER routines::unsupported` on the following code:

<img width="719" alt="Screenshot 2024-04-28 at 11 45 03 AM" src="https://github.com/lcobucci/jwt/assets/840983/14713bc2-9995-4401-b8dc-27fe7cc1d476">

I realize the article is written against an older version of JWT so I'm trying to figure out if I need to update something to get this working. The changelog docs seem to suggest that `getToken` should accept params from a config object (which I think I'm doing).

I found an old issue asking something similar, with a link to an openssl thread (https://github.com/lcobucci/jwt/issues/983), but I'm not sure what the fix would be in relation to my issue.

Any pointers/help would be greatly received!

**Comment by bradders** [comment]
Seems like the key I was using wasn't correctly encoded1

**Comment by andreladocruz** [comment]
@bradders can you share what you did to solve the issue?

Having the same behavior here. :P

**Comment by vierynugroho** [comment]
just create a key in your environment that is one line
