### ISSUE TITLE
Please mark Builder methods `@pure` to ease understanding that it's immutable

### ISSUE THREAD

**Issue by b1rdex** [lcobucci/jwt#1075]
After upgrading to v5, I spent some time figuring out why the code broke, but this wasn't detected by PHPStan or any other tool.

After some tests, I found out that the reason is making the Builder immutable (https://github.com/lcobucci/jwt/pull/979) in the version.

Please consider marking the methods `@pure`, so SCA can report that 'the result is not used'.

Rule check example: https://phpstan.org/r/f638ba16-0ab3-44e2-becd-2927e99ada09

**Comment by Slamdunk** [comment]
Thank you for your rightful complaint: could you please send a PR to fix this?

**Comment by b1rdex** [comment]
@Slamdunk done: https://github.com/lcobucci/jwt/pull/1076
