### ISSUE TITLE
there is a bug when I do composer update in my shopware 6.6.8

### ISSUE THREAD

**Issue by hakimdjabri** [lcobucci/jwt#1079]
there is a bug when I run  composer update in my shopware 6.6.8

![bug-lcobucci-jwt-v5 4 1](https://github.com/user-attachments/assets/d17da589-0178-42e9-ad60-59df16bc7d4e)

**Comment by Ocramius** [comment]
Look at the very last line in your screenshot:unrelated to this package.

**Comment by hakimdjabri** [comment]
> Look at the very last line in your screenshot:unrelated to this package.

Thanks for your answer and sorry for this inconvenient, I thought that it's related to your update released 1 hour before
