### ISSUE TITLE
Please make it a Symfony bundle

### ISSUE THREAD

**Issue by TangoMan75** [lcobucci/jwt#124]
Using this package in Symfony is a pain, that would be awesome to make it a Symfony bundle... Please!

**Comment by schnittstabil** [comment]
What's wrong with the Symfony bundle projects using this package at [packagist.org](https://packagist.org)?

**Comment by TangoMan75** [comment]
Can't find them... 
[https://packagist.org/packages/lcobucci/jwt](https://packagist.org/packages/lcobucci/jwt)

**Comment by lcobucci** [comment]
@TangoMan75 you can find them here https://packagist.org/packages/lcobucci/jwt/dependents

**Comment by lcobucci** [comment]
On my projects I don't use symfony as a fullstack framework so I wouldn't be the best person to create that bundle. However I'm curious why "using this package in Symfony is a pain", can you share your experience?

I do use it with symfony dependency injection container and I have no problem...

**Comment by lcobucci** [comment]
I'll close this as `wontfix` because it's really related to the library but I still want to hear your "pain"...

**Comment by TangoMan75** [comment]
Thank you lcobucci. 
"Pain" might be an overstatement from a lonely moment of frustration... Sorry about that. 
I really can't remember what bothered me so much... 
Keep up the good work !
