### ISSUE TITLE
Documentation is incorrect / refers to changes not yet in dev-master

### ISSUE THREAD

**Issue by gramorris** [lcobucci/jwt#125]
We're running latest dev-master version (972cfe0) and as part of the update changed the Configuration method names to issuedBy & canOnlyBeUsedBy etc.

The documentation shows the same changes for ValidationData however the ValidationData code is still using the old methods setIssuer and setAudience - using issuedBy & canOnlyBeUsedBy results in a "Call to undefined method Lcobucci\\JWT\\ValidationData::issuedBy()"

**Comment by renatomefi** [comment]
Hello @gramorris, thanks for the report! The dev-master is current part of a refactor to make a new major version, It's not advised to use it yet! @lcobucci please correct me if I'm wrong!
Do you have an specific reason to use that version?

**Comment by gramorris** [comment]
@renatomefi thanks, we didn't see anywhere where it says it's not advised to use it, it's worked and is working fine for us. I just felt it was worth pointing out that the documentation on the project homepage is incorrect as per the current commit.

**Comment by schnittstabil** [comment]
> we didn't see anywhere where it says it's not advised to use it

@renatomefi Sorry, but that's assumed to be common knowledge, `composer` also installs the latest stable release:
![image](https://cloud.githubusercontent.com/assets/6059032/19512118/a4612cba-95ea-11e6-8052-9fb72e3ba80b.png)


> I just felt it was worth pointing out that the documentation on the project homepage is incorrect as per the current commit.

Event though `master` is a development branch and not a release branch, the `readme.md` on `master` should match the current state of `master` (known as _iterative incremental development_) – hence thank you for pointing that out :+1: – However `master` was *deployed/released* only to jwt contributors,  thus inconsistencies have to be expected.

**Comment by renatomefi** [comment]
@schnittstabil do you tagging me or the issue author? :)

Thanks for making it clear though! Also agree in keeping the documentation up to date, I'm just worried the author was using master branch and it can be unsafe for now!

**Comment by gramorris** [comment]
We're getting in to a discussion of semantics so I'll just say that what we assumed was the risks associated with using a dev-master branch, we were happy to proceed on that basis. There's no need to be worried on our behalf.

As the documentation for the dev-master is on the project homepage and is incorrect/inconsistent I felt it worth pointing out, that was all I was doing.

**Comment by renatomefi** [comment]
You did right! Thanks for it!

**Comment by lcobucci** [comment]
WOW! Guys you're just awesome! Basically you're all right 😂 

@gramorris thanks for pointing out about the doc, I'll fix it.
@renatomefi @schnittstabil thanks for helping people in this repo too 🍻 

--

@gramorris is good to know that we have some early users. I'm working on the validation refactor and that is going to be merged soon (https://github.com/lcobucci/jwt/tree/refactor/validator-extraction).

**Comment by gramorris** [comment]
Thanks @lcobucci , appreciate the work on the library, we've not found any issues with the functionality so far 👍
