### ISSUE TITLE
Add deprecation notes on methods

### ISSUE THREAD

**Issue by lcobucci** [lcobucci/jwt#133]
To help users migrate to v4

**Comment by lcobucci** [comment]
Even adding `Builder` methods

**Comment by MasterOdin** [comment]
Is there plans to backport the changes in v4 to avoid the now deprecated sign/unsign functions?

**Comment by lcobucci** [comment]
@MasterOdin definitely, I'm working on that already. I decided to release v3.3 to solve the incompatibility with newer PHP versions but v3.4 isn't far away.
