### ISSUE TITLE
Adding the repository for version 3.2 to a project with composer require, installs a different version that the one in the docs

### ISSUE THREAD

**Issue by nanokid** [lcobucci/jwt#134]
Hello. I added the package with composer required and i received the latest version 3.2. Then i tried to create a token using the code in the docs for the version 3.2
```
$token = (new Builder())->issuedBy('http://example.com') // Configures the issuer (iss claim)
                        ->canOnlyBeUsedBy('http://example.org') // Configures the audience (aud claim)
                        ->identifiedBy('4f1g23a12aa', true) // Configures the id (jti claim), replicating as a header item
                        ->issuedAt(time()) // Configures the time that the token was issue (iat claim)
                        ->canOnlyBeUsedAfter(time() + 60) // Configures the time that the token can be used (nbf claim)
                        ->expiresAt(time() + 3600) // Configures the expiration time of the token (exp claim)
                        ->with('uid', 1) // Configures a new claim, called "uid"
                        ->sign($signer,  $privateKey) // creates a signature using your private key
                        ->getToken(); // Retrieves the generated token
```
But i kept receiving an error that the method issuedBy() is not available in the class builder. This method is only available in when using the version 3.2.x-
Can some 1 help me build a token with the code from the 3.2 version ? or guide me on how to proceed from here ?

Thank you

**Comment by schnittstabil** [comment]
From the readme:
 > **Important:** this is the documentation of our next major release (v4) and it **WILL** change. If you are using the **stable** version you should go to branch [3.2](https://github.com/lcobucci/jwt/blob/3.2/README.md).

**Comment by lcobucci** [comment]
@nanokid @schnittstabil I made a mistake here 💩 sorry

I've fixed the branches and you should be able to use these methods on `3.3.x-dev`
