### ISSUE TITLE
Use a time provider to get the current system time

### ISSUE THREAD

**Issue by lcobucci** [lcobucci/jwt#139]
With that we wouldn't allow `null` on methods that receives a `DateTimeInterface`, inject the time provider on the validation constraints and also on the configuration object.

**Comment by lcobucci** [comment]
Do anyone have a suggestion for the package that can be used for this (wouldn't make sense to provide that interface here IMO).

**Comment by lcobucci** [comment]
Depends on #129 (sure)

**Comment by Ocramius** [comment]
@lcobucci checked now, patch LGTM! :+1:
