### ISSUE TITLE
Create a "CONTRIBUTING" file.

### ISSUE THREAD

**Issue by henriquemoody** [lcobucci/jwt#14]
It's a good think to explain how developers can contribute to this project, it makes easy to avoid mistakes.

**Comment by henriquemoody** [comment]
Outdated.

PS.: I'm closing my older issues, please reopen if you think it's relevante.

**Comment by lcobucci** [comment]
I believe that it's relevant, I just hadn't time yet to do it :smile:.

Let's keep it here.

**Comment by henriquemoody** [comment]
:dancer:
