### ISSUE TITLE
How to make a token expired

### ISSUE THREAD

**Issue by Hkesd** [lcobucci/jwt#142]
When a user finds an illegal operation, how to make the user token expired, thanks

**Comment by Ocramius** [comment]
Once a token is emitted, unless it has an identifier, you cannot invalidate
it. One way is changing verification key, but that invalidates all current
tokens.

**Comment by schnittstabil** [comment]
The standard way to revoke tokens is to store them and discard requests with revoked tokens – And lose the benefits of being stateless :unamused:

**Comment by lcobucci** [comment]
Please check https://github.com/lcobucci/jwt/issues/80#issuecomment-192890099.

**Comment by lcobucci** [comment]
Will close it since it's not related to any library issue 😉
