### ISSUE TITLE
Support non-integer timestamps

### ISSUE THREAD

**Issue by kperry42** [lcobucci/jwt#144]
RFC 7519 clearly states (page 5) that for NumericDate properties, "non-integer values can be represented", but your version 3.2.1 code appears to cast all timestamps to (int)!  For instance, Builder's setExpiration() and setNotBefore(); and ValidationData's setCurrentTime().  A whole second is an eternity in CPU time.  Can we please have decimal seconds?

**Comment by lcobucci** [comment]
@kperry42 you're right. This was planned to be done for v4 when implementing #43.

An intermediate release (`v3.3`) is planned, and it will add deprecation notes on the methods and also (kind of) a compatibility layer with `v4`. Maybe we can port this too.
