### ISSUE TITLE
Downloading the source at 3.2.1 is missing Configuration.php

### ISSUE THREAD

**Issue by brianshaw** [lcobucci/jwt#145]
Downloading the source at 3.2.1 is missing Configuration.php

Not sure at what point it should be there. Or if it shouldn't be there then your documentation should be updated.

**Comment by Ocramius** [comment]
@brianshaw `Configuration.php` is in the current development branches: you'll probably see it when `4.0.0` is released.

**Comment by lcobucci** [comment]
@brianshaw there's a comment on README regarding that. If you would like to help us to improve you can check #37
