### ISSUE TITLE
Improve Builder interface methods

### ISSUE THREAD

**Issue by lcobucci** [lcobucci/jwt#150]
As per @henriquemoody and @Ocramius reviews on #129 we can make things more clear.
So let's discuss here to find the best names for `with()`, `canOnlyBeUsedBy()` and other method we would like to discuss about.

**Comment by lcobucci** [comment]
`withClaim()` is clearly better than `with()`

**Comment by lcobucci** [comment]
@Ocramius would `allowedTo()` be better than `canOnlyBeUsedBy()`? I think is pretty logical and also compatible with the constraints we created.

**Comment by Ocramius** [comment]
`allowedTo`... do what? (that's the question I ask myself when reading `allowedTo`.

**Comment by lcobucci** [comment]
allowed to as in "allowed to client A"

**Comment by Ocramius** [comment]
Still lacks expressivenes...

**Comment by lcobucci** [comment]
😭

**Comment by Ocramius** [comment]
@lcobucci ask the twitters?

**Comment by lcobucci** [comment]
@Ocramius can you do it plz?

**Comment by rdohms** [comment]
`clearedFor` as in "security clearance for client a"

**Comment by rdohms** [comment]
or `restrictedTo` if the `only` is still relevant.

**Comment by greg0ire** [comment]
`grantedTo`, like a right? I like `restrictedTo` too.

**Comment by nikolaposa** [comment]
I find `allow` as a term more appropriate than `restrict` because with every subsequent invocation of a method you are widening scope instead of narrowing it.

**Comment by nikolaposa** [comment]
... that being said, here are my suggestions:

- `allow()`
- `validFor()`
- `permit()`
- `permittedFor()`
- `grant()`

**Comment by rdohms** [comment]
@nikolaposa but the original name `canOnlyBeUsedBy` implies that its replacing all other grants with one restricted to the passed user. That's why i asked if the `only` is relevant.

**Comment by nikolaposa** [comment]
@rdohms Concrete implementation tells me that the actual idea of how method should behave is different: https://github.com/lcobucci/jwt/blob/master/src/Token/Builder.php#L63

**Comment by rdohms** [comment]
that's just bad naming then, i blame @lcobucci :D

**Comment by lcobucci** [comment]
> that's just bad naming then, i blame @lcobucci :D

@rdohms that's why this issue exists 😄

**Comment by lcobucci** [comment]
Thanks for the suggestions guys!

The idea of the `aud` claim is to have a list of clients that are allowed to use the token (basically a whitelist).

I'd say that `permittedFor()` is the closest one for that concept but I'm not sure it expresses what we want. Maybe dropping `canBeUsedBy()` is also a good idea (since it's causing the whole confusion), what you think @Ocramius?

**Comment by Ocramius** [comment]
@lcobucci "permission" is probably the closest to what the claim expresses (thanks for nothing, abbreviations, DUH.).

I'd go with `permittedFor`

**Comment by lcobucci** [comment]
@Ocramius cool let's go with that then. Do you think we should rename [`Lcobucci\JWT\Validation\Constraint\AllowedTo`](https://github.com/lcobucci/jwt/blob/43f30bc679b8e1efd8c9ad7844680a3a42342895/src/Validation/Constraint/AllowedTo.php) to make it consistent?
