### ISSUE TITLE
Out of nbf or exp Time Message?

### ISSUE THREAD

**Issue by michael-mammut** [lcobucci/jwt#151]
Hello @lcobucci , I am using  the following code snipped and I receive `true `or `false, `thats good,  but is it possible to receive a message, why the token is invalide? For example : `jwt - nbf - timestamp of nbf is not reached`  or `jwt - exp - token has expired`. 

```
        $validationData = new ValidationData();
        $jwtDec = (new Parser())->parse((string) $jwt);
       return  $jwtDec->validate($validationData );
```

**Comment by lcobucci** [comment]
@michael-mammut that's being done on #129 and it will be available for next major release 😉.

**Comment by lcobucci** [comment]
Closing as `duplicate` of #72.
