### ISSUE TITLE
How to check if the token was manipulated?

### ISSUE THREAD

**Issue by michael-mammut** [lcobucci/jwt#155]
Hello, I've created an example to be familiar with your API, validating token works very well, but a question today. How to check if the token was manipulated? I create the token on the server, send it to the client, and the client send the token back in the Authentication Header. 

` $val = new ValidationData();
  $jwt = (new Parser())->parse((string) $jwtInput);
   return  $jwt->validate($val );`

This returns false if the token has expired, but, how to check if  the token is not manipulated?

**Comment by schnittstabil** [comment]
You have to [sign](https://github.com/lcobucci/jwt#token-signature) and verify the token.

**Comment by michael-mammut** [comment]
Thank you...
