### ISSUE TITLE
Class 'Lcobucci\JWT\Configuration' not found in Laravel 5

### ISSUE THREAD

**Issue by bunlongheng** [lcobucci/jwt#157]
I ran  `sudo composer require lcobucci/jwt` to install the stuff.

Then, I added `use Lcobucci\JWT\Configuration;` on top of my file

Then, I start use the sample code

            $config = new Configuration(); // This object helps to simplify the creation of the dependencies
                                   // instead of using "?:" on constructors.
            $token = $config->createBuilder()
            ->issuedBy('https://login.uat.telenet.be/openid') // Configures the issuer (iss claim)
            ->canOnlyBeUsedBy('benu') // Configures the audience (aud claim)
            ->identifiedBy('888254e8-f1e8-4956-86fa-a6c0f61a6421', true) // Configures the id (jti claim), replicating as a header item
            ->issuedAt(time()) // Configures the time that the token was issue (iat claim)
            ->canOnlyBeUsedAfter(time() + 60) // Configures the time that the token can be used (nbf claim)
            ->expiresAt(time() + 3600) // Configures the expiration time of the token (exp claim)
            ->with('uid', 1) // Configures a new claim, called "uid"
            ->getToken(); // Retrieves the generated token
    
            $token->getHeaders(); // Retrieves the token headers
            $token->getClaims(); // Retrieves the token claims
    
            echo $token->getHeader('jti'); // will print "4f1g23a12aa"
            echo $token->getClaim('iss'); // will print "http://example.com"
            echo $token->getClaim('uid'); // will print "1"
            echo $token; // The string representation of the object is a JWT string (pretty easy, right?)

I kept getting this error

**Class 'Lcobucci\JWT\Configuration' not found**

How do I prevent that ?

**Comment by Ocramius** [comment]
Please refer to the [`3.2.1` tag](https://github.com/lcobucci/jwt/tree/3.2.1) when reading docs, since `master` has diverged quite a bit. You are reading docs for a version that wasn't released yet :-)

**Comment by bunlongheng** [comment]
You're right, I installed the 3.2 and refer the newer version. Thanks for correcting !
