### ISSUE TITLE
Impossible to set array value to Audience claim 

### ISSUE THREAD

**Issue by disharmonized** [lcobucci/jwt#172]
In your implementation i cant set audience array value, string only, but according to RFC, it must be possible
https://tools.ietf.org/html/rfc7519#section-4.1.3:

```
 In the general case, the "aud" value is an array of case-
   sensitive strings, each containing a StringOrURI value. 
```

**Comment by lcobucci** [comment]
This is not supported on the current version but is already implemented for next major release. If you really need it you can use it (it's not documented yet but works fine).

**Comment by lcobucci** [comment]
Closing as wont fix since it will only be available on v4.
