### ISSUE TITLE
Class 'Lcobucci\JWT\Configuration' not found

### ISSUE THREAD

**Issue by RudyJessop** [lcobucci/jwt#173]
I would advise someone update the documentation on the `readme` seeing that when using `Class 'Lcobucci\JWT\Configuration'` is non existent within the `src` folder. Do anyone know which file I have to call to create a token?

**Comment by Art4** [comment]
README.md says

> Important: this is the documentation of our next major release (v4) and it WILL change. If you are using the stable version you should go to branch 3.2.

**Comment by Ocramius** [comment]
Closing as per @Art4's comment
