### ISSUE TITLE
Vulnerability Found

### ISSUE THREAD

**Issue by Giovani-Brady** [lcobucci/jwt#175]
https://paragonie.com/blog/2017/03/jwt-json-web-tokens-is-bad-standard-that-everyone-should-avoid

Seems that the latest update to allow a None algorithm signature came with some security oversights.

**Comment by Ocramius** [comment]
Sigh, nope.

https://github.com/lcobucci/jwt/commit/6507ac39be5a5e06457c8ff8ad2c4d51d7d7b998#commitcomment-21304264

Closing as `invalid`.
