### ISSUE TITLE
Missing claims(): DataSet in Token interface

### ISSUE THREAD

**Issue by marekkobida** [lcobucci/jwt#176]
Missing:

    /**
     * Returns the token claims
     */
    public function claims(): DataSet;

**in src/Token.php interface** < src/Token/Plain.php

**Comment by lcobucci** [comment]
You won't have access to the claims of an encrypted token. That's why it's not on the interface.

**Comment by schnittstabil** [comment]
> You won't have access to the claims of an encrypted token.

May you explain this a bit further? Is this because of differences between JWT, JWE and JWS?

**Comment by lcobucci** [comment]
> Is this because of differences between JWT, JWE and JWS?

@schnittstabil yes.

This project only supports JWT, JWS and JWA however I do have plans (not anytime soon) to support encrypted tokens and that was to reason to create an interface for the token.
