### ISSUE TITLE
lcobucci / jwt (Laravel Passport)

### ISSUE THREAD

**Issue by ehababoshehab** [lcobucci/jwt#178]
hey,
sorry guys for this stupid question, but I am really fresh in the API authentication, and i need to figure it out.
what is the difference between this library and the one built in with passport in laravel framework.
thank you so much

**Comment by lcobucci** [comment]
@ehababoshehab this library doesn't offer any built-in integration with any framework. It is meant for building, parsing, and validating JWTs (that can be used for authentication or not).

I've found [some code in `laravel/passport`](https://github.com/laravel/passport/tree/052a2ba06dbab6448de569ace914c05419ce4f57/src/Http/Controllers) but I didn't go too far to see how they're using it.

I hope this helps 😉

**Comment by ehababoshehab** [comment]
@lcobucci thank you so much for this answer, but afteri install laraval/passport, one of the packages that will be installed is lcobucci/jwt and it has these classes (Builder, Claim, Parser, Signature, Signer, Token and ValidationData) and I am sure passport is using it to issue the token.

**Comment by lcobucci** [comment]
@ehababoshehab looking at [laravel/passport dependencies](https://packagist.org/packages/laravel/passport) I saw that it uses [league/oauth2-server](https://packagist.org/packages/league/oauth2-server) which depends on this library (but also on [firebase/php-jwt](https://packagist.org/packages/firebase/php-jwt)).
That means you have two JWT libs installed and I'm not sure which one is giving you headaches.

I suggest you to open an issue on stackoverflow (or `laravel/passport`) and ask for help, they will know more about how things works on their package.

If you're in fact using this lib to issue the token, check the [README]( https://github.com/lcobucci/jwt/blob/3.2/README.md) for more instructions 😉.

**Comment by ehababoshehab** [comment]
actually i did open an issue in laravel/passport and waiting for the reply ... and for passport im using lcobucci/jwt library and I am sure because i made some dumps ... and i had read the instructions in README .. it really clear and i had tied to follow it and it works fine ... but still passport using other things that i need to figure it out ....
thank you so much for your help :)

**Comment by lcobucci** [comment]
@ehababoshehab glad to help, please let me know if need something else.
