### ISSUE TITLE
JWT Builder Not Found

### ISSUE THREAD

**Issue by RezaNurRochmat13** [lcobucci/jwt#181]
I install from composer and i found this error Fatal error: Class 'Lcobucci\JWT\Builder' not found 
How i solve this problem thanks.

**Comment by Art4** [comment]
Use version 3.2.1, not 4.0.0-alpha1.

**Comment by Ocramius** [comment]
Closing as per @Art4's comment.

**Comment by Art4** [comment]
@Ocramius You should set up a bot for this 😆

**Comment by Ocramius** [comment]
@Art4 I try to be a bit human in these interactions: being on the side of somebody frustrated by a non-working package/library is terrible :-\

**Comment by Art4** [comment]
You're right. 👍
