### ISSUE TITLE
Implement ECDSA signer that uses OpenSSL

### ISSUE THREAD

**Issue by lcobucci** [lcobucci/jwt#187]
On Spomky-Labs/jose#161 @skyzyx commented that he's facing some performance issues with this library in his realtime API, based on @Spomky's response I've did some minor changes on his performance test (to adapt to `4.0.0-alpha1`) and I got this performance comparison (running on my laptop - PHP 7.1):

**it's important to say that this comparison is obviously just a reference and doesn't mean absolutely NOTHING in terms of which lib is better or not (specially because the implementations are different and @Spomky's lib supports JWK - that requires an additional complexity)**

**Signature**

Algorithm | Spomky-Labs/jose | lcobucci/jwt 
---------- | -------------------| ----------------
none         | 0.007670 ms/op    | 0.001469  ms/op
HS256      | 0.023170 ms/op    | 0.007911 ms/op
HS384      | 0.021369 ms/op    | 0.007732 ms/op
HS512       | 0.021610 ms/op    | 0.006850 ms/op
RS256       | 19.724061 ms/op  | 1.402881 ms/op
RS384       | 19.679730 ms/op | 1.385570 ms/op
RS512        | 19.765210 ms/op | 1.321239 ms/op
ES256       | 1.326001 ms/op    | 154.087379 ms/op
ES384       | 2.366140 ms/op   | 146.823630 ms/op
ES512        | 2.271872 ms/op    | 145.546641 ms/op

**Verification**

Algorithm | Spomky-Labs/jose | lcobucci/jwt 
---------- | -------------------| ----------------
none         | 0.007741  ms/op    |0.001271  ms/op
HS256     | 0.023739 ms/op     |0.014479 ms/op
HS384     | 0.023310 ms/op     | 0.008581 ms/op
HS512      | 0.023758 ms/op    | 0.008640 ms/op
RS256      | 17.913599 ms/op   | 0.065980 ms/op
RS384      | 18.093328 ms/op  | 0.068090 ms/op
RS512      | 17.817550 ms/op    | 0.067239 ms/op
ES256      | 1.715958 ms/op      | 295.684772 ms/op
ES384     | 3.032808 ms/op     | 283.335109 ms/op
ES512      | 3.423491 ms/op     | 294.083581 ms/op

It's really clear that ECDSA is far from being good (is quite depressing to be honest) in terms of performance and the big difference is that in @Spomky's implementation that algorithm uses primarily OpenSSL and phpecc as fallback when the ECDSA is not supported in server.

I'm still thinking if I want to have the same fallback idea or to provide two different implementations but I'm more inclined to go with the latter.

Thanks @ivanrosolen for pointing out the issue to me and @Spomky for providing a such complete implementation for JOSE 🍻 

@skyzyx would you mind sharing your issues with my lib here as well?

**Comment by Spomky** [comment]
Hi @lcobucci 

Thank you for this nice comparison!
It also quite depressing for me too to see that your lib is incredibely faster.
The JWK implementation may explain this, but from my point of view the real problem is the use of several third party libraries (e.g. the Assertion library).

> I'm still thinking if I want to have the same fallback idea or to provide two different implementations but I'm more inclined to go with the latter.

I agree with you. On the next revision I will remove that fallback. I think it is a bad idea to keep a pure PHP fallback when the library is used in production.

Let me know if you need help for your OpenSSL implementation, I will be happy to share my experience with you.

**Comment by lcobucci** [comment]
On #189 I added `phpbench` to the project. I've started some experiments with an OpenSSL version of the ECDSA signer and the results are quite promising:

|       Signer         | Operation |          Before       |       After             |
|----------------|-----------|-----------------|-----------------|
| Ecdsa\Sha256 | Sign           | 31,651.140 (μs)  |      198.310 (μs) |
| Ecdsa\Sha256 | Verify        | 58,454.050 (μs) |     382.550 (μs) |
| Ecdsa\Sha384 | Sign           | 31,633.910 (μs) |      219.040 (μs) |
| Ecdsa\Sha384 | Verify        | 64,479.270 (μs) |     397.500 (μs) |
| Ecdsa\Sha512 | Sign           | 31,780.130 (μs)  |      216.230 (μs) |
| Ecdsa\Sha512 | Verify         | 58,850.470 (μs) |     350.800 (μs) |

I'll be thinking on how to organise things properly to not add too many "weird stuff" to the library.
