### ISSUE TITLE
`$token->validate(ValidationData);` Could return _what_ is invalid

### ISSUE THREAD

**Issue by Firesphere** [lcobucci/jwt#193]
By returning the object that fails validation alongside a validation error would make it easier for implementations to return a useful error message.
This would be a breaking change (thus, only possible for v4), but an example would be to change `Token::validate()` to something like the following:
```
    public function validate(ValidationData $data)
    {
        $result = ['valid' => true];
        foreach ($this->getValidatableClaims() as $claim) {
            if (!$claim->validate($data)) {
                $result['valid'] = false;
                $result['claim'][] = $claim; // Add up all failing claims in an array
            }
        }

        return $result;
    }
```

**Comment by lcobucci** [comment]
@Firesphere v4's validator already have a [similar behaviour](https://github.com/lcobucci/jwt/blob/561bc8529e71ca754b6236143fc140e940bc5944/src/Validation/Validator.php#L24-L35). That won't be backported to v3.

**Comment by Firesphere** [comment]
Awesome! Didn't see that as I'm currently working with v3 (as it's stable)

And I don't expect it to be backported to v3 as it would be a break in semver ;)

Thanks! Closing this issue as it's a non-issue :)

**Comment by lcobucci** [comment]
@Firesphere awesome, thanks.

v4 is almost done and there's an alpha release, the API will suffer some small changes but everything is working (even better than in v3 😉). I'm just overwhelmed with paid work that I didn't manage to continue my work here, however I do encourage people to try things out (if possible).
