### ISSUE TITLE
there's no method setIssuedAt in Builder

### ISSUE THREAD

**Issue by agalstyan** [lcobucci/jwt#20]
there's a typo in method name. it's called "setIssueAt" instead of "setIssuedAt"

**Comment by lcobucci** [comment]
Wow this is a nasty typo! Thanks for pointing it out.

I'll fix it right now and create the 2.1.1 version ;)

**Comment by lcobucci** [comment]
@agalstyan all fixed and released, please update to 2.1.1 and have some :beers:

**Comment by agalstyan** [comment]
nice, thanks)
