### ISSUE TITLE
How get Claims after encode token

### ISSUE THREAD

**Issue by lpj145** [lcobucci/jwt#203]
I'm try to get claim on middleware.
Using Version 4.0@dev
![image](https://user-images.githubusercontent.com/11980109/31547582-406dfa60-affe-11e7-990a-95531931d87e.png)
But `parse` function return Plain, this is a error ?
![image](https://user-images.githubusercontent.com/11980109/31547642-87568622-affe-11e7-843d-d12d8cd92e27.png)

**Comment by lcobucci** [comment]
@lpj145 that's a forward compatibility layer. As stated on #6 we plan to support encrypted tokens (which will implement that interface).

Since `parse()` deals with untrusted data, users are supposed to verify if they have the expected type of token, like:

```php
$token = $this->parser->parse($jwt);

if (! $token instanceof Plain) {
    // You should have your own exception for that, sure =)
    throw new \RuntimeException('The provided token is not valid');
}
```

**Comment by lcobucci** [comment]
btw don't forget to validate the token properly using the validator 😉

**Comment by lpj145** [comment]
yep i'm using:
```
/**
     * @param Plain $token
     * @return bool
     */
    private function tokenIsValid(Plain $token)
    {
        if ($token->isExpired((new SystemClock())->now())) {
            return false;
        }

        try {
            $this->validator->assert($token, new SignedWith($this->signer, $this->key));
        }catch (ConstraintViolationException $exception) {
            return false;
        }

        return true;
    }
```

**Comment by lcobucci** [comment]
@lpj145 if you're not using the exception, I'd suggest to use this instead (I really need to work on the documentation 😭 ):

```php
return $this->validator->validate(
    $token,
    new ValidAt(new SystemClock()),
    new SignedWith($this->signer, $this->key)
);
```

The benefit with that approach is that the validator will stop its process when the first error comes and the constraints will be processed in the order you called the method, so you can leave the "expensive" operations to the end of your validation chain.

I'd also suggest to have the list of constraints injected, so it makes it easier for you (we're planning to add it to the `Configuration` object):

```php
return $this->validator->validate($token, ...$this->constraints);
```

**Comment by lcobucci** [comment]
@lpj145 let me know if your question has been answered and we can close this issue 👍

**Comment by lpj145** [comment]
I think this is a good solution, but need tests. in hour i answer to you.
```
public function process(ServerRequestInterface $request, DelegateInterface $delegate)
    {
        if (
            $this->middlewareConfig['secure'] &&
            $request->getUri()->getScheme() !== 'https' ||
            !$request->hasHeader('Authorization')
        ) {
            return new Unauthorized();
        }

        $jwt = $this->getTokenWithoutBearer($request->getHeaderLine('Authorization'));

        /** @var Plain $token */
        $token = $this->parser->parse($jwt);
        if (
            !$token instanceof Plain ||
            !$this->tokenIsValid($token)
        ) {
            return new Unauthorized();
        }

        return $delegate->process($request);
    }
```
