### ISSUE TITLE
Verify only the struct of token

### ISSUE THREAD

**Issue by henriqueweiand** [lcobucci/jwt#205]
I can verify only the struct of token without the instance new ValidationData()?

**Comment by lcobucci** [comment]
Can you give more info on what you're trying to achieve?

**Comment by lcobucci** [comment]
On v3 the `ValidationData` instance is required, v4 (alpha) "fixes" it by using constraints - and you're able to create your own constraints and validate them in the order you define.

**Comment by henriqueweiand** [comment]
In my case, isn't necessary to verify expiration date of token. Just verify de struct with signature of token.

Performing some tests,  I did it like this:
`
try {
   $token = (new Parser())->parse((string)$token);

   if(!$token->verify($signer, env('JWT_SECRET')))
      return response('Unauthorized.', 401);
} catch(\RuntimeException $e) {
   return response('Unauthorized.', 401);
}
`

this alternative is correct? suggestions?

**Comment by lcobucci** [comment]
@henriqueweiand yeap, that does what you need. I would recommend to make sure the token is still valid, though.
Using tokens that don't expire is not really secure but if you're 100% sure that you have no point where someone could potentially read the token you should be fine.
