### ISSUE TITLE
get payload from token in controller

### ISSUE THREAD

**Issue by williansmartins** [lcobucci/jwt#212]
Is possible get payload from token in controller?

**Comment by lcobucci** [comment]
@williansmartins this library doesn't provide anything regarding controllers, so I'm not sure what you're trying to do...

Maybe you're using something that connects `lcobucci/jwt` to a framework? If so, I'd suggest you to move the discussion to that library/module/bundle/* 😃

**Comment by williansmartins** [comment]
I was using lcobucci with laravel, but I will not more use, thanks
