### ISSUE TITLE
This token cann't use secret base64 encoded?

### ISSUE THREAD

**Issue by fouthfire** [lcobucci/jwt#217]
![image](https://user-images.githubusercontent.com/25971524/34401484-86f09cb8-ebd6-11e7-94e6-09bedef03de5.png)

Signature always Invalid!

**Comment by lcobucci** [comment]
@fouthfire I don't what you're trying to achieve here... base64 encoded keys are usually used when they are not plain strings (like binary content).

What jwt.io does is simply decoding they key you provide using base64 before of checking the signature. A token that was signed with a plain string can never have its signature verified using a base64 decoded key.

This library will simply create the signature with the key that you provide, if you want to use an encoded key you have to encode it first.

Does this help?

**Comment by lcobucci** [comment]
@fouthfire did my answer help you? If so, can we close this issue?

**Comment by fouthfire** [comment]
Actually, I need decode it first.

**Comment by pyaehein** [comment]
@fouthfire @lcobucci 
How can I encode and decode with base64? I stuck in here. I wrote as
 
`->sign($signer, base64_encode($my_secret_key))`

It showed "Invalid Signature" in jwt.io

**Comment by fouthfire** [comment]
maybee you can try
->sign($signer, base64_decode($my_secret_key))

**Comment by husunwang** [comment]
if secret is not encoded by base64, and I click 'secret base64 encoded'. how would it generate a secret?

**Comment by abhijain03** [comment]
How to generate token with some secret code without the secret base64 encoding.

**Comment by Ocramius** [comment]
Base64 is a bijecttive pure function: you can apply encoding/decoding yourself

**Comment by rishabhchd19** [comment]
We want keeping the secret code but unchecked the secret base64 encoded. How can we do that using library?

![34401484-86f09cb8-ebd6-11e7-94e6-09bedef03de5](https://user-images.githubusercontent.com/30948461/58374155-1c963880-7f57-11e9-9075-c2a2b4620ec3.png)

Like this kind of token we are using.
