### ISSUE TITLE
verify method

### ISSUE THREAD

**Issue by henriqueweiand** [lcobucci/jwt#220]
does the verify method validate if these entries are correct?

example:
-> setIssuedAt (time ()) -> setNotBefore (time () + 60) -> setExpiration (time () + 3600)

I mean, if the expiration time is already over, will it return false on a verify call for example?

**Comment by lcobucci** [comment]
@henriqueweiand that's done based on the `ValidationData` object you pass to the method. By default it uses the current time to validate stuff (using `time()`), but the current time can be injected. `Token#verify()` will do the validation only if the token has the claims, and it indeed returns a boolean.

You can find examples in:

https://github.com/lcobucci/jwt/blob/3.2.2/test/functional/UnsignedTokenTest.php#L89-L96

**Comment by lcobucci** [comment]
@henriqueweiand did my answer help you? If so, can we close this issue?
