### ISSUE TITLE
Problems verifying Firebase Token

### ISSUE THREAD

**Issue by rubobaquero** [lcobucci/jwt#222]
Hi,

In our project we use your library for generating/validating/verifying JWT tokens without problems. Now, we want to accept Firebase idTokens, so we have to parse, validate and verify their signature.

We can parse and validate them without problems, but we are having issues verifying the signature. This is our code:

```php
use Lcobucci\JWT\Signer\Keychain;
use Lcobucci\JWT\Signer\Hmac\Sha256;
use Lcobucci\JWT\Parser;
use Lcobucci\JWT\ValidationData;

// First: parse JWT token (OK)
$token = (new Parser())->parse((string) $google_token);
    		
// Second: validate (OK)
$validator = new ValidationData(); // It will use the current time to validate (iat, nbf and exp)
$validator->setIssuer('https://securetoken.google.com/<project_id>');
$validator->setAudience('<project_id>');
var_dump($token->validate($validator));
    		
// Third: check signature (Verify returns false)
$signer = new Sha256();
$keychain = new Keychain();
$kid = $token->getHeader('kid');
$certificates = json_decode(file_get_contents('https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com'),true);
if(isset($certificates[$kid])){
	var_dump($token->verify($signer, $certificates[$kid]));
}
else {
	throw new \Exception("Invalid token, wrong certificate kid",400);
}
```

Signature is verified without problems in JWT.io validator using the correct certificate, but the verify method returns false.

**Comment by Ocramius** [comment]
Could you scramble the retrieved `$certificates` and dump it here? (not your actual ones!)

**Comment by lcobucci** [comment]
@rubobaquero also, are you sure that the algorithm you're using is HMAC-SHA256 and not a RSA-256?

**Comment by lcobucci** [comment]
Considering that you have a public URL that has all your keys I'd assume you're using an asymmetric algorithm, otherwise anyone would be able to create tokens on your behalf.

**Comment by rubobaquero** [comment]
Hi, thanks for your answers @Ocramius and @lcobucci .

Tokens are generated by Google Firebase. What i am trying to do is to verify that tokens are really generated by them using their public keys. This URL contains all the public keys of Google for verifying the signature:

https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com

In the JWT.io validator, this is the info that appears in the headers section:
```
{
  "alg": "RS256",
  "kid": "72a01e4aeb4057b7996db1028d1ecff45aa239e1"
}
```

As the kid is 72a01e4aeb4057b7996db1028d1ecff45aa239e1, I should use this certificate from the URL above:

-----BEGIN CERTIFICATE-----
MIIDHDCCAgSgAwIBAgIIIdjhwLPBoVIwDQYJKoZIhvcNAQEFBQAwMTEvMC0GA1UE
AxMmc2VjdXJldG9rZW4uc3lzdGVtLmdzZXJ2aWNlYWNjb3VudC5jb20wHhcNMTgw
MjIwMDA0NTI2WhcNMTgwMjIzMDExNTI2WjAxMS8wLQYDVQQDEyZzZWN1cmV0b2tl
bi5zeXN0ZW0uZ3NlcnZpY2VhY2NvdW50LmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBAKNJopBZXMPrSbqXQkJb1ZOCsBKxsIOmOI1Nj3fcmQ325/GG
xRUIiYj8q2UcAtGZ3grWR9WYanz9C9Gw5kP2G3wgL82kE5+HZ6TFMuC6ZbPubcKK
RRRC6ZTen0EQrBRzX6JEtnjz5wKJ2sNlfV2xSZqqkOfSAVG8P6Lvqx+KljLIR/Pd
FTI1ey49axxOzUVt9kAB+fRvzQg3KeYWF7Fj2wo1N2gW0n4Ir7Nf20+SnNcNOf5J
MAhPeraKcsqVcJ1CKs1h3SUZmWSCdHafpCb3DBn5RYPFGoqq6edXxJoNAsEEMQ7/
Uxc8/anA4OxpTUuusrapTleqGPXGHO4Rz8V1ZhcCAwEAAaM4MDYwDAYDVR0TAQH/
BAIwADAOBgNVHQ8BAf8EBAMCB4AwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwIwDQYJ
KoZIhvcNAQEFBQADggEBAFUHGYZHhO8RzV8/JWrIh4UY6f/5BFcOQs/01Rfo+Ptg
pGK6D4rpK203wdhmG8A7N3kLLs4wJeb3L2n1yDWCsvpdpoBl4gSGx4X7/DLj2xSU
a/h1vHEKMeXRYA9/Y14OjzlmkXkbbEatHdxQnkZI+oMcaEpb7DT9krRJgU0u8gYL
sRto0NEwjCmdcazthlZb+2CDDqXDpPuLc4bHyVC7rk/c0wRSrYTF/Ra2Ei1g09/J
aiRavEBGcD8STI91J/dT+NBOZGVvzFZahRV8mrZtU6AtdN25uRb8AO7MBen1ed0U
ZocF1JkTQfsAL4oWl/LB1PUynJbP9BAUBon/ZK0cGfA=
-----END CERTIFICATE-----

If I paste the token and the certificate in JWT.io, it says that the signature is validated. But this library returns false for the verify() call.

**Comment by rubobaquero** [comment]
In the following URL is the documentation of Google Firebase where it explains the methodology (that i think that i am applying well in the code that i pasted in the issue):

https://firebase.google.com/docs/auth/admin/verify-id-tokens?hl=en#verify_id_tokens_using_a_third_party_jwt_library

**Comment by lcobucci** [comment]
@rubobaquero so it's indeed a RSA-256 signature... the problem with your code is that you're trying to verify the token using the wrong algorithm, and applying this change should solve your issue:

```diff
 use Lcobucci\JWT\Signer\Keychain;
-use Lcobucci\JWT\Signer\Hmac\Sha256;
+use Lcobucci\JWT\Signer\Rsa\Sha256;
 use Lcobucci\JWT\Parser;
 use Lcobucci\JWT\ValidationData;

 // First: parse JWT token (OK)
 $token = (new Parser())->parse((string) $google_token);
    		
 // Second: validate (OK)
 $validator = new ValidationData(); // It will use the current time to validate (iat, nbf and exp)
 $validator->setIssuer('https://securetoken.google.com/<project_id>');
 $validator->setAudience('<project_id>');
 var_dump($token->validate($validator));
    		
 // Third: check signature (Verify returns false)
 $signer = new Sha256();
 $keychain = new Keychain();
 $kid = $token->getHeader('kid');
 $certificates = json_decode(file_get_contents('https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com'),true);
 if(isset($certificates[$kid])){
 	var_dump($token->verify($signer, $certificates[$kid]));
 }
 else {
 	throw new \Exception("Invalid token, wrong certificate kid",400);
 }
```

**Comment by rubobaquero** [comment]
Thank you very much @lcobucci . Changing the algorithm made the verification work :-)
