### ISSUE TITLE
how to use without composer

### ISSUE THREAD

**Issue by weituotian** [lcobucci/jwt#232]
do not have an composer
is there any other way to use it.
may someone provide an autoload file?

**Comment by Ocramius** [comment]
99% of the PHP libraries out there rely on composer to get installed and set up, and  so does this one: please do get started at https://getcomposer.org/

**Comment by jowjon67** [comment]
And if we don't have access internet in our server?

**Comment by Ocramius** [comment]
You deploy a finished/assembled tarball
