### ISSUE TITLE
Preconfigured Builder and Verifyer

### ISSUE THREAD

**Issue by AAllport** [lcobucci/jwt#234]
Question:
Is it currently possible to preconfigure the builder and verifier, to avoid repetition of code?
This would include the secret and signer
I have noticed a ClaimFactory, would I half to use this and pass it as an argument? However, this does not include the Signer and Secret.
Is there a better way that allows me to use the human-readable functions (`setIssuedAt`) as opposed to the short names (`iat`,`jti`, etc)?

**Comment by Ocramius** [comment]
What kind of repeated code?

If you have repetitions, stash them into a function abstracting the common bits.

As for the "human-readable functions", please jump in on the development on `master`, where these are better defined :+1:
