### ISSUE TITLE
PEM_read_bio:bad end line,why?

### ISSUE THREAD

**Issue by lovearthhome** [lcobucci/jwt#236]
`PHP Fatal error:  Uncaught InvalidArgumentException: It was not possible to parse your key, reason: error:0906D066:PEM routines:PEM_read_bio:bad end line in /var/www/html/agi.xdua.com/jwt/vendor/lcobucci/jwt/src/Signer/Rsa.php:60
`

**Comment by Ocramius** [comment]
You will need to look up the openssl docs, but it may be that your key was not generated with correct (`\n`) line endings.

https://github.com/lcobucci/jwt/blob/3.2/src/Signer/Rsa.php#L44

**Comment by lcobucci** [comment]
@lovearthhome did you check what @Ocramius said? How did you generate the key?

**Comment by lcobucci** [comment]
@lovearthhome closing due to lack of info, please reopen if needed.
