### ISSUE TITLE
Random invalid token error (BUG?)

### ISSUE THREAD

**Issue by MurtazaAydogdu** [lcobucci/jwt#243]
I am using this library for my project and when I want to get data from the database the library throws a n error "invalid token". Also when I wait for a couple of minutes and try to get data from the database it works

**Comment by lcobucci** [comment]
@MurtazaAydogdu can you please provide more information regarding this? The token, algorithm you're using, the stack trace... everything you can.

**Comment by MurtazaAydogdu** [comment]
Thanks for the fast reply. In our company we are using your library as an SDK for the authentication. We have our custom invalid message, so I think it will be the same in the library. The algorithm we are using  is the RS256.

**token:**     	eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOjE2LCJyb2xlIjoiREVWIiwiaWF0IjoxNTIxNTUxMTg2LCJleHAiOjE5MjY2NTc1OTgsIm9yaWdpbiI6ImRpZ2l0YWxlZmFjdHV1ciIsImF1ZCI6WyJkaWdpdGFsZWZhY3R1dXIiXSwiaXNzIjoiQXV0aGVudGljYXRpb24gU2VydmVyIiwianRpIjoiMWRiNTk2YWQtYjMyMy00Zjg4LTk0ZjUtNmU3NDg1YTdlYzBkIn0.Ak4oYVQiolMPZl5dBxHg1k6Y5KVBVaZoHbi2KQeOn8iO8OSzUEHg4vk_dU5I-2IJxrghgIgonGYqYOKvmyz3NQ

**Comment by lcobucci** [comment]
> base64_decode($this->config->getSignKey($origin))

@MurtazaAydogdu this bit is not part of the library, are you 100% confident that you always have a valid RSA public key there?

And since you're using RSA your verification key is public, can you send it? And also the stack trace of the exception you're capturing...

Which PHP and OpenSSL versions you have?

**Comment by MurtazaAydogdu** [comment]
After searching for a long time. I found the problem was not in your library but in our sdk.

**Comment by lcobucci** [comment]
Ahhh alright, thanks for the update 👍
