### ISSUE TITLE
mdanter_ecc Singer Ecdsa KeyParse Issue

### ISSUE THREAD

**Issue by kapil-infobeans** [lcobucci/jwt#246]
I got below error:

 \Mdanter\Ecc\Primitives\prime. Actual type: int

Thanks

**Comment by lcobucci** [comment]
@kapil-infobeans can you please provide information on what happened here?

**Comment by kapil-infobeans** [comment]
Thank you for quick response, I was running the application on PHP 7.1 and
I was trying to use old version 3.2.0, so there was some errors. Now by
using latest 4.0 aplha veraion, it's working without any issues.

On 13 Jun 2018 8:19 pm, "Luís Cobucci" <notifications@github.com> wrote:

@kapil-infobeans <https://github.com/kapil-infobeans> can you please
provide information on what happened here?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/lcobucci/jwt/issues/246#issuecomment-396965173>, or mute
the thread

**Comment by lcobucci** [comment]
@kapil-infobeans right, please keep in mind that `v4` still alpha - which means that public interface is not fully stable yet (it's completely tested and fully functional, though).

We have cronjobs running on travis to check the supported branches but PHP 7.1 is not there yet, I'll add it soon and see what are the issues you're mentioning

**Comment by lcobucci** [comment]
#288 just backported PHP 7.1-7.3 support, can you please change your requirements to `3.3.x-dev` and check if things are working fine for you? **Important:** this is still a development version and shouldn't be used in production yet.

**Comment by kapil-infobeans** [comment]
Thanks!
<http://bit.ly/InfoBeans_esignature_website>
  <http://bit.ly/InfoBeans_esignature_facebook>
<http://bit.ly/InfoBeans_esignature_twitter>
<http://bit.ly/InfoBeans_esignature_linkedin>

**Comment by lcobucci** [comment]
Preparing the release of v3.3.0 now, so this can be closed.
