### ISSUE TITLE
Allow null as default value for getClaim

### ISSUE THREAD

**Issue by iluuu1994** [lcobucci/jwt#249]
Disclaimer: I'm not sure if this is still relevant for `4.0`.

The current implementation of `getClaim` does not allow null-values:

```php
public function getClaim($name, $default = null)
{
    if ($this->hasClaim($name)) {
        return $this->claims[$name]->getValue();
    }

    if ($default === null) {
        throw new OutOfBoundsException('Requested claim is not configured');
    }

    return $default;
}
```

Even if you specifically provide the default value:

```php
$token->getClaim('sub', null);
```

> OutOfBoundsException

This could be solved by simply changing this line:

```php
if ($default === null) {
```

to

```php
if (func_num_args() === 1) {
```

**Comment by lcobucci** [comment]
@iluuu1994 it's indeed not relevant for v4 but we can plan it for v3.3. I'll be working on it in the upcoming month 👍

**Comment by lcobucci** [comment]
Handled by #432
