### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by SandroBCIT** [lcobucci/jwt#251]
Is there a way to refresh the token using this library?

**Comment by ericktedeschi** [comment]
The way how you manage tokens is about your implementation, not the lib.
Identity providers (oauth2 + openid connect + jwt) do the job for you about
"persistent login"... and much more in a real application.

My point is: if you need refresh tokens... probably you are implementing an
authorization server (rfc 6749 and more)... if not. Probably you are
implementing something based upon concepts that already exists in an open
standard.

**Comment by vigor-vlad** [comment]
Well, it lies out of the scope of the library. It can be used to generate both the access and the refresh tokens, but as for the refresh process itself, it should be handled by your app.

**Comment by lcobucci** [comment]
@SandroBCIT as people mentioned here, refreshing and revoking tokens is not responsibility of any JWT library. This is up to you to define (or decide to use a standard as @ericktedeschi said).

Closing here, please re-open if you feel the need to discuss it further 👍
