### ISSUE TITLE
why do that? replace char

### ISSUE THREAD

**Issue by yangqinjiang** [lcobucci/jwt#252]
## vendor /lcobucci /jwt /src /Parsing / Decoder.php
```

    /**
     * Decodes from base64url
     *
     * @param string $data
     * @return string
     */
    public function base64UrlDecode($data)
    {
        if ($remainder = strlen($data) % 4) {  //  why,why,why
            $data .= str_repeat('=', 4 - $remainder);
        }
        return base64_decode(strtr($data, '-_', '+/'));//  why,why,why
    }
```
## I modify it for other systems write by golang
```
    public function base64UrlDecode($data)
    {
       return base64_decode($data);
   }
```

**Comment by lcobucci** [comment]
I hope that this answers you, please re-open the issue if you need more information.

**Comment by yangqinjiang** [comment]
OKkkkk.I try to verify the token by golang

**Comment by lcobucci** [comment]
@yangqinjiang sure, just make sure the implementation uses base64url and not base64, otherwise your token would be incorrect and not compliant with the spec. https://jwt.io might help you find good options.
