### ISSUE TITLE
Error token can be used normally

### ISSUE THREAD

**Issue by amd5** [lcobucci/jwt#253]
I directly loaded the SDK
generate token

Then  Use token Decrypt             Return   ok
modify token At the end of an arbitrary string                                              Decrypt         Return   ok

**Comment by amd5** [comment]
use Lcobucci\JWT\Parser;
use Lcobucci\JWT\Builder;
use Lcobucci\JWT\Signer\Hmac\Sha256;

PHP frame name
thinkphp 5.0.20

`
public function index(){
		$builder = new Builder();
		$signer  = new Sha256();
		// 设置发行人
		$builder->setIssuer('https://app01.test.com'); 
		// 设置接收人
		$builder->setAudience('https://app01.test.com'); 
		// 对当前token设置的标识
		$builder->setId('4f1g23a12aa', true); 
		// 设置生成token的时间
		$builder->setIssuedAt(time()); 
		// 设置在6秒内该token无法使用
		$builder->setNotBefore(time() + 6); 
		// 设置过期时间
		$builder->setExpiration(time() + 3600); 
		// 给token设置一个id
		$builder->set('uid', 1); 
		// 对上面的信息使用sha256算法签名
		$builder->sign($signer, '签名key');
		// 获取生成的token
		$token = $builder->getToken();
		dump((string)$token);
	}
`
ok token
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IjRmMWcyM2ExMmFhIn0.eyJpc3MiOiJodHRwczpcL1wvYXBwMDEud3lzeXQuY29tIiwiYXVkIjoiaHR0cHM6XC9cL2FwcDAxLnd5c3l0LmNvbSIsImp0aSI6IjRmMWcyM2ExMmFhIiwiaWF0IjoxNTMyOTQwNzMyLCJuYmYiOjE1MzI5NDA3MzgsImV4cCI6MTUzMjk0NDMzMiwidWlkIjoxfQ.4jBBsprDas0ONOuXEoxc5umn4KpGj9CjWd-mf5TJss8

error  token 
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IjRmMWcyM2ExMmFhIn0.eyJpc3MiOiJodHRwczpcL1wvYXBwMDEud3lzeXQuY29tIiwiYXVkIjoiaHR0cHM6XC9cL2FwcDAxLnd5c3l0LmNvbSIsImp0aSI6IjRmMWcyM2ExMmFhIiwiaWF0IjoxNTMyOTQwNzMyLCJuYmYiOjE1MzI5NDA3MzgsImV4cCI6MTUzMjk0NDMzMiwidWlkIjoxfQ.4jBBsprDas0ONOuXEoxc5umn4KpGj9CjWd-mf5TJss9

All 2 decryption returns to normal

**Comment by amd5** [comment]
Answer？

**Comment by lcobucci** [comment]
@amd5 it looks like you're just tampering the signature of the token, which is not being validated by your code. As mentioned on https://github.com/lcobucci/jwt/blob/3.2/README.md parsing, validation, and signature verification are different concepts.

I advise you to read a bit more into the JWT world to understand the basic format and how to use it properly.

**Comment by lcobucci** [comment]
I also suggest you to upgrade your PHP stack, this library requires (and it's fully tested with) PHP 5.5+. In the next minor release we're going to require PHP 5.6 and the major will probably require PHP 7.2.

**Comment by lcobucci** [comment]
Btw, you can also use https://jwt.io to validate your valid and invalid tokens

**Comment by lcobucci** [comment]
I'm sorry, there's another potential issue with your code which is the fact that you're using a weak algorithm (HS256) and a very small key. I'd also advise to use an asymmetric algorithm like RSA to avoid that.

**Comment by Spomky** [comment]
@amd5 The modification of the last character(s) i.e. the signature part may not change the decoded binary value (the signature is just base64url safe encoded). Please refer to [this answer](https://stackoverflow.com/questions/26432112/jwtsecuritytokenhandler-says-signature-of-jwt-valid-after-changing-1-char/26618941#26618941) and also all other similar questions on stackoverflow.

@lcobucci [this draft](https://tools.ietf.org/html/draft-irtf-cfrg-webcrypto-algorithms-00#section-18) is not up to date (May 2016) but I am not sure HS256 is so weak. Collision are still possible however no demonstration of attacks have been made. It still can be used when asymmetric algorithms cannot be used.

**Comment by lcobucci** [comment]
@Spomky thanks for your explanation, you're indeed correct about the two things. I tend to avoid symmetric algorithms as much as possible but I agree that it can still be used (but with a stronger key IMO).
