### ISSUE TITLE
Error while decoding to JSON

### ISSUE THREAD

**Issue by Tonkong** [lcobucci/jwt#255]
RuntimeException Object ( [message:protected] => Error while decoding to JSON: Malformed UTF-8 characters, possibly incorrectly encoded [string:Exception:private] => [code:protected] => 0 [file:protected] => /Users/tangkang/web/yii2/vendor/lcobucci/jwt/src/Parsing/Decoder.php [line:protected] => 36 [trace:Exception:private] => Array ( [0] => Array ( [file] => /Users/tangkang/web/yii2/vendor/lcobucci/jwt/src/Parser.php [line] => 112 [function] => jsonDecode [class] => Lcobucci\JWT\Parsing\Decoder [type] => -> [args] => Array ( [0] => ��z��'G�#�$�uB"�&�r#�$�3#Sb"�&�F�#�'F�r'� ) ) [1] => Array ( [file] => /Users/tangkang/web/yii2/vendor/lcobucci/jwt/src/Parser.php [line] => 60

**Comment by Tonkong** [comment]
I have already solved the problem。

`if (preg_match('/Bearer\s(\S+)/', $auth, $matches)) {
            $tokenStr = $matches[1];
}`

**Comment by lcobucci** [comment]
Ohh I see, thanks for explaining the reason. Please let us know if need help with anything else.
