### ISSUE TITLE
Unable to use ECDSA signer on PHP 7.2 (request to update mdanter/ecc dependency)

### ISSUE THREAD

**Issue by shakura** [lcobucci/jwt#259]
To use ECDSA signer it is required to install mdanter/ecc version ~0.3.1. But this extension requires php-mcrypt which was deprecated in PHP 7.1 and was deleted in PHP 7.2. 
Latest mdanter/ecc (0.5.0) doesn't depend on mcrypt but however it is incompatible and throws an exception: 
```Type error: Argument 1 passed to Lcobucci\JWT\Signer\Ecdsa\KeyParser::__construct() must be an instance of Mdanter\Ecc\Math\MathAdapterInterface, instance of Mdanter\Ecc\Math\GmpMath given, called in /vendor/lcobucci/jwt/src/Signer/Ecdsa.php on line 50```

**Comment by lcobucci** [comment]
@shakura at the moment PHP 7.1+ is not supported by the stable releases we have, v4-alpha1 is usable and fully tested but the interface is not 100% stable.

I'll be addressing this issue with the v3.3 ASAP.

**Comment by nmiller12** [comment]
Hi, is there an ETA for this? I also have this issue of being unable to use the stable release due to issue with mdanter/ecc, php-mcrypt, PHP 7.2

**Comment by lcobucci** [comment]
@nmiller12 not yet, #247 fixes that already but needs some minor changes and then be applied in 3.3-dev.

**Comment by nmiller12** [comment]
no problem. thanks for the quick reply.

**Comment by alexandrmazur96** [comment]
Hi! Has news?)

**Comment by lcobucci** [comment]
@alexandrmazur96 yeap, that got merged in and I'm working on backporting things to v3.3 (to also offer a decent migration path to v4). No schedule, though (sorry)

**Comment by lcobucci** [comment]
I will probably have many v3.x releases to have the **full** migration path - because there're still more things undecided on v4

**Comment by BillRiess** [comment]
Is there any update on this?

**Comment by Gerben-T** [comment]
@lcobucci Do you have an ETA on a 3.x release that fixes this issue? The library is currently unusable for me because of this issue.

**Comment by lcobucci** [comment]
@Gerben-T @BillRiess I don't have an ETA at the moment. I'm focused on supporting #276 and backporting some of the new features of v4 - which is a lot of work. Once that PR gets merged in I'll probably tag another alpha of v4, which is 100% functional at the moment - just have a different, and undocumented, API.

I **hope** to get everything done in about 2~3 weeks. I'd suggest you to check v4 API if you do need to have it done before of that - v3.3 shall be 100% compatible with both.

**Comment by Gerben-T** [comment]
@lcobucci Thanks for the quick response, sadly i'm working with PHP 5.5.x at the moment so i can't use the v4 api..

**Comment by Gerben-T** [comment]
I get the same error as the issue starter while on v3.2.5 and PHP 5.6.
This is my code

```
use Lcobucci\JWT\Builder;
use Lcobucci\JWT\Signer\Keychain; **<- This is marked depricated btw**
use Lcobucci\JWT\Signer\Ecdsa\Sha256;

...

$this->signer = new Sha256();
$this->keychain = new Keychain();
$token = (new Builder())->setIssuer('XXXXX')
                                ->setIssuedAt(time())
                                ->sign($this->signer, $this->keychain->getPrivateKey($apnsFile))
                                ->getToken();
```

error

```
Catchable fatal error: Argument 1 passed to Lcobucci\JWT\Signer\Ecdsa\KeyParser::__construct() must be an instance of Mdanter\Ecc\Math\MathAdapterInterface, instance of Mdanter\Ecc\Math\GmpMath given, called in C:\***\vendor\lcobucci\jwt\src\Signer\Ecdsa.php on line X and defined in C:\***\vendor\lcobucci\jwt\src\Signer\Ecdsa\KeyParser.php on line 46
```

**Comment by Gerben-T** [comment]
Ah i was using a newer version of the mdanter/ecc package (0.4.x)
I downgraded to the one that is listed in the composer.json of your package (0.3.1) and the fatal error is now gone.

**Comment by lcobucci** [comment]
#288 just backported PHP 7.1-7.3 support, can you please change your requirements to `3.3.x-dev` and check if things are working fine for you? **Important:** this is still a development version and shouldn't be used in production yet.

**Comment by lcobucci** [comment]
Preparing the release of v3.3.0 now, so this can be closed.
