### ISSUE TITLE
[Proposal] `Encoder` should be interface

### ISSUE THREAD

**Issue by yaquawa** [lcobucci/jwt#262]
Currently encoder is [concrete class](https://github.com/lcobucci/jwt/blob/3.3/src/Parsing/Encoder.php) which make [this line](https://github.com/lcobucci/jwt/blob/3.3/src/Builder.php#L68) nonsense.

Because user can only pass a instance of `Lcobucci\JWT\Parsing\Encoder`, but `Lcobucci\JWT\Parsing\Encoder` has no constructor which means the only option is passing a instance of `new Lcobucci\JWT\Parsing\Encoder`, so actually the `$encoder` can be eliminated because the `$encoder` always have to be the result of `new Lcobucci\JWT\Parsing\Encoder`.

The best solution is using interface instead of class, this way user can inject their own `Encoder` also. Actually I have problem with `jwt\src\Parsing\Encoder::jsonEncode` because of the data to be encoded contains binary data the `json_encode` will give an error, so I want to have my own implementation of `Encoder`, but currently I can't do that because `Encoder` is not an interface.

**Comment by lcobucci** [comment]
@yaquawa thanks for your input, this is indeed an important matter and it has already been addressed in v4 (which is currently in alpha). Now we depend on interfaces provided by [`lcobucci/jose-parsing`](https://github.com/lcobucci/jose-parsing/tree/master/src) and you can provide whatever implementation you need.

I'll analyse things to see if we'd have any BC-break to backport it to v3.x.

**Comment by lcobucci** [comment]
In the meantime you can try to use v4, which is thoroughly tested but will still have some interface changes.

**Comment by yaquawa** [comment]
@lcobucci Cool!! Thanks!👍🏼

**Comment by lcobucci** [comment]
Will be resolved by #518
