### ISSUE TITLE
Can't set expiration to more than 1h

### ISSUE THREAD

**Issue by SandroBCIT** [lcobucci/jwt#266]
I set the expiration time to 8 hours like this
`->setExpiration(time() + 28800)`
but it seems that from what I was able to test, the token is returned as invalid after 1 hour... 

Any ideas why that might be??

**Comment by lcobucci** [comment]
Can you please post a sample token (full string) and the snippet you're using to validate it?

**Comment by SandroBCIT** [comment]
@lcobucci 
```
public function get_token() {
    $signer = new Sha256();
    $token = (new Builder())->setHeader("alg","HS256") // header
                            ->setHeader("typ","JWT") // header
                            ->setIssuedAt(time()) // payload
                            ->setNotBefore(time()) // payload
                            ->setExpiration(time() + 28800) // payload (3600s = 1h) (28800s = 8h)
                            ->sign($signer, $this->signature) // signature
                            ->getToken(); // creates token string
    
    $token->getHeaders(); // Retrieves the token headers
    $token->getClaims(); // Retrieves the token claims

    return $token; // The string representation of the object is a JWT string

  }
```
this is the function I use to generate the token. It works for 5, 15, 30 min, and 1 hour, but not more.

**Comment by lcobucci** [comment]
That's not exactly what I've asked, I'd like to have a sample token generated by your code and the snippet which you use to validate tokens (what tells you that the token is not valid even though you've used the correct amount of seconds to issue it) ...

**Comment by SandroBCIT** [comment]
Oh my bad. Here is the token that got returned just now.
`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MzY3ODkyMDgsIm5iZiI6MTUzNjc4OTIwOCwiZXhwIjoxNTM2ODE4MDA4fQ.5ov-utAj2NhFOilgNSlaGShn2SY7glHX1BW5kwaMRrM`

**Comment by lcobucci** [comment]
@SandroBCIT no worries :+1: 

And how are you validating this token? I've just wrote this script and it looks like things are working as expected:

```php
use Lcobucci\JWT\Parser;
use Lcobucci\JWT\ValidationData;

$token = (new Parser())->parse('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MzY3ODkyMDgsIm5iZiI6MTUzNjc4OTIwOCwiZXhwIjoxNTM2ODE4MDA4fQ.5ov-utAj2NhFOilgNSlaGShn2SY7glHX1BW5kwaMRrM');
$data  = new ValidationData();

for ($i = 28797; $i < 28803; ++$i) {
    $data->setCurrentTime($token->getClaim('iat') + $i); // to simulate the current system time
    var_dump($i, $token->validate($data));
    echo PHP_EOL;
}
``` 

Output:

```sh
int(28797)
bool(true)

int(28798)
bool(true)

int(28799)
bool(true)

int(28800)
bool(true)

int(28801)
bool(false)

int(28802)
bool(false)

int(28803)
bool(false)
```

As you can see the validation works as expected, returning `true` when `time()` is less or equals than `1536818008` and `false` when it's greater than `1536818008`.

With that said, it really looks like there might be something wrong with how your validation is being handled.

**Comment by lcobucci** [comment]
@SandroBCIT closing this as `invalid` due to the fact that everything seems to work. Please open it if you feel the need :+1:
