### ISSUE TITLE
For validation rules, 'not equal' maybe add.

### ISSUE THREAD

**Issue by zxj2018** [lcobucci/jwt#268]
like claim 'jti',use 'not equal' or 'not in' more.

**Comment by lcobucci** [comment]
As explained in https://lcobucci-jwt.readthedocs.io/en/latest/extending-the-library/#validation-constraints we're allowing people to create their own validation constraints and only supporting the basic set of constraints in the library.

We'll be soon backporting the new validation system to `v3.4.0`.
