### ISSUE TITLE
This token is not signed.

### ISSUE THREAD

**Issue by mahmutakyol** [lcobucci/jwt#273]
Hi, I am developing rest full api with JWT and I gave that error. 
My codes like 

```php
public function encode(array $data): string
    {
        $token = $this->builder->setIssuer($this->config['issuer'])
            ->setAudience($this->config['audience'])
            ->setId($this->config['id'], true)
            ->setIssuedAt(time())
            ->setNotBefore(time())
            ->setExpiration(time() + 3600);
        foreach ($data as $key => $value) {
            $token->set($key, $value);
        }
        return $token->getToken()->__toString();
    }
```

```php
public function decode(): array
    {
        try {
            $token = $this->parser->parse((string)$this->token[0]);
            $this->validator->setIssuer($this->config['issuer']);
            $this->validator->setAudience($this->config['audience']);
            $this->validator->setId($this->config['id']);
            if (!$token->validate($this->validator)) {
                throw new JWTException('Invalid Token', 'Error validating the token');
            }
            if (!$token->verify($this->sha256, $this->config['sign'])) {
                throw new JWTException('Invalid Token', 'The token is empty or not encrypted correctly');
            }

            return $token->getClaims();
        } catch (InvalidArgumentException $e) {
            throw new JWTException('Invalid Token', $e->getMessage(), $e->getCode());
        } catch (BadMethodCallException $e) {
            throw new JWTException('Parsing Error', $e->getMessage(), $e->getCode());
        } catch (RuntimeException $e) {
            throw new JWTException('Parsing Error', $e->getMessage(), $e->getCode());
        }
    }
```

Example token  string when I send with Authorization; 

Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIiwianRpIjoiNGYxZzIzYTEyYWEifQ.eyJpc3MiOiJodHRwOlwvXC9zdHlidWwuY29tIiwiYXVkIjoiaHR0cDpcL1wvc3R5YnVsLmNvbSIsImp0aSI6IjRmMWcyM2ExMmFhIiwiaWF0IjoxNTQxNjgwMDM3LCJuYmYiOjE1NDE2ODAwMzcsImV4cCI6MTU0MTY4MzYzNywiaWQiOjM5LCJjb3VudHJ5X2lkIjoiMCIsImNpdHlfaWQiOiIwIiwiZGlzdHJpY3RfaWQiOiIwIiwibmFtZSI6Im1haG11dCIsInN1cm5hbWUiOiJha3lvbCIsImVtYWlsIjoibWFobXV0LmFreW9sQG91dGxvb2suY29tIiwicGhvbmUiOiIwNTUzMzY0MDQ3NCIsInByb2ZpbGVfcGljdHVyZV91cmwiOiIiLCJzdGF0dXMiOiIwIiwib3JkZXJpbmciOiIwIiwidXBkYXRlZF9hdCI6IjIwMTgtMTEtMDcgMDk6MjU6MjEiLCJjcmVhdGVkX2F0IjoiMjAxOC0xMS0wNyAwOToyNToyMSJ9.

Php Version. 7.1

**Comment by lcobucci** [comment]
@mahmutakyol you're receiving that error because you're indeed not signing the token while issuing it. Please take a look at https://github.com/lcobucci/jwt/blob/3.2/README.md#token-signature :+1:

**Comment by mahmutakyol** [comment]
Thank you so much fast solution 🥇 I used the signature method in the wrong place, should be used just before getToken()
