### ISSUE TITLE
Must be an instance of Lcobucci\JWT\Signer, instance of Lcobucci\JWT\Signer\Key given

### ISSUE THREAD

**Issue by eddiejibson** [lcobucci/jwt#279]
Hello,
I'm attempting to sign a token with an RSA key that has 4096 bits. I've done it like this:
`->sign($keychain->getPrivateKey('file://path/to/my/key.key'))`
However, when I run it, I'm getting this error:
`Argument 1 passed to Lcobucci\JWT\Builder::sign() must be an instance of Lcobucci\JWT\Signer, instance of Lcobucci\JWT\Signer\Key given`
I'm using version 3.2.
Any ideas?
Thanks.

**Comment by eddiejibson** [comment]
It works when I sign it with `Lcobucci\JWT\Signer\Rsa\Sha512`
However, I'm unsure why that's needed when I could just sign it with the RSA key alone?

**Comment by Ocramius** [comment]
The signer is what is used to do the actual signature, and it needs the key.

**Comment by Ocramius** [comment]
Closing as `invalid`. The signer is indeed what is using the key to perform the signing operation.

**Comment by eddiejibson** [comment]
So I do need to use `Lcobucci\JWT\Signer\Rsa\Sha512` every time I sign?

**Comment by Ocramius** [comment]
Or any other RSA signer.
