### ISSUE TITLE
There is no support for PHP 7.3

### ISSUE THREAD

**Issue by aksafan** [lcobucci/jwt#282]
There is [mdanter/ecc](https://github.com/phpecc/phpecc) in dependencies of an old version, that required php 7.2 max.
So when i'm trying to add lcobucci/jwt library to my project, i receive and error:
`- mdanter/ecc v0.4.5 requires php >=5.6.0, <7.2 -> your PHP version (7.3.0) does not satisfy that requirement.`

The fully php 7.* support for this library was arrived in release [PHPECC v0.5.0](https://github.com/phpecc/phpecc/releases/tag/v0.5.0).

It will be very good, if you upgrade mdanter/ecc in your library.

**Comment by lcobucci** [comment]
@aksafan thanks, we're aware and working on it to removing that dependency quite soon. A security review is pending on the ecdsa pr we have open, and then it will be back ported to v3.3.

Sorry about that delay but I really don't want to have potential security issues.

**Comment by lcobucci** [comment]
@GrahamCampbell I've just merged in @Spomky's PR (which is quite interesting in many ways) and am back porting things to v3.3. It would be awesome to have help with the documentation (not sure if the open issues on that are helpful enough).

**Comment by lcobucci** [comment]
#288 just backported PHP 7.1-7.3 support, can you please change your requirements to `3.3.x-dev` and check if things are working fine for you? **Important:** this is still a development version and shouldn't be used in production yet.

**Comment by lcobucci** [comment]
Preparing the release of v3.3.0 now, so this can be closed.
