### ISSUE TITLE
Question about verify method

### ISSUE THREAD

**Issue by TihomirS** [lcobucci/jwt#289]
Hi, 
First, thanks for the great work.

Just short question:
If I modify string for the token with some characters on validation I receive - wrong token - this is fantastik.
But if modify it with one more dot (.)  I get -  PHP Fatal error:  Uncaught InvalidArgumentException: The JWT string must have two dots .. and I get error 500 

How to deal with this?

**Comment by andreasschroth** [comment]
You can catch the exception and then e.g. respond with a more specific API error as response.

**Comment by TihomirS** [comment]
yes, I know this...
but still thinking that checking dots must be first validation rule and not in my side :)

**Comment by Ocramius** [comment]
There are two types of validation in most web apps:

 * Frontend validation, optional - makes things nice for end users, stops incoming requests from hitting the domain layer
 * Domain validation, required - crashes hard if something doesn't match expectations, prevents invalid state from flowing into the system

This library implements the second, in the domain/context of JWT.

It is up to you to make it nice for your frontend by adding frontend validation, if that's a business requirement.
