### ISSUE TITLE
Private/public claims validation

### ISSUE THREAD

**Issue by lcobucci** [lcobucci/jwt#29]
The issue #28 remind me of that we actually don't have any way to validate private/public claims.

Of course this is an edge case because most of people will just "store things" in the token and are not expecting to validate a non-registered claim, but anyway this should probably be helpful for someone.

**Comment by robksawyer** [comment]
Is it possible to use something like the following in validation? 

I'm still trying to wrap my head around the signing part of the token. (See my comment below.)
```
$data = new ValidationData();
$data->setIssuer($serverName);
$data->setAudience($serverName);
$data->setId($uid);
$data->setSigner(strval($my_secret_signer)); // <------- Is signer actually secret?
```

**Comment by emilva** [comment]
+1 private/public claims validation would be very neat

**Comment by jom** [comment]
+1 I'd especially like to be able to override just `exp` for adding a grace period when refreshing a [potentially a bit expired] JWT.
