### ISSUE TITLE
Why does the parser cast the `aud` claim to an array when the builder only accepts a string?

### ISSUE THREAD

**Issue by samjudge** [lcobucci/jwt#291]
I was looking at the code for Tokens/Parser and Tokens/Builder and noticed that the parser casts the aud claim to an array

```
if (isset($claims[RegisteredClaims::AUDIENCE])) {
    $claims[RegisteredClaims::AUDIENCE] = (array) $claims[RegisteredClaims::AUDIENCE];
}
```

but the builder only accepts a string...

```
public function permittedFor(string $audience): BuilderInterface
```

Surely this mismatch in types is a mistake?

**Comment by samjudge** [comment]
Nevermind, I see I'm supposed to iterate over and add them one by one now...

**Comment by lcobucci** [comment]
@samjudge thanks for your input here, this is part of an **unstable** and still under revision API (hence the lack of documentation).

Do you think it would be better for you if that method was variadic? Like:

```php
public function permittedFor(string ...$audiences): BuilderInterface
```

I haven't considered that before but if it makes your life easier it would be extremely easy to modify things :smile:

**Comment by samjudge** [comment]
@lcobucci Hi, thanks for getting back so fast, I love this project and have used the stable releases for a long time :) but for reasons beyond my control the team I've began working with has adopted the unstable v4 stuff... (So I'll probably be popping by a few times - sorry!)

Regardless, I think that would be a good change, since the signature would make what was going on clearer, and let me remove a couple lines in my own code :)

**Comment by lcobucci** [comment]
> I love this project and have used the stable releases for a long time :) but for reasons beyond my control the team I've began working with has adopted the unstable v4 stuff... (I think they just like making more work for me. So I'll probably be popping by a few times - sorry!)

@samjudge I'm really glad to hear you love it and use it for a long time :heart:
v4 is the imperfect result of a perfectionist's mind, which means that I'm always reviewing its API :joy: However I'm starting to be happy about it - after 3 years of it's first commit - and am working on designing a migration process for v3 users (on v3.3 or even v3.4).

I'd really appreciate any feedback, so don't hesitate to submit issues with questions or suggestions.

> Regardless, I think that would be a good change, since the signature would make what was going on clearer, and let me remove a couple lines in my own code :)

Implemented, I'll release a new alpha in a sec :tada:

Thanks, again, for you input :+1:

**Comment by lcobucci** [comment]
Done: https://github.com/lcobucci/jwt/releases/tag/4.0.0-alpha3
