### ISSUE TITLE
Verify ES256 with public key

### ISSUE THREAD

**Issue by Petah** [lcobucci/jwt#294]
Hi, how would I verify a JWT token with a ES256 public key?

**Comment by lcobucci** [comment]
@Petah in order to use ECDSA you should follow: https://github.com/lcobucci/jwt/blob/3.3/README.md#rsa-and-ecdsa importing `Lcobucci\JWT\Signer\Ecdsa\Sha256` instead of `Lcobucci\JWT\Signer\Rsa\Sha256`.

**Comment by Petah** [comment]
Thanks, and sorry I should have read it properly.
