### ISSUE TITLE
ECDSA signing/verification does not work

### ISSUE THREAD

**Issue by jurriaan** [lcobucci/jwt#30]
I was testing if your ECDSA JWT validation works correctly, but couldn't get it to work.

This is the example I used:

```php
use Lcobucci\JWT\Builder;
use Lcobucci\JWT\Signer\Keychain; // just to make our life simpler
use Lcobucci\JWT\Signer\Ecdsa\Sha512; // you can use Lcobucci\JWT\Signer\Ecdsa\Sha256 if you're using ECDSA keys
use Lcobucci\JWT\Parser;

$keychain = new Keychain();
$token = 'eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJoZWxsbyI6IndvcmxkIn0.AQx1MqdTni6KuzfOoedg2-7NUiwe-b88SWbdmviz40GTwrM0Mybp1i1tVtmTSQ91oEXGXBdtwsN6yalzP9J-sp2YATX_Tv4h-BednbdSvYxZsYnUoZ--ZUdL10t7g8Yt3y9hdY_diOjIptcha6ajX8yzkDGYG42iSe3f5LywSuD6FO5c';
$token = (new Parser())->parse((string) $token); // Parses from a string
$signer = new Sha512();

var_dump($token->verify($signer, $keychain->getPublicKey("-----BEGIN PUBLIC KEY-----\nMIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQAcpkss6wI7PPlxj3t7A1RqMH3nvL4\nL5Tzxze/XeeYZnHqxiX+gle70DlGRMqqOq+PJ6RYX7vK0PJFdiAIXlyPQq0B3KaU\ne86IvFeQSFrJdCc0K8NfiH2G1loIk3fiR+YLqlXk6FAeKtpXJKxR1pCQCAM+vBCs\nmZudf1zCUZ8/4eodlHU=\n-----END PUBLIC KEY-----")));
```
returns false.

Maybe I'm doing something wrong, but I quickly looked over the code and it looks like the ECDSA signing is not implemented according to the JWT RFC. See https://tools.ietf.org/html/rfc7515#appendix-A.3.1.

Also see this issue: https://github.com/jwt/ruby-jwt/issues/84.

**Comment by lcobucci** [comment]
Hello @jurriaan, thanks for your report.
I'll look it right now.

**Comment by lcobucci** [comment]
@jurriaan you're right and I'm fixing it right now.
Thanks again for your contribution!

**Comment by jurriaan** [comment]
@lcobucci You could test your signing and verification implementations (for all algorithms) against the [RFC 7520](https://tools.ietf.org/html/rfc7520) examples to make sure you've implemented RFC 7519 correctly.

Testing your verification implementation against your signing implementation doesn't work.

**Comment by lcobucci** [comment]
That's very strange @jurriaan, but tomorrow I'll arrive from a small trip and will dig into it. 

The HMAC and RSA algorithms are working and compatible with the jwt.io debugger and a python library that I've tested with. 

With ECDSA I'm basically relying on OpenSSL and it's having issues to verify using the public key that you've sent, I'll try to use a pure PHP implementation and see what happens. 

I'm definitely not an expert in cryptography but as far as I read OpenSSL does the same thing as described in RFC. But anyway, I'll add A LOT of functional tests to try to cover all possibilities and don't have compatibility issues. 

Thanks again!

**Comment by lcobucci** [comment]
With a little help of @ericktedeschi I was able to find the reason why it's not working. It seems that OpenSSL doesn't support nist curves. I'm rewriting ECDSA signers to fix that.

Thanks everyone :smile:

**Comment by lcobucci** [comment]
@jurriaan I think everything is fixed now, I just had to rewrite everything hehehe.
Grab some :beers: there, man! Thanks again.

I had to do some workarounds to keep the BC, but I'm planning a new major version right now :smile:.

**Comment by jurriaan** [comment]
Awesome!
