### ISSUE TITLE
Roadmaps for 4.0.0 and 5.0.0

### ISSUE THREAD

**Issue by bradynpoulsen** [lcobucci/jwt#300]
I'd be interested in helping to stabilize the v4 code APIs. Do you have a roadmap on what is still needing to be completed?

**Comment by jansor** [comment]
Hi, just curious, is their any timeline when this would be released?

**Comment by mtyeh411** [comment]
on a similar note, how would we grade the stability of current latest (4.0-alpha)? should it not be considered production-ready?  if so, what is work is outstanding to reach stable/production-ready?

**Comment by lcobucci** [comment]
Hey folks, sorry for the delayed response (I was on family vacations :smile:).

The plan for v4.0 is essentially this:

* Finish the work started in https://github.com/lcobucci/jwt/pull/339#issuecomment-561078369 (which would allow us to do #32 without breaking BC)
* Implement #128 
* Require PHP 7.4
* Backport changes to v3.x in a BC-compatible manner to create a migration path

The first 2 items are the ones which would modify the API, apart from that everything is pretty much stable. Although I do use the alpha version in production, I'd suggest you wait until those items are done to avoid having to modify things on your apps (or you use it knowing that things will change).

I don't have a timeline (sorry) but my hope is to tackle these things in the upcoming months (after I release a new version of @chimeraphp packages).

**Comment by GrahamCampbell** [comment]
> Require PHP 7.4

Which features are you looking to use from PHP 7.4?

**Comment by Ocramius** [comment]
Just bumping the min version to current stable is sufficient 👍

Besides that, typed properties, obviously

**Comment by zhangchenglin** [comment]
Are you planning to change from the BSD 3 license to the MIT license after version 4?
@lcobucci

**Comment by lcobucci** [comment]
@zhangchenglin we can surely change, AFAIK BSD-3 is as permissive as MIT so I didn't bother to change back then. However, I'm not an expert in that area and if that's an issue for you I can definitely modify it.

**Comment by zhangchenglin** [comment]
> @zhangchenglin we can surely change, AFAIK BSD-3 is as permissive as MIT so I didn't bother to change back then. However, I'm not an expert in that area and if that's an issue for you I can definitely modify it.

I do n’t know much about this either. I just see that many projects are using the MIT license, so I feel that if they are the same, then maybe you can introduce more about the idea of ​​using this license in the readme. Someone can give you the answer you want. I think that the current license has no effect on me.

**Comment by Ocramius** [comment]
BSD/MIT are pretty much the same: changing license is much more effort
(need to hunt down all previous contributors and ask for their opinion)

**Comment by GrahamCampbell** [comment]
RE PHP version stats from composer, only 1 in 5 people are using PHP 7.4. PHP 7.2 is still the most popular version...

**Comment by zhangchenglin** [comment]
> BSD/MIT are pretty much the same: changing license is much more effort (need to hunt down all previous contributors and ask for their opinion)

I don't understand this, so it's so troublesome?

**Comment by Ocramius** [comment]
Yes, **changing** license is a lot of work

**Comment by GrahamCampbell** [comment]
> Besides that, typed properties, obviously

It all your properties are private, typing them in the language is only gonna give you a slowdown at runtime, compared to using a static analyzer and phpdoc?

**Comment by Ocramius** [comment]
It will add runtime invariants, should any initialisation escape our analysis.

In general, the overhead is negligible, compared to the advantages: if you are worried about this kind of overhead, you can write a plugin to drop all typed properties post installation.

**Comment by Ocramius** [comment]
Besides, adding types explicitly can aid compilers and reflectors 👍

**Comment by GrahamCampbell** [comment]
> you can write a plugin to drop all typed properties post installation.

That would be a bad idea, if someone is reflecting on the code. ;)

**Comment by Potherca** [comment]
I'm getting the feeling that the PHP7.4 yay/nay discussion might be better served elsewhere....

Regardless, I'd be **very** interested in having JWK support, to the point of adding it myself _but_ for PHP 7.2 and higher, as that is indeed the constraint for the libs I am currently integrating with...

**Comment by bradjones1** [comment]
Per the PHP 7 question I agree with @Potherca this is a bit off-topic here and _also_, [this ship has sailed months ago](https://github.com/lcobucci/jwt/commit/d08362dd2ea3a014d8a3d905b61eed3c50f6247e). The README was [updated](https://github.com/lcobucci/jwt/commit/1fbc47871ce9e7ca237fac80c49eca79cacc8b49) last week.

I am a co-maintainer of the Simple OAuth/OpenID Connect module for Drupal and have an interest in #32, per above (so will also take a look at #339, which is indicated as a blocker.)

**Comment by chris-doehring** [comment]
I would really appreciate the release of a stable version `4.x` before the php 8 GA next month. As you may know, this package is an important dependency to others, and it would block them to upgrade to php 8.

@lcobucci If you like, I could create a PR where I make version `3.4` compatible to php 8, but that could mean dropping support for php `5.*` (due to phpunit). Depending on your priorities, this would give you some more time to prepare version 4.

**Comment by lcobucci** [comment]
@chris-doehring my plan is to release v4 before php 8.0 GA - or at least really close to it.

I want for v3.x to only serve as migration path for the new API, the only tricky thing is to backport BC-breaking changes.

**Comment by driesvints** [comment]
@lcobucci is there anything I can do to help out? Currently this is blocking PHP 8 support on league/oauth2-server and laravel/passport. Let me know what can be done to speed this up :)

**Comment by driesvints** [comment]
See https://github.com/thephpleague/oauth2-server/pull/1146 & https://github.com/laravel/passport/pull/1373

**Comment by driesvints** [comment]
@lcobucci so If I go by https://github.com/lcobucci/jwt/issues/300#issuecomment-591507948 it seems https://github.com/lcobucci/jwt/pull/452, https://github.com/lcobucci/jwt/pull/339 & " Backport changes to v3.x in a BC-compatible manner to create a migration path" are the only three things left for v4? #339 is a bit out of date it seems but do you have any more feedback for those PRs? Not sure what you mean with the backport of changes to v3?

**Comment by lcobucci** [comment]
Okay, folks, I took some time to organise stuff - about time, right? (sorry).

So I have some dates which I'm aiming for [v4.0.0-beta1](https://github.com/lcobucci/jwt/milestone/16) and v3.4.0 (assigned on the milestones) and added issues to backport stuff.

v4.0.0-beta1 issues: https://github.com/lcobucci/jwt/milestones/4.0.0-beta1
v3.4.0 issues: https://github.com/lcobucci/jwt/milestones/3.4.0

With that said, I'll be closing this issue and invest some time reaching those expected dates.
I hope this gives the necessary information.

Any help on getting stuff done is really appreciated!

**Comment by driesvints** [comment]
That's great @lcobucci! I'll check those out soon to see if I can help out there 👍
