### ISSUE TITLE
Dependencies PHP 5.6+ but requires PHP 7.2?

### ISSUE THREAD

**Issue by skyvondave** [lcobucci/jwt#303]
The readme says Dependencies PHP 5.6+ (v3.3) and PHP 7.1 (v4.x) but the composer.json file says "require" "php": "^7.2",

So which is it?

We're using PHP 5.6; not sure what I need to change anywhere in this repo to make it work with it.

**Comment by lcobucci** [comment]
@skyvondave the version v3.3 (stable) requires PHP 5.6+. The v4.x (dev) was requiring PHP 7.1 but has been bumped up and I forgot to update the readme.

Check https://github.com/lcobucci/jwt/blob/3.3/README.md for the documentation of the stable version.

**Comment by lcobucci** [comment]
Thanks for letting me know about the outdated README on `master`, just fixed it :+1:

**Comment by lcobucci** [comment]
By the way, if you run `composer require lcobucci/jwt` composer will detect the most appropriated version, according to your system.

**Comment by skyvondave** [comment]
Thanks. I tried clicking the "Stable" link to 3.3 and that says 5.6+ only, which is what I'm trying now.
