### ISSUE TITLE
composer require lcobucci/jwt from 3.3 installs 3.2.5 with different Builder methods?

### ISSUE THREAD

**Issue by skyvondave** [lcobucci/jwt#304]
I ran it from the instructions here: https://github.com/lcobucci/jwt/blob/3.3/README.md

When I copy over your "Creating" example code to see how it works, PHPStorm says most of the functions from Builder don't exist, and they're not actually in the Builder.php file.

When I check composer.lock (this is after update and install), it says "version": "3.2.5",
            "source": {
                "type": "git",
                "url": "https://github.com/lcobucci/jwt.git",

So I'm not sure what's going on.

**Comment by Ocramius** [comment]
Try with an explicit `compose require lcobucci/jwt:^3.3.1`

**Comment by lcobucci** [comment]
@skyvondave is it possible that you are running composer with php 5.5 (or earlier) - either in your system or via the platform configuration in your composer.json? If that's the case, you will get a previous version of this library (as v3.3 requires php 5.6+).

**Comment by lcobucci** [comment]
v3.2.5 works fine btw, you just won't have new features - only security issues will be backported. The documentation is available in the 3.2 branch.

**Comment by skyvondave** [comment]
OK 3.2 has matching method names...

I guess I'm curious why the method names were changed on a minor version number change; wouldn't that be an "API-breaking" major change?

**Comment by lcobucci** [comment]
@skyvondave the v3.2 API works fine on v3.3, we've only added new methods and deprecated the old ones.

That is being done to create an upgrade path for the new major release (v4.0), the documentation just had to reflect that :smile:

**Comment by skyvondave** [comment]
OK I see thank you

**Comment by lcobucci** [comment]
Closing this then! Feel free to comment/reopen it if you want to explore more on why v3.2 is being installed in your system instead of v3.3.
