### ISSUE TITLE
invalid UTF8 characters

### ISSUE THREAD

**Issue by xcodevsci** [lcobucci/jwt#305]
I m using the library in my projet. Last time all run fine but since yesterday when i run my API, i got dat error:
{
  "code": 500,
  "message": "Your data could not be encoded because it contains invalid UTF8 characters."
}

... and when i dump the returv value, dat is the trace :
 
object(Lcobucci\JWT\Token)#451(4){
  [
    "headers": "Lcobucci\JWT\Token": private
  ]=>array(2){
    [
      "typ"
    ]=>string(3)"JWT"[
      "alg"
    ]=>string(5)"HS256"
  }[
    "claims": "Lcobucci\JWT\Token": private
  ]=>array(7){
    [
      "iss"
    ]=>object(Lcobucci\JWT\Claim\EqualsTo)#443(2){
      [
        "name": "Lcobucci\JWT\Claim\Basic": private
      ]=>string(3)"iss"[
        "value": "Lcobucci\JWT\Claim\Basic": private
      ]=>string(18)"http://iventaf.com"
    }[
      "aud"
    ]=>object(Lcobucci\JWT\Claim\EqualsTo)#444(2){
      [
        "name": "Lcobucci\JWT\Claim\Basic": private
      ]=>string(3)"aud"[
        "value": "Lcobucci\JWT\Claim\Basic": private
      ]=>string(18)"http://iventaf.com"
    }[
      "jti"
    ]=>object(Lcobucci\JWT\Claim\EqualsTo)#445(2){
      [
        "name": "Lcobucci\JWT\Claim\Basic": private
      ]=>string(3)"jti"[
        "value": "Lcobucci\JWT\Claim\Basic": private
      ]=>string(15)"ApPK5ycoNFUA4Z4"
    }[
      "iat"
    ]=>object(Lcobucci\JWT\Claim\LesserOrEqualsTo)#446(2){
      [
        "name": "Lcobucci\JWT\Claim\Basic": private
      ]=>string(3)"iat"[
        "value": "Lcobucci\JWT\Claim\Basic": private
      ]=>int(1564587146)
    }[
      "nbf"
    ]=>object(Lcobucci\JWT\Claim\LesserOrEqualsTo)#447(2){
      [
        "name": "Lcobucci\JWT\Claim\Basic": private
      ]=>string(3)"nbf"[
        "value": "Lcobucci\JWT\Claim\Basic": private
      ]=>int(1564587206)
    }[
      "exp"
    ]=>object(Lcobucci\JWT\Claim\GreaterOrEqualsTo)#448(2){
      [
        "name": "Lcobucci\JWT\Claim\Basic": private
      ]=>string(3)"exp"[
        "value": "Lcobucci\JWT\Claim\Basic": private
      ]=>int(1564590746)
    }[
      "t"
    ]=>object(Lcobucci\JWT\Claim\Basic)#449(2){
      [
        "name": "Lcobucci\JWT\Claim\Basic": private
      ]=>string(1)"t"[
        "value": "Lcobucci\JWT\Claim\Basic": private
      ]=>string(15)"aroun3@yahoo.fr"
    }
  }[
    "signature": "Lcobucci\JWT\Token": private
  ]=>object(Lcobucci\JWT\Signature)#450(1){
    [
      "hash": protected
    ]=>string(32)"�;��v�p�υftm
���]��>�!y|�"
  }[
    "payload": "Lcobucci\JWT\Token": private
  ]=>array(3){
    [
      0
    ]=>string(36)"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9"[
      1
    ]=>string(208)"eyJpc3MiOiJodHRwOlwvXC9pdmVudGFmLmNvbSIsImF1ZCI6Imh0dHA6XC9cL2l2ZW50YWYuY29tIiwianRpIjoiQXBQSzV5Y29ORlVBNFo0IiwiaWF0IjoxNTY0NTg3MTQ2LCJuYmYiOjE1NjQ1ODcyMDYsImV4cCI6MTU2NDU5MDc0NiwidCI6ImFyb3VuM0B5YWhvby5mciJ9"[
      2
    ]=>string(43)"ijujtHYT2gdwE87PhWZ0bQ2OjoRdp_M-G-8heRd86Y0"
  }
}

Please help

**Comment by lcobucci** [comment]
@xcodevsci hey, can you please provide more information? Perhaps the full stack trace of the exception to know what is causing the error. It seems like the token has been parsed properly but I don't know what you're trying to do :)

**Comment by lcobucci** [comment]
@xcodevsci closing here since no info was provided. Feel free to reopen if you're still having issues.
