### ISSUE TITLE
getPayload method do not return whole token

### ISSUE THREAD

**Issue by thiagoSLV** [lcobucci/jwt#307]
Hello, I'm currently using the 3.3 version and the method getPayload return the position 0 and 1 from the payload array.
But in my token's payload array I have 3 positions: 

```
["payload":"Lcobucci\JWT\Token":private]=>
  array(3) {
    [0]=>
    string(62) "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IjE1NjUyODExMzcifQ"
    [1]=>
    string(151) "eyJpc3MiOiIyZTAyZDk3YjdkY2MiLCJqdGkiOiIxNTY1MjgxMTM3IiwidXNlciI6eyJwcm9qZXRvIjoiY2RwciIsImlkIjoxLCJjZmMiOm51bGwsImVzdGFkbyI6InByIiwibWFzdGVyIjp0cnVlfX0"
    [2]=>
    string(43) "_wHGc2uaoC8UZftYN-p3lkQTVoDqeL3UHRYx1suOx5M"
  }
```

When I call the method getPayload that' the return:

```
string(214) "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IjE1NjUyODEzMDcifQ.eyJpc3MiOiIyZTAyZDk3YjdkY2MiLCJqdGkiOiIxNTY1MjgxMzA3IiwidXNlciI6eyJwcm9qZXRvIjoiY2RwciIsImlkIjoxLCJjZmMiOm51bGwsImVzdGFkbyI6InByIiwibWFzdGVyIjp0cnVlfX0"
```

Is it possible to alter this method on version 3.3 so it return the whole token?

Thanks :)

**Comment by Ocramius** [comment]
The payload is effectively the first two components: the third is a signature, so it shouldn't be considered part of the "payload". The fact that a `private` property (which doesn't really concern your usage of the API) contains also the signature is not really relevant.

**Comment by thiagoSLV** [comment]
Ok, thanks for the explanation, closing this issue.
