### ISSUE TITLE
Question: how to get the whole JWT string to send back over HTTP

### ISSUE THREAD

**Issue by tommasodargenio** [lcobucci/jwt#312]
Hi,

this could be a very stupid question but I'm struggling a bit to understand how can I get out of the object the whole JWT string that I need to send back to the HTTP post request from the client.

I've used the sample code as provided in your readme to create the token, but the getToken method doesn't give me the plain text but return the whole object. I can see the token string and the signature in the object payload but shouldn't the getToken method return the plain text version I can send back to the client?

Thanks

**Comment by Ocramius** [comment]
`$token->__toString()` or `(string) $token`:

https://github.com/lcobucci/jwt/blob/a11ec5f4b4d75d1fcd04e133dede4c317aac9e18/src/Token.php#L269-L283

**Comment by lcobucci** [comment]
@tommasodargenio the `Token` class has the `__toString()` method, which means that you get the string representation by casting it to string.
