### ISSUE TITLE
Custom Claims

### ISSUE THREAD

**Issue by gbozzetti** [lcobucci/jwt#332]
Hey guys, maybe I'm blind but I can't find a way to insert custom claims in the token.

I can use the default 'uid' but if I set a custom claim with the 'withClaim' function I cannot retrieve it with getClaim!

How to do that?

Thank you!

**Comment by Ocramius** [comment]
@gbozzetti can you make an example of the code, expectations and actual results, please?

**Comment by gbozzetti** [comment]
Sure!

I'm creating a new token with the builder:

`$token = (new Builder()) 
->issuedBy(...)
->permittedFor(...)
....
->withClaim("mycustomname","myvalue"
`
But then when I try to retrieve it with `$token->getClaim("mycustomname")` I get an error.

**Comment by Ocramius** [comment]
Can you expand the snippet then, please?

**Comment by gbozzetti** [comment]
Ooooooops, my fault! I was passing null values to claims!!!!

Sorry, you can burn this issue request!!!
