### ISSUE TITLE
Composer install snippet in the docs has the wrong version?

### ISSUE THREAD

**Issue by nyalex** [lcobucci/jwt#333]
Ref: https://lcobucci-jwt.readthedocs.io/en/latest/installation/

This document instructs us to run the following command.

`composer require lcobucci/jwt:^4.0@alpha`

If I am reading this correctly, this would import alpha versions of the library. If so,t his is dangerous and should not be recommended. I believe it should be:

`composer require lcobucci/jwt:^3.3-stable`

**Comment by andreasschroth** [comment]
Hm, I guess you didn't read the project README file?

Quote:

> Basic usage
> The documentation of the unstable version is available at https://lcobucci-jwt.readthedocs.io/en/latest/.
> 
> The documentation of the stable version is on branch 3.3.

**Comment by nyalex** [comment]
I see that now. I got to those docs before hitting Github. I got confused because I didn't see any mention that it is alpha on those docs. Seems like you do not see the problem, so I will close this issue.

**Comment by lcobucci** [comment]
@nyalex I'm sorry for the confusion in the docs. We're backporting things to v3.4, docs included and we'll soon have the stable version in the website too.
