### ISSUE TITLE
How can I add custom claims to payload?

### ISSUE THREAD

**Issue by rezarabbbani** [lcobucci/jwt#335]
Hi. I need to to add more claims to token payload like user's name and email but I have no idea how can i do it. I've been searching for a long time but it didn't help much.

**Comment by lcobucci** [comment]
@rezarabbbani the token builder has the method `withClaim()`. You can see an example in the docs: https://github.com/lcobucci/jwt/blob/3.3/README.md#creating

**Comment by lcobucci** [comment]
I hope this helps you. I will close this issue but feel free to reopen if you would like more information about this.

**Comment by nargalzius** [comment]
Sorry for opening this again, but seems related

Using the custom claim method in the docs seems to skip over the sub altogether (which is integral) when generating the custom token.

Then setting it via `withClaim()` throws an error `Builder#withClaim() is meant to be used for non-registered claims, check the documentation on how to set claim "sub"` - but I can't find how to set the sub in the documentation anywhere.

**Comment by lcobucci** [comment]
@nargalzius thanks for raising this... I haven't noticed that we're missing the example on the docs.

Here's the method you should call:

https://github.com/lcobucci/jwt/blob/2f58ec307b4beac98578bdaf7bc9f89ca9cc6af9/src/Builder.php#L53-L58

I'll make sure https://lcobucci-jwt.readthedocs.io/en/stable/issuing-tokens/ has that info soon :+1:

**Comment by lcobucci** [comment]
https://github.com/lcobucci/jwt/commit/820ead6970a7e8fa46760226b12e74f2a397cd96 here you go :smile:
