### ISSUE TITLE
Builder convertDate causes timezone and date to be incorrect

### ISSUE THREAD

**Issue by legeng** [lcobucci/jwt#336]
version  "lcobucci/jwt": "^4.0@alpha"

```php
 private function convertDate(DateTimeImmutable $date)
    {
        $seconds      = $date->format('U');
        $microseconds = $date->format('u');

        if ((int) $microseconds === 0) {
            return (int) $seconds;
        }

        return $seconds . '.' . $microseconds;
    }
```
generate exp:
DateTimeImmutable Object
(
    [date] => 2019-11-21 18:14:59.908116
    [timezone_type] => 3
    [timezone] => Asia/Shanghai
)

If you follow this method，cause parse after  incorrect

```php
private function convertDate(string $value): DateTimeImmutable
    {
        if (strpos($value, '.') === false) {
            return new DateTimeImmutable('@' . $value);
        }

        $date = DateTimeImmutable::createFromFormat('U.u', $value);

        if ($date === false) {
            throw new InvalidArgumentException('Given value is not in the allowed format: ' . $value);
        }

        return $date;
    }
```

result exp:
DateTimeImmutable Object
(
    [date] => 2019-11-21 09:23:18.732245
    [timezone_type] => 1
    [timezone] => +00:00
)

if return $date->format('Y-m-d H:i:s'); result is right

**Comment by lcobucci** [comment]
@legeng the [section 2 of JWT RFC](https://tools.ietf.org/html/rfc7519#section-2) defines we must to use the `NumericDate` type:

> A JSON numeric value representing the number of seconds from 1970-01-01T00:00:00Z UTC until the specified UTC date/time, ignoring leap seconds.  This is equivalent to the IEEE Std 1003.1, 2013 Edition [POSIX.1] definition "Seconds Since the Epoch", in which each day is accounted for by exactly 86400 seconds, other than that non-integer values can be represented.  See RFC 3339 [RFC3339] for details regarding date/times in general and UTC in particular.

This explains the reason why this is being converted to UTC (unix timestamps are always in UTC). However, it doesn't explain why the time is changing when parsing, that should work fine: https://3v4l.org/HY2p1.

Could you please send us a sample token (doesn't need to be signed or anything) and the dates you used to issue it? That would help a lot on testing this.

**Comment by legeng** [comment]
@lcobucci  ok , Thank you for your reply and solved my doubts. I understand, it should be a problem with my use, it works, your package is great , thank you!

**Comment by lcobucci** [comment]
@legeng alright then, glad to hear it worked well. Do you think that having the timezone configured to your system defaults would help you? That would require a few changes here and there but I'm happy to do it if people would see the value in it.

In the meantime I'll close this issue 👍
