### ISSUE TITLE
jwt token by lcobucci != jwt token by jwt.io

### ISSUE THREAD

**Issue by Gemorroj** [lcobucci/jwt#341]
Why is there a difference in the JWT token generated by the library and jwt.io?

![Захват-1](https://user-images.githubusercontent.com/885731/70314325-4a263d80-1828-11ea-8df4-127481a9f806.jpg)
![Захват-2](https://user-images.githubusercontent.com/885731/70314326-4abed400-1828-11ea-92d8-ae0c28eb31f3.jpg)

**Comment by Ocramius** [comment]
What difference do you see? Same claims, from what I can see.

**Comment by Gemorroj** [comment]
1 block is identical
2 - lcobucci ending with `19fQ`, jwt.io ending with `XX19`
3 - lcobucci ending with `Jtc4`, jwt.io ending with `DzSE`

**Comment by Ocramius** [comment]
I'd check the difference in the base64-decoded fragments: potentially whitespace.

**Comment by lcobucci** [comment]
This is most likely to be differences on how the json string is created (escaping slashes or unicode).

That shouldn't cause any issue but are you experiencing any?

**Comment by Gemorroj** [comment]
@lcobucci, no problem, everything seems to be fine.
Yes, probably the difference is due to differences in JSON escaping.
