### ISSUE TITLE
Invalid signature when using google json service key

### ISSUE THREAD

**Issue by pelayo** [lcobucci/jwt#344]
Im trying to create a JWT token to manually authenticate calls to a cloud function in Google Cloud.
The token gets generated but Google returns 401 when using it and jwt.io says the signature is wrong.

Here's my code.

            $jsonData = json_decode(file_get_contents($serviceKeyDir)); 
            $signer = new Sha256();
            $privateKey = new Key($jsonData->private_key);

            $this->apiKey = (new Builder())
                ->issuedBy("https://accounts.google.com")
                ->withHeader("kid", $jsonData->private_key_id)
                ->withClaim("sub", $jsonData->client_id)
                ->withClaim("azp", $jsonData->client_email)
                ->withClaim("email", $jsonData->client_email)
                ->withClaim("aud", $jsonData->project_id)
                ->issuedAt($time)
                ->expiresAt($time+3600)
                ->getToken($signer, $privateKey);`

Any suggestion?

**Comment by Ocramius** [comment]
Unless you are the owner of `accounts.google.com`, I don't think you are the issuer there: whose `private_key` is that?

**Comment by pelayo** [comment]
The private key comes from a json service key associated to a gcloud service account.

The jwt genereted with the command "gcloud auth print-identity-token" works as a charm (also in jwt.io) and I tried to copy it's contents.

**Comment by Ocramius** [comment]
Yeah, but then the key is issued by a web service that has its own private key: unless you have that same private key, you won't be able to generate a payload that is accepted by the remote server (won't match a public key that they have)

**Comment by pelayo** [comment]
Okey. Does that explain the jwt.io "signature error" to?

I followed the jwt guides in https://developers.google.com/identity/protocols/OAuth2ServiceAccount
No exactly the same service, but thought it would do.

Guess ill have to rollout my own security ...

**Comment by Ocramius** [comment]
> Guess ill have to rollout my own security ...

These are some of the most dangerous words in our industry: do not do that, especially if you don't understand what's going on.

 > Does that explain the jwt.io "signature error" to?

Can you dump one of these tokens with dummy data, so that we can see what is going on?

**Comment by pelayo** [comment]
I know, famous last words. Don't worry, it would be just jwt with my own key pairs, nothing fancy/in-house. Also, thanks for the help.

Anyway, I still want to solve this. This is a minimun token, just the iat and exp field. Jwt.io still says "invalid signature".

> eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODA4MDQyMzMsImV4cCI6MTU4MDgwNzgzM30.V4R5efdwUg_7A7uTHc9DzixZHgagyQUKWiOdk-bDAzoBlZnX_tPoBMAouNUi0Jo2ZEkK6zbyipT-rqS451vSI6OPOWlRHHJhvRSHf-FaafDcQguNcoGiY-d1qVCfX3STuNZsPLQsDXdrInXjWtz_FuHexPylB023FQcmmEsIha89WMsSyyMvjOPvwz3R-Ik15j8K7y2o_mLgAgyoz5RgRjLoqXAsm0e024a88cCJLu3eEU6sWUDgj_ooiNTFGxPm-pLwm93XfsfxszdxOCZcUJECuXhj7mDM517NSexypMt9tCCRqriWOaXtLCUCk0zV7WTkavdrMu5naL0oKuZJHw

Tried with the key in its own file and not embedded in the json of the service key but it has the problem.

**Comment by lcobucci** [comment]
In your snippet we can't see which algorithm you're using, is it RSA?

Did you manage to verify the token signature using the public key with this lib after issuing it?

One thing that may be relevant is that jwt.io UI isn't the best in terms of usability (at least was in the last time I've used it). If I'm not mistaken, you've got to paste the public key **before** of pasting the token.

**Comment by lcobucci** [comment]
Closing here since we didn't get more input from @pelayo

**Comment by Aymkdn** [comment]
In the case of a Smart Home object, using Homegraph, the `issuer` is the `client_email` from the JSON file.

Also a **RSA256** must be used.

Some references:
- https://cloud.google.com/endpoints/docs/openapi/service-account-authentication 
- https://stackoverflow.com/questions/51471726/google-smart-home-report-state-error-403 
- https://github.com/actions-on-google/smart-home-nodejs/issues/149
- https://developers.google.com/identity/protocols/oauth2/service-account#httprest

I'm posting here in case it can help someone else. This is for the [Google Report State](https://developers.google.com/assistant/smarthome/develop/report-state) to get an access token using JWT:
```php
$jsonData = json_decode(file_get_contents('file-token-key.json'));  // this .json has been generated with https://developers.google.com/assistant/smarthome/develop/report-state#service-account-key
$signer = new Sha256();
$privateKey = new Key($jsonData->private_key);
$time = time();

echo (new Lcobucci\JWT\Builder())
    ->issuedBy("<client_email>")
    ->withClaim("scope", "https://www.googleapis.com/auth/homegraph")
    ->withClaim("aud", "https://oauth2.googleapis.com/token")
    ->issuedAt($time)
    ->expiresAt($time+3600)
    ->getToken($signer, $privateKey);
```

Then we can test it on https://jwt.io/ by passing the returned value in the "Encoded" field, and in the "Decoded" part, we must copy/paste the Private Key coming from the `file-token-key.json` (make sure to replace the `\n` string with an actual return) into the field `your-256-bit-secret` field, and the signature should appear as "verified".
