### ISSUE TITLE
[3.3] `Claim::getValue` can return an array

### ISSUE THREAD

**Issue by carusogabriel** [lcobucci/jwt#367]
Hi @lcobucci 👋 

I'd like to report to you something that we found at @usabilla while using this amazing library 😄 

The documentation for 

https://github.com/lcobucci/jwt/blob/56f10808089e38623345e28af2f2d5e4eb579455/src/Claim.php#L27-L32

is missing the possibility of an `array`. Example: https://jwt.io/#debugger-io?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJteUN1c3RvbUFycmF5Q2xhaW0iOlsidmFsdWUxIiwidmFsdWUyIl19.krhErcq8V7_W2K4dSlXtp63d8AY4LTwdU08b6DlR_rU

Can I open a PR adding it, or would it be a BC?

I found that with PHPStan, telling me that I can't use functions like `is_array` or `is_string` and they would be always `false` or `true`, respectively.

**Comment by lcobucci** [comment]
@carusogabriel nice catch, thanks!

This was clearly a mistake, as you can see on the implementation https://github.com/lcobucci/jwt/blob/3.3/src/Claim/Basic.php#L36

It's not a BC-break so, please, do send a patch for the 3.3.x series!
