### ISSUE TITLE
Requested claim \"kid\" is not configured

### ISSUE THREAD

**Issue by ArmChaCib** [lcobucci/jwt#372]
when i try to loggin with apple i received this message: "Requested claim \"kid\" is not configured".
But it is in the header 
{
  "kid": "*******f",
}

**Comment by JoeBengalen** [comment]
Try using the `getHeader` method instead of `getClaim`. The latter looks only at the payload of the token, not in the header part.

**Comment by lcobucci** [comment]
@JoeBengalen is 100% correct here. Claims are different from headers, that's why we provide different methods to fetch them.

I'll close this issue for now, feel free to comment further or reopen it.
