### ISSUE TITLE
Signer factory?

### ISSUE THREAD

**Issue by elazar** [lcobucci/jwt#45]
I'm filing this issue mostly to feel out interest in and/or likelihood of acceptance of a simple factory implementation for `Signer` implementations if I were to submit a PR for one.

There's a [factory for Claims](https://github.com/lcobucci/jwt/blob/master/src/Claim/Factory.php), so it seems like there's some precedent for this.

This `Signer` factory would essentially resolve short algorithm names, such as [those used by the Firebase JWT implementation](https://github.com/firebase/php-jwt/blob/4a94b91434bf02395b4c2714ae19562116a80a10/src/JWT.php#L32-L37), to `Signer` instances, and allow users to add their own custom `Signer` implementations.

**Comment by lcobucci** [comment]
Hello @elazar we used to have a [signer factory in v2.x](https://github.com/lcobucci/jwt/blob/2.1/src/Signer/Factory.php) but it became useless in my opinion when I started to work on the v3.

@ocramius gave me an interesting idea about the creation of a configuration object to simplify the usage of both Builder and Parser. I was thinking to discuss more about that and create it in v4 (that I'm already planning) but maybe we can find something for a v3.1.

I think that using this configuration object your integration would be easier.

@ocramius please share your thoughts!

**Comment by Ocramius** [comment]
I don't have enough insight on this, but it seems to me that factories are pretty much unnecessary in this lib.

Having the instances in a small configuration object is indeed simpler and more straightforward, whereas factories would be defined in framework-specific (or consumer-specific) implementations instead.

**Comment by lcobucci** [comment]
I think that we can discuss about simplifying things in #49 and this issue can be closed.
