### ISSUE TITLE
How to update or refresh token?

### ISSUE THREAD

**Issue by johndavedecano** [lcobucci/jwt#48]
I see alot of stackoverflow answers telling that you have to refresh the token every request so that it wont expire whenever there is an activity. Please let me know if this is okay. If yes, let me know how do it in your library/package thanks.

Dave

**Comment by Ocramius** [comment]
@johndavedecano you just create a new token at each request...

**Comment by lcobucci** [comment]
@johndavedecano the refresh thing depends on your use case, because JWT can be used in different contexts.

As @Ocramius said, if you just want to refresh it you just create a new token using the ```Builder``` with all claims you think you should use.

**Comment by johndavedecano** [comment]
Is it possible to just update its expiration? Thanks

**Comment by lcobucci** [comment]
Nope, the token is immutable.
