### ISSUE TITLE
Introduce configuration object

### ISSUE THREAD

**Issue by lcobucci** [lcobucci/jwt#49]
As mentioned on #45 and #47 we're thinking a way to simplify the things by introducing a configuration object.

**Comment by Ocramius** [comment]
@lcobucci I don't think this is better than the builder. (probably just provide the builder with better defaults and it's the same stuff).

It would be good to have the `Builder`, `Parser` and `Signer` to have in the config object. 

Token generation is already easy-peasy, but gluing everything together isn't really.

**Comment by Ocramius** [comment]
I think it would be good to survey the possible use-case scenarios first, in order to see what can be simplified. I personally think the builder is fine, and very simple to use :-)

**Comment by lcobucci** [comment]
Ok. I've edited to don't confuse anyone else.
