### ISSUE TITLE
Class Hmac not found in Sha256

### ISSUE THREAD

**Issue by rutwick** [lcobucci/jwt#50]
I get the following errors when I try to use the Sha256 interface:

Fatal error: Class 'Lcobucci\JWT\Signer\Hmac' not found in C:\wamp\www\examples\jwt-master\src\Signer\Hmac\Sha256.php on line 19

I include the following files:
include('jwt-master/src/Builder.php');
include('jwt-master/src/Signer/Hmac/Sha256.php');

Am I doing something wrong here? I'm fairly new to namespaces.

**Comment by Ocramius** [comment]
@rutwick you should run a composer installation, not manual includes :-)

**Comment by lcobucci** [comment]
Exactly @rutwick. As explained in [README.md](https://github.com/lcobucci/jwt#installation) you must use composer to install all project dependencies and have a PSR-4 autoloader (so you won't have to use manual includes).

I'll be closing this issue now ;-)
