### ISSUE TITLE
Move to PHP 7

### ISSUE THREAD

**Issue by lcobucci** [lcobucci/jwt#51]
Since we're planning to break the BC in v4 I believe that we can push this forward and have a better API.

**Comment by Ocramius** [comment]
:+1:

**Comment by udf2457** [comment]
PHP 7 is not release yet.
As per the PHP website:
 **"THIS IS A DEVELOPMENT PREVIEW - DO NOT USE IT IN PRODUCTION!"**

Therefore JWT should not be written in PHP7 yet !

**Comment by Ocramius** [comment]
It's going to be stable in 2 weeks, so that is not a problem. Not every new
software bit needs to be developed against stable software only.

**Comment by udf2457** [comment]
Ocramius,

Please.  Be sensible !

PHP7 might be "stable in 2 weeks" .... but how many people, honestly, are going to be bleeding-edge day zero adopters.

How many people have yet to even make the transition from PHP 5.5 to PHP 5.6 ?  And that's only a minor release.

I think it is far, far too early for you to say  "who cares about <7 users ...." ... maybe in 12/24 months.

**Comment by Ocramius** [comment]
They can still use the previous version of the lib: that's why major
versions exist ;-)

**Comment by udf2457** [comment]
Ocramius,

That's even more stupid.

So basically you let them use an abandoned old version.

Shame on you.

**Comment by Ocramius** [comment]
Who ever said old versions are abandoned?  That is not how it works, do not
worry. There is bug/security support for (some) older versions of pretty
much every lib.

See ZendFramework for example: v1.* is still maintained and patched for
bugs/security issues since 3 years after 2.* came out.

**Comment by lcobucci** [comment]
@udf2457 the v3.x is fully working and we have dozens of BC-break ideas, that's why we're going to make a v4.x (but the v3.x will be maintained).

With that we can have PHP 5.5+ folks using v3.x (and helping to make it even better - respecting the BC) and PHP 7+ folks using the v4.x new API.

The v4.x won't be released in less then 14 days.

We also have (until now) two features that can be implemented for a v3.1 (#29 and #49).
