### ISSUE TITLE
lcobucci/jwt updated version 3.4.0  issue

### ISSUE THREAD

**Issue by saifmuhammad** [lcobucci/jwt#553]
Today , we were releasing laravel project which uses following packages 
"laravel/framework": "5.7.*",
 "tymon/jwt-auth": "1.0.*",

After composer update , jwt authentication stoped working and gave below mentioned error 
**Replicating claims as headers is deprecated and will removed from v4.0. Please manually set the header if you need it replicated.**
There  must be some issue with package dependencies "lcobucci/jwt" updated version 3.4.0 inside "tymon/jwt-auth". We had to roll it back to version 3.3.2 to make it worked for us.

**Comment by Luc45** [comment]
Related: 
- https://stackoverflow.com/questions/64999830/getting-exception-while-create-token-using-passport-laravel
- https://stackoverflow.com/questions/65003024/replicating-claims-as-headers-is-deprecated-and-will-removed-from-v4-0-laravel

**Comment by Luc45** [comment]
This is coming from https://github.com/lcobucci/jwt/commit/5ce37ae2061942019e21ad5ef3af160cb5a4ad39#diff-aaf0bc0443d3390951e65b1d6dadf6134554550b510609434969424757f1b6f9R336

It should probably be throwing a notice instead of triggering a fatal error since it's a warning of future deprecation, not actual deprecated.

**Comment by ivalsdtech** [comment]
I have same problem in laravel 5.8

**Comment by Ocramius** [comment]
Would rather say that laravel turning `E_USER_DEPRECATED` into an error is a problem: in other apps, I suppressed laravel's error handling mechanism completely, as it generally leads to this sort of problem.

Overall, I'm also not a fan of `E_USER_DEPRECATED`, as all warnings lead to side effects, but here the resolution path for others is

 1. Pin to an older release of this library in your root `composer.json`
 2. Override Laravel's error handling mechanism (generally incompatible with warnings/notices)
 3. Upgrade this library again
 4. Start migration to `4.0.0` of this library

**Comment by Luc45** [comment]
@Ocramius You are right, I overlooked this application is throwing an `E_USER_DEPRECATED`, which seems fine. Indeed, throwing a fatal for deprecation is overkill, and if it's coming from Laravel, then it seems like a Laravel's problem to me.

**Comment by ArchimedeSolutions** [comment]
Just got this...
`[2020-11-25 12:03:00] development.ERROR: Implicit conversion of keys from strings is deprecated. Please use InMemory or LocalFileReference classes. {"exception":"[object] (ErrorException(code: 0): Implicit conversion of keys from strings is deprecated. Please use InMemory or LocalFileReference classes. at /var/www/vendor/lcobucci/jwt/src/Signer/BaseSigner.php:57)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(16384, 'Implicit conver...', '/var/www/vendor...', 57, Array)
#1 /var/www/vendor/lcobucci/jwt/src/Signer/BaseSigner.php(57): trigger_error('Implicit conver...', 16384)
#2 /var/www/vendor/lcobucci/jwt/src/Signer/BaseSigner.php(46): Lcobucci\\JWT\\Signer\\BaseSigner->getKey('file:///var/www...')
#3 /var/www/vendor/lcobucci/jwt/src/Signature.php(60): Lcobucci\\JWT\\Signer\\BaseSigner->verify('9'\\x16\\xBA\\f|\\x06\\x95\\xA8\\x7F\\xD81\\xB3\\xEC\\xC3...', 'eyJ0eXAiOiJKV1Q...', 'file:///var/www...')
#4 /var/www/vendor/lcobucci/jwt/src/Token.php(258): Lcobucci\\JWT\\Signature->verify(Object(Lcobucci\\JWT\\Signer\\Rsa\\Sha256), 'eyJ0eXAiOiJKV1Q...', 'file:///var/www...')
#5 /var/www/vendor/league/oauth2-server/src/AuthorizationValidators/BearerTokenValidator.php(72): Lcobucci\\JWT\\Token->verify(Object(Lcobucci\\JWT\\Signer\\Rsa\\Sha256), 'file:///var/www...')
#6 /var/www/vendor/league/oauth2-server/src/ResourceServer.php(84): League\\OAuth2\\Server\\AuthorizationValidators\\BearerTokenValidator->validateAuthorization(Object(Nyholm\\Psr7\\ServerRequest))
#7 /var/www/vendor/laravel/passport/src/Guards/TokenGuard.php(204): League\\OAuth2\\Server\\ResourceServer->validateAuthenticatedRequest(Object(Nyholm\\Psr7\\ServerRequest))
#8 /var/www/vendor/laravel/passport/src/Guards/TokenGuard.php(147): Laravel\\Passport\\Guards\\TokenGuard->getPsrRequestViaBearerToken(Object(Illuminate\\Http\\Request))
#9 /var/www/vendor/laravel/passport/src/Guards/TokenGuard.php(110): Laravel\\Passport\\Guards\\TokenGuard->authenticateViaBearerToken(Object(Illuminate\\Http\\Request))
#10 /var/www/vendor/laravel/passport/src/PassportServiceProvider.php(297): Laravel\\Passport\\Guards\\TokenGuard->user(Object(Illuminate\\Http\\Request))
#11 [internal function]: Laravel\\Passport\\PassportServiceProvider->Laravel\\Passport\\{closure}(Object(Illuminate\\Http\\Request), NULL)
#12 /var/www/vendor/laravel/framework/src/Illuminate/Auth/RequestGuard.php(58): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request), NULL)
#13 /var/www/vendor/laravel/framework/src/Illuminate/Auth/GuardHelpers.php(60): Illuminate\\Auth\\RequestGuard->user()
#14 /var/www/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(63): Illuminate\\Auth\\RequestGuard->check()
#15 /var/www/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(42): Illuminate\\Auth\\Middleware\\Authenticate->authenticate(Object(Illuminate\\Http\\Request), Array)
#16 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
#17 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(694): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#19 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(669): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#20 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#21 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#22 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#23 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#24 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /var/www/vendor/fruitcake/laravel-cors/src/HandleCors.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /var/www/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#38 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#39 /var/www/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#40 {main}
"} `

**Comment by lcobucci** [comment]
It's unfortunate that Laravel converts a deprecation message into an exception. Please check the whole explanation on why this approach has been picked [here](https://github.com/lcobucci/jwt/issues/550#issuecomment-733557709).

I'll be closing this as invalid because this lib is behaving in the same way as PHP.
