### ISSUE TITLE
[v4.0] Add stricter ValidAt constraint

### ISSUE THREAD

**Issue by Slamdunk** [lcobucci/jwt#554]
Hi, it seems to me that the new `ValidAt` constraint is very dangerous:

https://github.com/lcobucci/jwt/blob/6d8665ccd924dc076a9b65d1ea8abe21d68f6958/test/unit/Validation/Constraint/ValidAtTest.php#L218-L225

It creates a false sense of security, and it's easy to mess with: I've already had a successful token misused because no time claim was set.

I propose to rename `ValidAt` to `LooseValidAt`, and introduce a new `StrictValidAt` that requires all time claims to be set

**Comment by Slamdunk** [comment]
NDR: `DateTimeImmutable` and `NULL` comparison may return true:

https://github.com/lcobucci/jwt/blob/6d8665ccd924dc076a9b65d1ea8abe21d68f6958/src/Token/Plain.php#L67-L75

Pretty dangerous too!

**Comment by Ocramius** [comment]
@Slamdunk can we turn it into a test case? Seems like an oversight that could have security implications

**Comment by Slamdunk** [comment]
I tried to get `hasBeenIssuedBefore` tested, but then I run into `assertShouldNotRaiseExceptionWhenTokenDoesNotHaveTimeClaims` test so I thought it was done on purpose with the reasoning: "If no time claim has been set, the token shall always be valid in time".

I'm totally against this, but wanted to wait @lcobucci for a reply before a PR

**Comment by lcobucci** [comment]
This constraint was created based in the behaviour we had in v3.x (nothing fails when claims aren't set).
Your concern is valid, though! It's a pity we didn't raise this point during the alpha stages.

We cannot rename it any more (BC-break) but can definitely create the strict one (which makes sure we have the claims before of performing the validations with the `Token`).

Does it make sense to you @Slamdunk?

**Comment by Slamdunk** [comment]
> We cannot rename it any more (BC-break)

We can proxy `ValidAt` to `LooseValidAt` by composition, and deprecated `ValidAt` within a MINOR release.

I'll PR everything soon if it's ok to you. A `4.1.0` can be released right-away without hassles I think

**Comment by lcobucci** [comment]
@Slamdunk sounds like a plan :+1:
