### ISSUE TITLE
can't generate toekn.

### ISSUE THREAD

**Issue by farshidrezaei** [lcobucci/jwt#556]
i get this error

> Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead.

where generating token.

**Comment by lcobucci** [comment]
@farshidrezaei I assume you upgraded to v3.4, did you read the changelog and the upgrading guide?

I do recommend you also to check https://github.com/lcobucci/jwt/issues/550#issuecomment-733557709 to understand how the dynamic deprecation messages (which aren't errors) are handled.

**Comment by lcobucci** [comment]
Also, if this happens in Laravel, please be mindful of: https://twitter.com/driesvints/status/1331584996147126273

**Comment by lcobucci** [comment]
Closing as invalid as per my comments.
