### ISSUE TITLE
3.4.0 introduced a breaking change

### ISSUE THREAD

**Issue by nvahalik** [lcobucci/jwt#557]
Laravel Passport has a dependency set to `^3.3.1` for this library.

Installation of version `3.4.0` for those users will make them start seeing the following error message:

    Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead.

If you're one of those unlucky users, just:

`composer require lcobucci/jwt@~3.3.1`

And you should be all set.

**Comment by lcobucci** [comment]
As mentioned in https://github.com/lcobucci/jwt/issues/550, https://github.com/lcobucci/jwt/issues/553, and https://github.com/lcobucci/jwt/issues/556 this isn't a BC-break.

An issue on Laravel's side has been uncovered and now its users are having deprecation messages (which don't break the app) converted into exceptions https://twitter.com/driesvints/status/1331584996147126273.

Closing as invalid 👍
