### ISSUE TITLE
The new behaviour of the method withClaim breaks our adapters

### ISSUE THREAD

**Issue by Spomky** [lcobucci/jwt#559]
Hi,

In our application, we have adapters for several JWT libraries including this one.
The headers and claims we pass to the adapters are already well-formatted as per the RFCs.

The issue comes from the new version 3.4 (and 4.0 as well) and the [new restriction added here](https://github.com/lcobucci/jwt/blob/3.4.0/src/Builder.php#L414-L416).

As we pass registered/custom claims, the method `withClaim` was fine with it.
With the version 3.4+, an exception is thrown and breaks our application… which is something that should not append for a minor release.

The only way we’ve found is to create a mapping that checks if it is a registered claim or not and call the correct method. This situation is not great at all as it adds complexity and hardcoded method name constants…

What we suggest is to keep the previous behaviour i.e. no exception by default in 3.4:

```php
public function withClaim(string $name, $value, bool $strict = false): BuilderInterface
{
    if ($strict && in_array($name, RegisteredClaims::ALL, true)) {
        throw RegisteredClaimGiven::forClaim($name);
    }

    return $this->setClaim($name, $value);
}
```

And in v4.x, keep the current behaviour by setting `$strict` to `true`:

```php
public function withClaim(string $name, $value, bool $strict = true): BuilderInterface
{
    if ($strict && in_array($name, RegisteredClaims::ALL, true)) {
        throw RegisteredClaimGiven::forClaim($name);
    }

    return $this->setClaim($name, $value);
}
```

**Comment by lcobucci** [comment]
Yeah, throwing the exception on v3.4 breaks BC and it's a mistake (sorry about that).

The guard is there because of expectations about the types used in the registered claims (arrays/DateTimeImmutable/etc).

I'd propose a different approach to this:

```php
public function withClaim(string $name, $value): BuilderInterface
{
    if (in_array($name, RegisteredClaims::ALL, true)) {
        trigger_error('A nice deprecation message', E_USER_DEPRECATED); // just to alert users
    }

    if ($name === RegisteredClaims::AUDIENCE) {
        return $this->permittedFor($value);
    }

    // and the same for the other registered claims

    return $this->setClaim($name, $value);
}
```

This means that your app will be just fine with v3.4 but will need to be updated for v4.0. Is that a reasonable approach?

**Comment by Spomky** [comment]
Hi @lcobucci,

Looks good to me. We will manage that when updating the adapters for v4.0+.
I've just submitted a PR with the code you proposed.

**Comment by lcobucci** [comment]
Thanks for sending the PR, tonight I'll work on this project and work on releasing v3.4.1 👍

**Comment by Spomky** [comment]
Closing as the PR exists. Let’s continue the discussion on #561
