### ISSUE TITLE
Make `Key` extendable

### ISSUE THREAD

**Issue by AlmogBaku** [lcobucci/jwt#56]
`Key` class is final and not extendable. Why?

**Comment by lcobucci** [comment]
That class it's not meant to be extendable.
It's just a value object that contains the key content or certificate path.

Why would you need to extend it?

**Comment by AlmogBaku** [comment]
for implementation of dynamic key (using jti)

**Comment by lcobucci** [comment]
You can create you own key and just pass the instance to ```Key``` constructor, just implement a ```__toString()``` and it will be accepted.

**Comment by lcobucci** [comment]
@AlmogBaku I'll close this issue. If you need any help to make it work please let's discuss.
