### ISSUE TITLE
Deprecation message throws an exception

### ISSUE THREAD

**Issue by ithieme71** [lcobucci/jwt#563]
Since updating from 3.3.3 to 3.4.0 the newly added deprecation messages throw an exception which causes some issues at least in combination with the lexik/jwt-authentication-bundle 2.6.5. 

```
trigger_error('Implicit conversion of keys from strings is deprecated. Please use InMemory or LocalFileReference classes.', E_USER_DEPRECATED);
```

The reason is that the use of trigger_error throws an exception. That's why a lot of developers set the error control operator '@' in front of this function. Then the error can still be seen in the log files but will not throw an exception.

**Comment by lcobucci** [comment]
@ithieme71 that has been covered by https://github.com/lcobucci/jwt/issues/550#issuecomment-733557709. 

> The reason is that the use of trigger_error throws an exception. 

btw, `trigger_error()` doesn't throw an exception. Custom error handlers on frameworks that don't necessarily respect the configured `error_reporting` are the ones to blame here.

I'll be closing this as invalid 👍

**Comment by lcobucci** [comment]
It's also quite weird that exceptions are being thrown on a bundle, given that SF error handler doesn't throw on deprecations https://github.com/symfony/error-handler/blob/5.x/ErrorHandler.php#L40
