### ISSUE TITLE
you faggot 

### ISSUE THREAD

**Issue by stolentine** [lcobucci/jwt#564]
v3.4.x crash my app. You know that in case of violation of reverse compatibility, you need to change the first digit in the version. v<this>.*.*  v<THIS>.*.*?

You should have changed to release this version as v4.0.0

asshole

**Comment by Ocramius** [comment]
Closing and locking: you did not read the license, and you are being disrespectful of hard work done for free.

**Comment by lcobucci** [comment]
You're giving me too much power and credit, here, @stolentine.

Please read https://github.com/lcobucci/jwt/issues/550#issuecomment-733557709.
