### ISSUE TITLE
Composer update 

### ISSUE THREAD

**Issue by fulelamakasi** [lcobucci/jwt#566]
Ran composer update and received this error is there any upgrading guide

Cannot instantiate interface Lcobucci\JWT\Parser {"exception":"[object] (Error(code: 0): Cannot instantiate interface Lcobucci\\JWT\\Parser at app/Http/Middleware/ApiAuthMiddleware.php:45)

**Comment by lcobucci** [comment]
It looks like you upgraded to v4.0. There's an upgrade guide: https://lcobucci-jwt.readthedocs.io/en/stable/upgrading/
