### ISSUE TITLE
Keychain deprecated

### ISSUE THREAD

**Issue by psylo31** [lcobucci/jwt#57]
Is it normal, the class Keychain is deprecated ?

"@deprecated Since we've removed OpenSSL from ECDSA there's no reason to use this class"

I use this class with RSA encryption like in your documentation page , is it an error ?

Thanks for your answer.

**Comment by lcobucci** [comment]
Yes, it will be removed in v4.0.

If you look at its code you'll that it's just returning an instance of ```Key``` which makes it pretty useless :smile:.

**Comment by lcobucci** [comment]
Solved by #58
