### ISSUE TITLE
Cannot use to authenticate with GitHub anymore

### ISSUE THREAD

**Issue by emiliopedrollo** [lcobucci/jwt#582]
Using the Builder's new typed `issuedAt` method generates and token that fails github authentication with the following message:

```
{"message":"'Issued at' claim ('iat') must be an Integer representing the time that the assertion was issued","documentation_url":"https://docs.github.com/rest"}
```

I think a similar problem would occur with `expiresAt`

**Comment by lcobucci** [comment]
@emiliopedrollo as part of the RFC, dates can be represented with numeric strings and have fraction of time.

The default behaviour of the library is to use microsecond precision **if the DateTimeImmutable object has that info**, otherwise an integer will be used.

That means that you may instantiate an object without having microseconds and pass it down to the builder. 

Alternatively, you may change that by proving your own claim formatter. In our docs, we include a sample that does exactly what you want: https://lcobucci-jwt.readthedocs.io/en/latest/extending-the-library/#claims_formatter

**Comment by t0mmy742** [comment]
Hello,

> must be an Integer

This library generates decimal numbers. The [RFC](https://tools.ietf.org/html/rfc7519#page-6) states that non-integer format can be used [You can create your ClaimsFormatter](https://lcobucci-jwt.readthedocs.io/en/latest/extending-the-library/#claims-formatter) to generate Integer as GitHub wants.

**Comment by lcobucci** [comment]
@t0mmy742 I just happened to have my phone in hands and browsing through the GH app :joy:. Your help is much appreciated :heart:

**Comment by killgt** [comment]
I'm having the same issue (in php 8) in combination with https://github.com/GrahamCampbell/Laravel-GitHub . It seems that the github implementation of jwt doesn't respect the spec, and maybe php 8 added decimals to the default info on the DateTime object.

**Comment by emiliopedrollo** [comment]
> I'm having the same issue (in php 8) in combination with https://github.com/GrahamCampbell/Laravel-GitHub . It seems that the github implementation of jwt doesn't respect the spec, and maybe php 8 added decimals to the default info on the DateTime object.

Using Laravel you should use the following:

```php
$now = Carbon::now()->setMilliseconds(0)->toDateTimeImmutable();
```

**Comment by lcobucci** [comment]
@killgt `new DateTimeImmutable('@' . time())` should do the trick too.

Microseconds were added in php 7.1: https://www.php.net/manual/en/datetime.construct.php#refsect1-datetime.construct-changelog

**Comment by killgt** [comment]
Thanks both for your help, i commented on the issue for the next one who have the same issue.

The solution it's to stripe the microseconds, but the hard part its that the `new DateTimeImmutable` its 'hardcoded' on GrahanCambepbell integration of this library. I actually managed to do it overriding the jwt authenticator class, as i don't know any way to change the new DateTimeImmutable behavior remotely.

**Comment by lcobucci** [comment]
@killgt does that library expose the configuration object? If so, you can go with the custom claim formatter approach.

**Comment by killgt** [comment]
I don't think so:

https://github.com/GrahamCampbell/Laravel-GitHub/blob/9.6/src/Auth/Authenticator/PrivateKeyAuthenticator.php#L72
