### ISSUE TITLE
HMAC SHA256 signatures differ in 3.0.5

### ISSUE THREAD

**Issue by robertvandell-ck** [lcobucci/jwt#59]
I recently updated via composer from 3.0.4 to 3.0.5 and the signature portion of tokens no longer behaved as expected.

**Comment by Ocramius** [comment]
Can you clarify on the change? Maybe provide a sample?

**Comment by robertvandell-ck** [comment]
I'm not positive what the change was, but my unit tests started breaking:

3.0.4 (Expected on top, actual on the bottom)

    eyJ0eXAiOiJKV1MiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvYWRtYXguY3JlZGl0a2FybWEuY29tIiwiYXVkIjoiaHR0cHM6XC9cL2FkbWF4LmNyZWRpdGthcm1hLmNvbSIsImZvbyI6ImJhciJ9.cirNIUOWHtqZTgWYzK06s3D9X2VImeZiLn0PzU5xMEo
    eyJ0eXAiOiJKV1MiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvYWRtYXguY3JlZGl0a2FybWEuY29tIiwiYXVkIjoiaHR0cHM6XC9cL2FkbWF4LmNyZWRpdGthcm1hLmNvbSIsImZvbyI6ImJhciJ9.cirNIUOWHtqZTgWYzK06s3D9X2VImeZiLn0PzU5xMEo%

3.0.5

    eyJ0eXAiOiJKV1MiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvYWRtYXguY3JlZGl0a2FybWEuY29tIiwiYXVkIjoiaHR0cHM6XC9cL2FkbWF4LmNyZWRpdGthcm1hLmNvbSIsImZvbyI6ImJhciJ9.cirNIUOWHtqZTgWYzK06s3D9X2VImeZiLn0PzU5xMEo
    eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvYWRtYXguY3JlZGl0a2FybWEuY29tIiwiYXVkIjoiaHR0cHM6XC9cL2FkbWF4LmNyZWRpdGthcm1hLmNvbSIsImZvbyI6ImJhciJ9.FPBLTP10_sx7BYr_St2P1trMkacnyMOt6oj1pGrBYgg%

**Comment by lcobucci** [comment]
Something is really strange with both tokens, can you provide us the inputs?

**Comment by robertvandell-ck** [comment]
I can't provide the exact content, as it's sensitive information, however I can provide an example of a method we're using the library for:

    $token = (new Builder())->setIssuer($issuer)->setAudience($audience);

    $token->set('foo', 'bar');
    $token->sign(new Sha256(), $key);

    return (string) $token->getToken();

**Comment by lcobucci** [comment]
No problem @robertvandell-ck 

The change is in the header part (which is related to the fix that happened in v3.0.5):

eyJ0eXAiOiJKV1**M**iLCJhbGciOiJIUzI1NiJ9
eyJ0eXAiOiJKV1**Q**iLCJhbGciOiJIUzI1NiJ9

Of course that impacts on the signature.

In v3.0.4 we were using "JWS" as typ, but that's not right since we're representing a token and not a signature.

You can always use the [JWT debugger](http://jwt.io) to see the token content.

**Comment by lcobucci** [comment]
Closing since is not an issue, thanks!
