### ISSUE TITLE
Target [Lcobucci\\JWT\\Parser] is not instantiable

### ISSUE THREAD

**Issue by vikas-agent** [lcobucci/jwt#590]
I am trying to login into my application which is in laravel but I'm getting this error.

```
Target [Lcobucci\\JWT\\Parser] is not instantiable while building [Laravel\\Passport\\PersonalAccessTokenFactory].
```

not sure why this is happening.

I tried

1. delete vendor and composer install
2. delete vendor and composer update
3. composer require Iacobucci/jwt it installed ^4.0 version 

Still getting this error. Can you have a look at this?

**Comment by Ocramius** [comment]
`Lcobucci\JWT\Parser` is an interface, hence not instantiable:

https://github.com/lcobucci/jwt/blob/6d8665ccd924dc076a9b65d1ea8abe21d68f6958/src/Parser.php#L10

The configuration of your app should probably specify which parser to use.
