### ISSUE TITLE
ParseError while creating token with passport 

### ISSUE THREAD

**Issue by Tayyab20** [lcobucci/jwt#608]
ParseError
syntax error, unexpected 'Parser' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) 
vendor/lcobucci/jwt/src/Configuration.php:22

I am using "version": "4.0.0",

![Screenshot_2020-12-10 🧨 syntax error, unexpected 'Parser' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)](https://user-images.githubusercontent.com/17792607/101775559-7a767b00-3b11-11eb-9574-0f737900786d.png)

**Comment by lcobucci** [comment]
@Tayyab20 v4.0 requires PHP 7.4+ (which are versions that have typed properties support). It seems like you're not running your app with this same PHP version that you used to download the dependencies (or perhaps you're ignoring platform requirements when installing the lib via composer?).

**Comment by Tayyab20** [comment]
I am using PHP 7.3.12 but I simply installed laravel/passport package. jwt installed with it automatically.
