### ISSUE TITLE
Output of 'getToken' changed when upgrading to 4.0.0

### ISSUE THREAD

**Issue by timmipetit** [lcobucci/jwt#625]
We recently tried upgrading to 4.0.0, but found that the output of 'getToken' seems to be different. Currently we are using 3.4.2, with our code already prepared for the 4.0.0 release.

Our code looks something like this:
```php
$config = \Lcobucci\JWT\Configuration::forSymmetricSigner(new \Lcobucci\JWT\Signer\Rsa\Sha256(), \Lcobucci\JWT\Signer\Key\InMemory::plainText($rsakey));
return $config->builder()
    ->withHeader('alg', 'RS256')
    ->withHeader('typ', 'JWT')
    ->issuedBy($this->clientEmail)
    ->withClaim('scope', 'https://mail.google.com/')
    ->permittedFor('https://oauth2.googleapis.com/token')
    ->issuedAt($issuedAt)
    ->expiresAt($expiry)
    ->relatedTo($username)
    ->getToken($config->signer(), $config->signingKey())
    ->toString();
```

We expected the output for this code to be the same for version 3.4.2 and 4.0.0, is this correct? The difference in the output seems to be triggered by the `withClaim` and `permittedFor` calls.

**Comment by lcobucci** [comment]
The change is related to the date claims, v4 exposes microseconds if your DateTimeImmutable objects have microseconds.

That's expected.

Please check https://github.com/lcobucci/jwt/discussions/623 for possible solutions.

**Comment by lcobucci** [comment]
I'll close it here, please comment on the discussion thread if you need further help/info.

**Comment by timmipetit** [comment]
Digging in a bit further, I suspect that this is a different issue and not related to the date claims. The difference seems to occur because of the lack of escaping of the slashes in the urls in V4.

The output of the claims in 3.4.2 looks something like this (before encoding):
```json
{
   "iss":"tmp-test@mailer-smtp-xoauth2-1.iam.gserviceaccount.com",
   "scope":"https:\/\/mail.google.com\/",
   "aud":"https:\/\/oauth2.googleapis.com\/token",
   "iat":1577872800,
   "exp":1577873700,
   "sub":"info@recras.nl"
}
```

While the output in v4 is:
```json
{
   "iss":"tmp-test@mailer-smtp-xoauth2-1.iam.gserviceaccount.com",
   "scope":"https://mail.google.com/",
   "aud":"https://oauth2.googleapis.com/token",
   "iat":1577872800,
   "exp":1577873700,
   "sub":"info@recras.nl"
}
```

**Comment by Ocramius** [comment]
The v4 output is valid: uses `JSON_UNESCAPED_SLASHES`:

https://github.com/lcobucci/jwt/commit/90386f7d18f7cc6c7ab75e0362362370f5a9ff93#diff-b6fe6a80fe44d045d8d0e01f0556b8fd3ce2c89cfaf5df0dbf9c206bcb02c94eR35
https://github.com/lcobucci/jwt/blob/54c82fdbf457051750ac6f4653241e2e57d57f8c/src/Encoding/JoseEncoder.php#L32

In `3.4.2`, encoding had no flags:

https://github.com/lcobucci/jwt/blob/17cb82dd625ccb17c74bf8f38563d3b260306483/src/Parsing/Encoder.php#L39-L49

Either format is valid JSON, so perhaps a custom encoder implementation is needed in your case?

**Comment by lcobucci** [comment]
@timmipetit I see, that has been done to reduce the token length. As @Ocramius said this is also valid JSON and shouldn't cause issues.

**Comment by timmipetit** [comment]
Interesting. As you might suspect, this is giving us issues indeed. We're getting `invalid_grant` errors back from Google with v4. I guess we'll need a custom encoder for that. Thanks for the swift response :)

**Comment by lcobucci** [comment]
@timmipetit wow, that's quite weird. Is it possible that you've configure the audience/scope with the slashes escaped? I find it hard to believe that Google has issues decoding JSON objects...

We could, perhaps, make the JSON flags configurable on the constructor. That would only be added to v4.1, though, but might make things simpler on your side... Would you like to send us PR?

**Comment by lcobucci** [comment]
btw, the headers `typ` and `alg` are defined automatically by library. `alg` is based on what you sent as a signer and `typ` is **always** `JWT`.

**Comment by timmipetit** [comment]
Really weird indeed. We don't add any escaping to the slashes, this is our literal code:
```php
->withClaim('scope', 'https://mail.google.com/')
->permittedFor('https://oauth2.googleapis.com/token')
```

I'll investigate a bit more. We're in no rush to update to V4.

Also, thanks for the heads up on the `typ` and `alg` headers
