### ISSUE TITLE
It was not possible to parse your key, reason: error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by chococrypto** [lcobucci/jwt#626]
hello I have a error with this package when I use passport. The error occurs when I launch my tests on gitlab.
I don't know why the format of my keys are not correct, I created them on [this website](https://travistidwell.com/jsencrypt/demo/ ) with a size of 2048 bits.

here is my configuration of Laravel in composer.json
- `"php": "^7.3",`
- `"laravel/framework": "^8.0",`
- `"laravel/passport": "^10.0.1",`
-  `"lcobucci/jwt": "^4.0",`
- my php version is `7.4`

here is how I proceed to add my keys on gitlab 
```
...
    - docker run $TEST_IMAGE_TAG echo -n "${PRIVATE_KEY_TEST}" >> storage/oauth-private.key
    - docker run $TEST_IMAGE_TAG echo -n "${PUBLIC_KEY_TEST}" >> storage/oauth-public.key
...
```
`$PRIVATE_KEY_TEST/$PUBLIC_KEY_TEST` - it is the variable that holds the key to rsa

I create an artifact when the job does not go and so the keys are correctly added in the file. Moreover, I use these files in locally and it works. Somebody can help me with this error, I begin to doubt that the error does not come from me (but I don't think so).

Here the error message
`Lcobucci\JWT\Signer\InvalidKeyProvided: It was not possible to parse your key, reason: error:0906D06C:PEM routines:PEM_read_bio:no start line in file /var/www/vendor/lcobucci/jwt/src/Signer/InvalidKeyProvided.php on line 13\n`

**Comment by lcobucci** [comment]
This seems to be an issue with how you're using docker on your pipeline. You could share the rest of the job so we can say that with 100% sure.

The hint is in `docker run`. That executes a command in an isolated container using the given image. This means that you're writing to a file in that container and simply not doing anything with it.

If you are using another `docker run` to execute your tests then you won't have the files there, since it's a brand new container. You should look into passing the keys as mounted volumes or environment variables.

**Comment by chococrypto** [comment]
here is the script I run in test 
```
  script:
    - docker pull $TEST_IMAGE_TAG
    - mysqlip=$(getent hosts mysql | awk '{ print $1 ; exit }')
    - docker run --network=host --env DB_HOST=$mysqlip $TEST_IMAGE_TAG php artisan migrate
    - docker run $TEST_IMAGE_TAG echo -n "${PRIVATE_KEY_TEST}" >> storage/oauth-private.key
    - docker run $TEST_IMAGE_TAG echo -n "${PUBLIC_KEY_TEST}" >> storage/oauth-public.key
    - docker run --network=host
      -e DB_HOST=$mysqlip
      -e APP_KEY="$APP_KEY_TEST"
      $TEST_IMAGE_TAG ./vendor/bin/phpunit --coverage-text --colors=never
```

oooh ok I just understand why it doesn't work. I'm going to try this: 

```
  script:
    - docker pull $TEST_IMAGE_TAG
    - mysqlip=$(getent hosts mysql | awk '{ print $1 ; exit }')
    - docker run --network=host --env DB_HOST=$mysqlip $TEST_IMAGE_TAG php artisan migrate
    - docker run --network=host
      -e DB_HOST=$mysqlip
      -e APP_KEY="$APP_KEY_TEST"
      $TEST_IMAGE_TAG 
      echo -n "${PRIVATE_KEY_TEST}" >> storage/oauth-private.key &&
      echo -n "${PUBLIC_KEY_TEST}" >> storage/oauth-public.key &&
      ./vendor/bin/phpunit --coverage-text --colors=never
```

Do you think this is the right way to do it?

**Comment by lcobucci** [comment]
Okay, so that confirms my thoughts.
I'd suggest you to dive a bit more and understand how docker (and `docker run`) works but if your app expects files, doing something like this should make things clearer:

```yaml
  script:
    - docker pull $TEST_IMAGE_TAG
    - mysqlip=$(getent hosts mysql | awk '{ print $1 ; exit }')
    - docker run --network=host --env DB_HOST=$mysqlip $TEST_IMAGE_TAG php artisan migrate
    - echo -n "${PRIVATE_KEY_TEST}" > oauth-private.key
    - echo -n "${PUBLIC_KEY_TEST}" > oauth-public.key
    - docker run --network=host
      -e DB_HOST=$mysqlip
      -e APP_KEY="$APP_KEY_TEST"
      -v oauth-private.key:storage/oauth-private.key
      -v oauth-public.key:storage/oauth-public.key
      $TEST_IMAGE_TAG
      ./vendor/bin/phpunit --coverage-text --colors=never
```

That script can be drastically simplified by using a side-car container and your test image as the base image of your job. Check https://docs.gitlab.com/ee/ci/docker/using_docker_images.html.

I'll close this since it's 100% unrelated to the lib.

**Comment by chococrypto** [comment]
I tried your solution and you forgot about `/` in  `-v oauth-private.key:storage/oauth-private.key`

here are my cmd:

```
...
    - echo -n "${PRIVATE_KEY_TEST}" > oauth-private.key
    - echo -n "${PUBLIC_KEY_TEST}" > oauth-public.key
    - docker run --network=host
      -e DB_HOST=$mysqlip
      -e APP_KEY="$APP_KEY_TEST"
      -v oauth-private.key:/storage/oauth-private.key
      -v oauth-public.key:/storage/oauth-public.key
      $TEST_IMAGE_TAG ./vendor/bin/phpunit --coverage-text --colors=never
...
```

However, the proposed solution does not work because the keys RSA are added in the project root and not in the `storage/` folder.

<img width="309" alt="Capture d’écran 2021-01-08 à 18 16 48" src="https://user-images.githubusercontent.com/27860198/104044489-adc62b80-51dd-11eb-9f33-435862b7e272.png">

I tried another solution but I can't add the keys in the storage folder.

**Comment by lcobucci** [comment]
I didn't forget, I used a relative path but check your workdir to use the absolute one.

But again this is all about Docker and gitlab CI, I'd (again) suggest you reading about the concepts and/or asking help to people behind those tools.

We just pointed out what was happened on the library's perspective (key isn't set in the container).

**Comment by lcobucci** [comment]
Bear in mind you can also try the docker commands locally.
