### ISSUE TITLE
DateTime related constraints require (unnecessary) Clock interface

### ISSUE THREAD

**Issue by khorsky** [lcobucci/jwt#631]
Is there any good explanation why do all DateTime related constraints require proprietary `Lcobucci\Clock\Clock` interface instead of simple `DateTimeImmutable`?

I've checked the code and it seems a bit exaggerated to me - it makes the usage more complicated. IMHO one has usually some implementation of `MyFavorite\Clock` interface. This way I need to write my own Constraint or use your implementation.

I would vote for KISS, because I see no benefit here. Have I overlooked something interesting?

**Comment by Ocramius** [comment]
A clock allows time manipulation in complex test scenarios, as well as runtime time emulation.

**Comment by Ocramius** [comment]
BTW, simple clock:

```php
$clock = new class implements Clock {
    function now () { return new DateTimeImmutable(); }
}
```

**Comment by khorsky** [comment]
I get the idea.

Thanks for clarification Marco.
