### ISSUE TITLE
Constraints SignedWith doesn't work.

### ISSUE THREAD

**Issue by MuhammedAlmaz** [lcobucci/jwt#659]
I want to use SignedWith on validate method but it's doesn't work when i change one key of signature. 

```php
private static function getConfig(): Configuration
{
    $config= Configuration::forSymmetricSigner(new Sha256(), InMemory::plainText(env("JWT_PRIVATE_KEY")));
    $config->setValidationConstraints(new SignedWith($config->signer(), $config->signingKey()));
    return $config;
}

private static  function createToken(array $claims = []): String
{
    $config = JWTHelper::getConfig();
    $now   = new DateTimeImmutable();
    $exp = $now->modify('+1 hour');
    $builder = $config->builder()
        ->issuedBy(JWTHelper::$issuedBy)
        ->permittedFor(JWTHelper::$permitedFor)
        ->issuedAt($now)
        ->identifiedBy(JWTHelper::generateClaimsKey($claims, $exp->getTimestamp() . $exp->format(".u")))
        ->canOnlyBeUsedAfter($now)
        ->withHeader("tokenType", "ORK_33|2")
        ->withHeader("generatedBy", "Muhammed#ALMAZ")
        ->expiresAt($exp);
    foreach ($claims as $key => $value) {
        $builder->withClaim($key, $value);
    }
    $token = $builder->getToken($config->signer(), $config->signingKey());
    return $token->toString();
}


public static function isValid(string $token): bool
{
    try {
        if ($token == null) return false;
        $config = JWTHelper::getConfig();
        $parsedToken = $config->parser()->parse($token);
        assert($parsedToken instanceof Plain);
        $exp = $parsedToken->claims()->get("exp");
        $config->setValidationConstraints(new IssuedBy(JWTHelper::$issuedBy));
        $config->setValidationConstraints(new PermittedFor(JWTHelper::$permitedFor));
        $config->setValidationConstraints(
            new IdentifiedBy(
                JWTHelper::generateClaimsKey(
                    $parsedToken->claims()->all(),
                    $exp->getTimestamp() . $exp->format(".u")
                )
            )
        );
        $constraints = $config->validationConstraints();
        $config->validator()->assert($parsedToken, ...$constraints);
        if (!$config->validator()->validate($parsedToken, ...$constraints)) {
            die("no");
            return false;
        }
        if ($parsedToken->isExpired(new DateTimeImmutable())) return false;
    } catch (Exception) {
        die("no");
        return false;
    }

    die("ok");
    return true;
}
```

I get this token from this key

`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsInRva2VuVHlwZSI6Ik9SS18zM3wyIiwiZ2VuZXJhdGVkQnkiOiJNdWhhbW1lZCNBTE1BWiJ9.eyJpc3MiOiJodHRwczovL3RlbWt1cnllLmNvbSIsImF1ZCI6Imh0dHBzOi8vdGVta3VyeWUuY29tIiwiaWF0IjoiMTYxMjY4NDQzMS41NzcxMTgiLCJqdGkiOiJNdWhhbW1lZEFsbWF6LjJmNjgzYjZjZTZlNTQ1MWUyZTNhNzZiMmRhNjJlZDMzIiwibmJmIjoiMTYxMjY4NDQzMS41NzcxMTgiLCJleHAiOiIxNjEyNjg4MDMxLjU3NzExOCIsInJvbGUiOjIsInVzZXJJbmZvcm1hdGlvbklkIjoyODUsInVzZXJJZCI6MTA4fQ.X0f89t1JYiaTpG57sLWGhjxw-puOZuD0GRo4MV4eR6Y`

it's valid on jwt.io also. But when i change last key of signature jwt.io give error but isValid function don't give error. 
![1](https://user-images.githubusercontent.com/17336091/107140573-fa636a80-6933-11eb-817c-de219268e27e.png)

next token

`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsInRva2VuVHlwZSI6Ik9SS18zM3wyIiwiZ2VuZXJhdGVkQnkiOiJNdWhhbW1lZCNBTE1BWiJ9.eyJpc3MiOiJodHRwczovL3RlbWt1cnllLmNvbSIsImF1ZCI6Imh0dHBzOi8vdGVta3VyeWUuY29tIiwiaWF0IjoiMTYxMjY4NDQzMS41NzcxMTgiLCJqdGkiOiJNdWhhbW1lZEFsbWF6LjJmNjgzYjZjZTZlNTQ1MWUyZTNhNzZiMmRhNjJlZDMzIiwibmJmIjoiMTYxMjY4NDQzMS41NzcxMTgiLCJleHAiOiIxNjEyNjg4MDMxLjU3NzExOCIsInJvbGUiOjIsInVzZXJJbmZvcm1hdGlvbklkIjoyODUsInVzZXJJZCI6MTA4fQ.X0f89t1JYiaTpG57sLWGhjxw-puOZuD0GRo4MV4eR6U`

![2](https://user-images.githubusercontent.com/17336091/107140574-fd5e5b00-6933-11eb-8b2a-465588eff0cf.png)

What is my mistake ? I cant verify the signedWith constratint I change last char Y to U and in this code verify token but JWT.IO not.

**Comment by lcobucci** [comment]
I'm not sure if I follow here... You want to manually manipulate the signature and expect the validation to still work? If so, why?

On the technical details why this might work in different libs but doesn't work here, it has to do with the fact we use a stricter implementation of base64url decoding. That will probably generate a different binary hash, which fails when comparing the hash of the payload.

Please explain what do you plan to achieve/validate here so we can confirm that this isn't an issue.

**Comment by MuhammedAlmaz** [comment]
Just i want to sure about the signedWith contstraint work properly. But i guess it doesn't work fine. Cuz i can manipule the JWT like that. its just a example. In the JWT.IO website its doesn't work but in this library it's working. So i can't trust this library :(

**Comment by lcobucci** [comment]
@MuhammedAlmaz I really can't reproduce what you're describing here:

```php
<?php
declare(strict_types=1);

require __DIR__ . '/vendor/autoload.php';

use Lcobucci\JWT\Configuration;
use Lcobucci\JWT\Signer\Hmac\Sha256;
use Lcobucci\JWT\Signer\Key\InMemory;
use Lcobucci\JWT\Validation\Constraint\SignedWith;

$config = Configuration::forSymmetricSigner(new Sha256(), InMemory::plainText('TEST_1453'));

$originalJwt = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsInRva2VuVHlwZSI6Ik9SS18zM3wyIiwiZ2VuZXJhdGVkQnkiOiJNdWhhbW1lZCNBTE1BWiJ9.eyJpc3MiOiJodHRwczovL3RlbWt1cnllLmNvbSIsImF1ZCI6Imh0dHBzOi8vdGVta3VyeWUuY29tIiwiaWF0IjoiMTYxMjY4NDQzMS41NzcxMTgiLCJqdGkiOiJNdWhhbW1lZEFsbWF6LjJmNjgzYjZjZTZlNTQ1MWUyZTNhNzZiMmRhNjJlZDMzIiwibmJmIjoiMTYxMjY4NDQzMS41NzcxMTgiLCJleHAiOiIxNjEyNjg4MDMxLjU3NzExOCIsInJvbGUiOjIsInVzZXJJbmZvcm1hdGlvbklkIjoyODUsInVzZXJJZCI6MTA4fQ.X0f89t1JYiaTpG57sLWGhjxw-puOZuD0GRo4MV4eR6Y';
$modifiedJwt = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsInRva2VuVHlwZSI6Ik9SS18zM3wyIiwiZ2VuZXJhdGVkQnkiOiJNdWhhbW1lZCNBTE1BWiJ9.eyJpc3MiOiJodHRwczovL3RlbWt1cnllLmNvbSIsImF1ZCI6Imh0dHBzOi8vdGVta3VyeWUuY29tIiwiaWF0IjoiMTYxMjY4NDQzMS41NzcxMTgiLCJqdGkiOiJNdWhhbW1lZEFsbWF6LjJmNjgzYjZjZTZlNTQ1MWUyZTNhNzZiMmRhNjJlZDMzIiwibmJmIjoiMTYxMjY4NDQzMS41NzcxMTgiLCJleHAiOiIxNjEyNjg4MDMxLjU3NzExOCIsInJvbGUiOjIsInVzZXJJbmZvcm1hdGlvbklkIjoyODUsInVzZXJJZCI6MTA4fQ.X0f89t1JYiaTpG57sLWGhjxw-puOZuD0GRo4MV4eR6U';

$token1 = $config->parser()->parse($originalJwt);
$token2 = $config->parser()->parse($modifiedJwt);

$validator  = $config->validator();
$signedWith = new SignedWith($config->signer(), $config->verificationKey());

assert($validator->validate($token1, $signedWith));
$validator->assert($token1, $signedWith);

assert(! $validator->validate($token2, $signedWith));
$validator->assert($token2, $signedWith);
```

The output is (on both PHP 7.4 and PHP 8.0):

```sh
PHP Fatal error:  Uncaught Lcobucci\JWT\Validation\RequiredConstraintsViolated: The token violates some mandatory constraints, details:
- Token signature mismatch in /home/lcobucci/projects/tests/jwt-signature-manipulation/vendor/lcobucci/jwt/src/Validation/RequiredConstraintsViolated.php:19
Stack trace:
#0 /home/lcobucci/projects/tests/jwt-signature-manipulation/vendor/lcobucci/jwt/src/Validation/Validator.php(23): Lcobucci\JWT\Validation\RequiredConstraintsViolated::fromViolations()
#1 /home/lcobucci/projects/tests/jwt-signature-manipulation/aa.php(26): Lcobucci\JWT\Validation\Validator->assert()
#2 {main}
  thrown in /home/lcobucci/projects/tests/jwt-signature-manipulation/vendor/lcobucci/jwt/src/Validation/RequiredConstraintsViolated.php on line 19
```

Can you try to reduce your code - in the same way I did - so we can pinpoint the cause?

**Comment by MuhammedAlmaz** [comment]
I got my error lets see.. I Run your code and it's ok.
The problem was setValidationConstraints. I mean its setting the by one by. but i must put the multiple constraints (array) on this method. And then in my code just IdentifiedBy worked. 

It's ok i found the mistake thanks !!
