### ISSUE TITLE
Call to undefined function sodium_bin2base64()

### ISSUE THREAD

**Issue by sina-developer** [lcobucci/jwt#664]
i'm using laravel passport which uses this package 

i can use this lib on local but on shared host it couse an error:

Call to undefined function sodium_bin2base64()

**Comment by Slamdunk** [comment]
I guess you are uploading a build of your code in the shared host, with SCP/SFTP or something, otherwise composer would have warned you that without `ext-sodium` you cannot install this lib anymore.

`ext-sodium` is required since `v4.1`

**Comment by sina-developer** [comment]
> I guess you are uploading a build of your code in the shared host, with SCP/SFTP or something, otherwise composer would have warned you that without `ext-sodium` you cannot install this lib anymore.
> 
> `ext-sodium` is required since `v4.1`

Yeah

i'm using shared host with FTP

what do you suggest to solve this problem?

**Comment by Slamdunk** [comment]
`sodium_bin2base64` is used to issue the tokens and cannot be avoided: you should configure the hosting to have `ext-sodium` enabled

**Comment by sina-developer** [comment]
OK

thank you for your response
