### ISSUE TITLE
Call to undefined function sodium_bin2base64

### ISSUE THREAD

**Issue by neguradionisie** [lcobucci/jwt#665]
After last update 4.1.0 i got error  *Call to undefined function sodium_bin2base64() {"exception":"[object] (Error(code: 0): Call to undefined function sodium_bin2base64() at vendor/lcobucci/jwt/src/Encoding/JoseEncoder.php:50)* my php version is 7.4.13  and sodium version 1.0.13. If i change sodium version to 1.0.18 everything is fine.

**Comment by Slamdunk** [comment]
`sodium_bin2base64` was in fact first introduced in `1.0.14`: https://github.com/jedisct1/libsodium/commit/3f272cbbfcd6b29e511386e87c60e6a425354aa6
And first introduced in `libsodium-php` in `2.0.6`: https://github.com/jedisct1/libsodium-php/commit/0e4c82112f0d34b57f0317ae65221f39698f7431

I'll see if we can require a minimum version for `ext-sodium`

**Comment by Slamdunk** [comment]
As I feared, even though `ext-sodium` version is known to PHP:

```
$ php -i | grep sodium
sodium
sodium support => enabled
libsodium headers version => 1.0.18
libsodium library version => 1.0.18

$ php -r 'print_r(get_defined_constants(true));' | grep -i sodium | grep -i version
            [SODIUM_LIBRARY_VERSION] => 1.0.18
            [SODIUM_LIBRARY_MAJOR_VERSION] => 10
            [SODIUM_LIBRARY_MINOR_VERSION] => 3
```

There is no standardization around extension versioning, so composer is unaware of it.
As a result, unfortunately we cannot require the correct version into `composer.json`.

We could leverage `SODIUM_LIBRARY_VERSION` constant, but I don't like dynamic checks for extensions.
It's worth a doc update though.

WDYT @lcobucci ?

**Comment by SvenRtbg** [comment]
Detect with function_exists() and either have an alternative implementation or send a descriptive error message.

In theory you could require extension versions in Composer. In practice they act as hidden PHP version requirements, and users are usually unable to update extensions, either because they lack the permissions or their distribution does not have them.

**Comment by lcobucci** [comment]
I'd add back the old implementation as a new class (legacy encoder?) and put the logic to pick the new or the legacy (or the user provided one) on the config class.

Then we keep the weird stuff in the service locator.

@Slamdunk how does that sound?

**Comment by susheelk985** [comment]
Error: Call to undefined function sodium_bin2base64() in file vendor/lcobucci/jwt/src/Encoding/JoseEncoder.php on line 50

How to solve this issue?

**Comment by Slamdunk** [comment]
Either upgrade `libsodium` or wait for https://github.com/lcobucci/jwt/pull/670 fix to be released

**Comment by lcobucci** [comment]
Released!
