### ISSUE TITLE
[3.4.*] composer aliases missing when classmap-authoritative is applied

### ISSUE THREAD

**Issue by fyrye** [lcobucci/jwt#666]
**Affected version:** 3.4
**PHP Version:** 7.3.22

Encountered the issue in https://github.com/scheb/2fa/issues/57.

It appears the `lcobucci/jwt/compat/class-aliases.php` is not properly configured to support the `classmap-authoritative`, expecting `class_exists()` to call the autoloader which is not run when `classmap-authoritative` is applied.

Thoughts on changing `class-aliases.php` to?:

```php
class_exists(\Lcobucci\JWT\Token\Plain::class) || class_alias(\Lcobucci\JWT\Token::class, \Lcobucci\JWT\Token\Plain::class);
class_exists(\Lcobucci\JWT\Token\Signature::class) || class_alias(\Lcobucci\JWT\Token::class, \Lcobucci\JWT\Token\Signature::class);
```

**Comment by lcobucci** [comment]
Resolved by #667
