### ISSUE TITLE
Implement Magic Method __toString.

### ISSUE THREAD

**Issue by rbrouwer** [lcobucci/jwt#669]
Would it be possible to implement the magic method [__toString](https://www.php.net/manual/en/language.oop5.magic.php#object.tostring) in at least Lcobucci\JWT\Token\Plain?

**Comment by Slamdunk** [comment]
May I ask you what could you to with `__toString()` that you can't do with the current `toString`?
Magic is the path to brittleness, imho

**Comment by lcobucci** [comment]
We removed the magic method on purpose from v4 and don't have plans for adding it back.

The implicit call created confusion among our users and that's something we want to avoid as much as possible.

**Comment by rbrouwer** [comment]
It might ease some migration to 4. In v3 you had to cast to a specifically cast tokens to a string, you now have to call toString(). Why not support both? 

I honestly do believe a adding a simple
```
public function __toString(): string
{
    return $this->toString();
}
```
wouldn't hurt this solution, yet make it easier for people to do migrations from 3 to 4.

**Comment by Ocramius** [comment]
Better explanation at https://github.com/ShittySoft/symfony-live-berlin-2018-doctrine-tutorial/pull/3#issuecomment-460441229

Closing here.

**Comment by Slamdunk** [comment]
I was looking for that very post. I really need a web search for every of your post with a like.

**Comment by lcobucci** [comment]
> It might ease some migration to 4. In v3 you had to cast to a specifically cast tokens to a string, you now have to call toString(). Why not support both?
> 
> I honestly do believe a adding a simple
> 
> ```
> public function __toString(): string
> {
>     return $this->toString();
> }
> ```
> 
> wouldn't hurt this solution, yet make it easier for people to do migrations from 3 to 4.

@rbrouwer that's why v3.4.x still has it. We mention that on our migration guide: https://lcobucci-jwt.readthedocs.io/en/4.1.x/upgrading/#v3x-to-v4x

**Comment by Ocramius** [comment]
> I was looking for that very post. I really need a web search for every of your post with a like.

I use my firefox search bar, plus I'm too damn lazy to write a blogpost.
