### ISSUE TITLE
Error while decoding from JSON

### ISSUE THREAD

**Issue by cyrilbosson** [lcobucci/jwt#681]
Hello,

I had [this issue](https://github.com/lcobucci/jwt/issues/665) on my hosting server so I upgraded to 4.1.1 but now I have this error:

`Error while decoding from JSON`

**Stacktrace**
`/home/clients/9ec8ad5583918ce55944b1cc6bdd9057/web/releases/95/vendor/lcobucci/jwt/src/Encoding/JoseEncoder.php:41
/home/clients/9ec8ad5583918ce55944b1cc6bdd9057/web/releases/95/vendor/lcobucci/jwt/src/Token/Parser.php:67
/home/clients/9ec8ad5583918ce55944b1cc6bdd9057/web/releases/95/vendor/lcobucci/jwt/src/Token/Parser.php:30`

I use it with Laravel 8.28.1 & Telescope 10.1.0

PHP 7.4.15

Thanks !

**Comment by Ocramius** [comment]
That usually happens when your input string is not JSON:

https://github.com/lcobucci/jwt/blob/f7c9bb18699ff328e988b12cb6c504ca0ffaa1d0/src/Encoding/JoseEncoder.php#L25-L43

The library is correctly throwing an exception here.

**Comment by cyrilbosson** [comment]
Ok but my JSON didn't change 🤨
I switched to 3.4.5 and I works now

**Comment by Ocramius** [comment]
@cyrilbosson can the string you are trying to encode (with 3.x) be posted here (as in no NDA'd secrets)? Can you perhaps provide a full JWT token string? Can you try looking at it on https://jwt.io/ ?

Also, I wonder if some of the fields you are trying to encode contain non-utf8 characters (which leads to `null` output for fields, but would throw when using `JSON_THROW_ON_ERROR`)

**Comment by cyrilbosson** [comment]
The JSON response :

{
"data": {
"user": {
"id": 59,
"name": "TEST",
"firstname": "Cyril",
"email": "test@example.com",
"locale": "fr",
"avatar": "https://www.example.com/images/default.gif"
},
"patient": {
"id": 66,
"name": "TEST",
"birthname": "",
"firstname": "Cyril",
"gender": "m",
"birthdate": "2020-10-25",
"nir": "145121212312308",
"email": "test@example.com",
"phone": "123456789",
"referring_doctor": null,
"new_patient": 0,
"address": {
"line_1": "route",
"postcode": "75000",
"city": "Paris",
"country": "fr"
},
"appointments": [
]
},
"access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNDIyZDUyNTRkNWZjZTM5OWFhNThhYWU5ZGJmZDBmNTUwM2JiOWQ4OTgwYTcwNzJjZDk5NTcyMTg1NzcwODYyZjZhNDUwNTQ2ZTIyNjk4ZjUiLCJpYXQiOjE2MTM1ODE2OTQsIm5iZiI6MTYxMzU4MTY5NCwiZXhwIjoxNjQ1MTE3Njk0LCJzdWIiOiI1OSIsInNjb3BlcyI6W119.nNA0Uz9uLptDAJ57rmnYnoP80bp2eGlqPbv3jkANGgXLPm1W8GxibEyKMivzgg_7U5I4D5_IB19OR9ESTg_tNUztBydFSNsYnmsxuQxiH3cKt-1-JzeVyYORUhk1cPPlKp7g_s3hZxSWjCwtmeYdfitpvA7MvVhZfLCZG1UC5ukrrCrsM84_itdb5QFNGL6RwXPwBDGzdVHLX9MaBgB4oL6K_QtfauW6ki2TracqzTYtzCbTGSnVVSR5yFBnnzXd_uyx0schZneLSEQRUOlfI1P4LRhvn_dfzMfHQ8GMZEpuoHrPPnioQym8EV5lXmWzfC2TKi0nV1W89e-_W8apWchFtIDeg6wpRCNiGgMUomz4bPpCxUH13XSJIzELFSWCehH4dZcvnAW-K9788H3UExgCc5hQlcKdIONlWLUlAvWLNR58huaFA1TAcLfiuv3Xjjv4G9ihmdo47dtDlyWpsXlCZE56HycKZwwCC0_F49ws9C4ZsrbCYk1Cq5-gY_55ruqfTURk0pNVwFg9bxiHQrHcxDChvnotmWi9NYmBBYrETYGP4DYrOH4_k1CHJwn3GRpW9ma8XTL75M3Ejl5DWduZnS1Yk_d59g-d5EmS6862_giyWMATuStufnpibgLT8jaViuQ2TfcEVArijS07KKk7IJADavXgPh6ZAFECDC8"
}
}

**Comment by lcobucci** [comment]
@cyrilbosson I cannot reproduce your issue using the latest version of the lib and the token in the `access_token` property you sent:

```php
<?php
declare(strict_types=1);

use Lcobucci\JWT\Encoding\JoseEncoder;
use Lcobucci\JWT\Token\Parser;
use Lcobucci\JWT\UnencryptedToken;

require 'vendor/autoload.php';

$token = (new Parser(new JoseEncoder()))->parse(
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNDIyZDUyNTRkNWZjZTM5OWFhNThhYWU5ZGJmZDBmNTUwM2JiOWQ4OTgwYTcwNzJjZDk5NTcyMTg1NzcwODYyZjZhNDUwNTQ2ZTIyNjk4ZjUiLCJpYXQiOjE2MTM1ODE2OTQsIm5iZiI6MTYxMzU4MTY5NCwiZXhwIjoxNjQ1MTE3Njk0LCJzdWIiOiI1OSIsInNjb3BlcyI6W119.nNA0Uz9uLptDAJ57rmnYnoP80bp2eGlqPbv3jkANGgXLPm1W8GxibEyKMivzgg_7U5I4D5_IB19OR9ESTg_tNUztBydFSNsYnmsxuQxiH3cKt-1-JzeVyYORUhk1cPPlKp7g_s3hZxSWjCwtmeYdfitpvA7MvVhZfLCZG1UC5ukrrCrsM84_itdb5QFNGL6RwXPwBDGzdVHLX9MaBgB4oL6K_QtfauW6ki2TracqzTYtzCbTGSnVVSR5yFBnnzXd_uyx0schZneLSEQRUOlfI1P4LRhvn_dfzMfHQ8GMZEpuoHrPPnioQym8EV5lXmWzfC2TKi0nV1W89e-_W8apWchFtIDeg6wpRCNiGgMUomz4bPpCxUH13XSJIzELFSWCehH4dZcvnAW-K9788H3UExgCc5hQlcKdIONlWLUlAvWLNR58huaFA1TAcLfiuv3Xjjv4G9ihmdo47dtDlyWpsXlCZE56HycKZwwCC0_F49ws9C4ZsrbCYk1Cq5-gY_55ruqfTURk0pNVwFg9bxiHQrHcxDChvnotmWi9NYmBBYrETYGP4DYrOH4_k1CHJwn3GRpW9ma8XTL75M3Ejl5DWduZnS1Yk_d59g-d5EmS6862_giyWMATuStufnpibgLT8jaViuQ2TfcEVArijS07KKk7IJADavXgPh6ZAFECDC8'
);

var_dump($token instanceof UnencryptedToken); // bool(true)
```

Can you provide more information or check if your application is sending the JWT properly to the parser?

**Comment by amrishkakadiya** [comment]
I am facing similar error. Its working fine in other dedicated server but not in Shared Hosting.
Code and even project is same in both server.

My Token:

**eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOiIxNjIwNjIxMjY4LjI2Mzc3MCIsImV4cCI6IjE2MjA2MjEzMjguMjYzNzcwIiwiaWQiOjEsInJvbGUiOiJhZG1pbiJ9.K2VEqI5XnHMf-Je4iYh857GgXhs2z9AmlnvvJhjbRUw**


**Error** 

```
throwable JsonException: Syntax error in /home/smartmpsco/public_html/cust/rms/api/vendor/lcobucci/jwt/src/Encoding/JoseEncoder.php:39
Stack trace:
#0 /home/smartmpsco/public_html/cust/rms/api/vendor/lcobucci/jwt/src/Encoding/JoseEncoder.php(39): json_decode('ZXlKMGVYQWlPaUp...', true, 512, 4194304)
#1 /home/smartmpsco/public_html/cust/rms/api/vendor/lcobucci/jwt/src/Token/Parser.php(67): Lcobucci\JWT\Encoding\JoseEncoder->jsonDecode('ZXlKMGVYQWlPaUp...')
#2 /home/smartmpsco/public_html/cust/rms/api/vendor/lcobucci/jwt/src/Token/Parser.php(30): Lcobucci\JWT\Token\Parser->parseHeader('eyJ0eXAiOiJKV1Q...')
#3 /home/smartmpsco/public_html/cust/rms/api/app/Http/Middleware/ParseToken.php(41): Lcobucci\JWT\Token\Parser->parse('eyJ0eXAiOiJKV1Q...')
#4 /home/smartmpsco/public_html/cust/rms/api/vendor/illuminate/pipeline/Pipeline.php(167): App\Http\Middleware\ParseToken->handle(Object(Laravel\Lumen\Http\Request), Object(Closure))
#5 /home/smartmpsco/public_html/cust/rms/api/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Laravel\Lumen\Http\Request))
#6 /home/smartmpsco/public_html/cust/rms/api/app/Http/Middleware/CorsMiddleware.php(60): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Laravel\Lumen\Http\Request))
#7 /home/smartmpsco/public_html/cust/rms/api/vendor/illuminate/pipeline/Pipeline.php(167): App\Http\Middleware\CorsMiddleware->handle(Object(Laravel\Lumen\Http\Request), Object(Closure))
#8 /home/smartmpsco/public_html/cust/rms/api/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Laravel\Lumen\Http\Request))
#9 /home/smartmpsco/public_html/cust/rms/api/vendor/illuminate/pipeline/Pipeline.php(103): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Laravel\Lumen\Http\Request))
#10 /home/smartmpsco/public_html/cust/rms/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(423): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#11 /home/smartmpsco/public_html/cust/rms/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(172): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#12 /home/smartmpsco/public_html/cust/rms/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(109): Laravel\Lumen\Application->dispatch(NULL)
#13 /home/smartmpsco/public_html/cust/rms/api/public/index.php(28): Laravel\Lumen\Application->run()
#14 {main}

Next Lcobucci\JWT\Encoding\CannotDecodeContent: Error while decoding from JSON in /home/smartmpsco/public_html/cust/rms/api/vendor/lcobucci/jwt/src/Encoding/CannotDecodeContent.php:14
Stack trace:
#0 /home/smartmpsco/public_html/cust/rms/api/vendor/lcobucci/jwt/src/Encoding/JoseEncoder.php(41): Lcobucci\JWT\Encoding\CannotDecodeContent::jsonIssues(Object(JsonException))
#1 /home/smartmpsco/public_html/cust/rms/api/vendor/lcobucci/jwt/src/Token/Parser.php(67): Lcobucci\JWT\Encoding\JoseEncoder->jsonDecode('ZXlKMGVYQWlPaUp...')
#2 /home/smartmpsco/public_html/cust/rms/api/vendor/lcobucci/jwt/src/Token/Parser.php(30): Lcobucci\JWT\Token\Parser->parseHeader('eyJ0eXAiOiJKV1Q...')
#3 /home/smartmpsco/public_html/cust/rms/api/app/Http/Middleware/ParseToken.php(41): Lcobucci\JWT\Token\Parser->parse('eyJ0eXAiOiJKV1Q...')
#4 /home/smartmpsco/public_html/cust/rms/api/vendor/illuminate/pipeline/Pipeline.php(167): App\Http\Middleware\ParseToken->handle(Object(Laravel\Lumen\Http\Request), Object(Closure))
#5 /home/smartmpsco/public_html/cust/rms/api/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Laravel\Lumen\Http\Request))
#6 /home/smartmpsco/public_html/cust/rms/api/app/Http/Middleware/CorsMiddleware.php(60): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Laravel\Lumen\Http\Request))
#7 /home/smartmpsco/public_html/cust/rms/api/vendor/illuminate/pipeline/Pipeline.php(167): App\Http\Middleware\CorsMiddleware->handle(Object(Laravel\Lumen\Http\Request), Object(Closure))
#8 /home/smartmpsco/public_html/cust/rms/api/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Laravel\Lumen\Http\Request))
#9 /home/smartmpsco/public_html/cust/rms/api/vendor/illuminate/pipeline/Pipeline.php(103): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Laravel\Lumen\Http\Request))
#10 /home/smartmpsco/public_html/cust/rms/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(423): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#11 /home/smartmpsco/public_html/cust/rms/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(172): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#12 /home/smartmpsco/public_html/cust/rms/api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(109): Laravel\Lumen\Application->dispatch(NULL)
#13 /home/smartmpsco/public_html/cust/rms/api/public/index.php(28): Laravel\Lumen\Application->run()
#14 {main}  

```

My Code to parse the token.

` $aToken =  $aConfig->parser()->parse(Crypt::decrypt($req->header('x-token')));`

can you help me ?

**Comment by Ocramius** [comment]
I can see this in your trace:

> json_decode('ZXlKMGVYQWlPaUp

You aren't decoding JSON there?

**Comment by amrishkakadiya** [comment]
> I can see this in your trace:
> json_decode('ZXlKMGVYQWlPaUp
> You aren't decoding JSON there?
> […](#)
>

no, its working in other server(nginx). I am passing raw string to parse which is stated in Documentation.

**Comment by Ocramius** [comment]
I can clearly see this:

```
#1 /home/smartmpsco/public_html/cust/rms/api/vendor/lcobucci/jwt/src/Token/Parser.php(67): Lcobucci\JWT\Encoding\JoseEncoder->jsonDecode('ZXlKMGVYQWlPaUp...')
```

That means that gibberish is passed to JSON decoding logic :-)

The exception is just the symptom.

Locking this thread: please do write an integration test about your use-case, before reporting a new issue with a reproducible scenario.

**Comment by lcobucci** [comment]
Is it possible that a bug in libsodium is the thing to blame here? That's the only explanation I have for it to fail on specific servers only. @Slamdunk have you experienced something like this?

**Comment by lcobucci** [comment]
@amrishkakadiya can you run the following code on both the new and old servers:

```php
<?php

$headers = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9';

var_dump(
    base64_decode(strtr($headers, '-_', '+/'), true), 
    sodium_base642bin($headers, 7, '') 
);
```

**Comment by amrishkakadiya** [comment]
Dedicated server response
`string(27) "{"typ":"JWT","alg":"HS256"}" string(27) "{"typ":"JWT","alg":"HS256"}"`

and Shared Server respone
`Call to undefined function App\\Http\\Middleware\\sodium_base642bin()`

So is it because of Sodium extenstion?

**Comment by lcobucci** [comment]
`ext-sodium` is required extension (as stated in the `composer.json`). Please make sure it is installed.

**Comment by amrishkakadiya** [comment]
> `ext-sodium` is required extension (as stated in the `composer.json`). Please make sure it is installed.

Is there any way to install in Shared Hosting usign Cpanel without terminal access?

**Comment by lcobucci** [comment]
@amrishkakadiya sorry but I can't help you with that, it's been ages since I last used shared hosting. Try contacting them.

It's also important to note that copying `vendor` files from one place to another is a bit error-prone. Try to use `composer install` to detect any potential incompatibility.

**Comment by lcobucci** [comment]
Locking here as we discovered it's not related to the lib itself but the environment in which the library runs.
