### ISSUE TITLE
Getting Unauthenticated when update to lcobucci/jwt 4.1

### ISSUE THREAD

**Issue by trancongminh132** [lcobucci/jwt#687]
Hello, currently, I upgraded to Laravel 8, Passport 10.
When I try to call oauth/token, it return bearer_token ok,
But when I use that bearer token that to call some api, it always return
"Unauthenticated"
Could someone help me?
Thank you!

Surprisingly when I was using it locally it worked fine, but when doing it through the server it didn't work smoothly. Have you experienced the same thing as me?

**Comment by lcobucci** [comment]
@trancongminh132 that's rather strange. However, I have very little knowledge on what can be the cause of that for I'm no Laravel user.

If things work locally and don't work remotely, it might be worth checking if the configuration is similar and/or reading the generated logs (if there's anything useful there).

The changes in 4.1.x should not break applications so I'm quite interested in knowing the results of your investigation to make sure that we didn't ship something wrong.

**Comment by lcobucci** [comment]
No response from the OP... closing here, we can reopen when necessary.
