### ISSUE TITLE
JWT intro usage

### ISSUE THREAD

**Issue by killua-eu** [lcobucci/jwt#69]
Hi,

Started playing with jwt and for various reasons ended up writing a selfcontained demo of using jwt+cookies as a drop-in replacement for session auth (see https://gist.github.com/killua-eu/d45ac9a7c8073f24876b). Luis, would you mind looking at the code and pointing out obvious fallacies + best practices according to your experience? I'd like to post the code somewhere more public to make things easier with jwt. 

thanks, Pavel

p.s.: Should you at some point want a demo dir for jwt, feel free to tweak the gist and use it as you see fit.

**Comment by Ocramius** [comment]
@killua-eu you can check https://github.com/Ocramius/PSR7Session for a reference implementation on which I, @malukenho and @lcobucci worked on together in August.

**Comment by lcobucci** [comment]
@killua-eu sorry about this humongous delay...

I'm a bit lost on this issue - and you probably already solved this - but how are you using JWT (or was planning to use)? Do you still need any help? Maybe we could use [gitter](https://gitter.im/lcobucci/jwt) to discuss this a bit more.

> p.s.: Should you at some point want a demo dir for jwt, feel free to tweak the gist and use it as you see fit.

I don't know exactly what would be the best thing to about that... I mean, JWT are not meant just for auth and I really to don't to make people think that there's only ONE right way to use JWTs. There are different ways to use those tokens and with creativity we can do a lot of cool things...

**Comment by lcobucci** [comment]
Will close this as "invalid" and if needed we can reopen it and discuss a bit more 😉
