### ISSUE TITLE
parseing claim exp not correct

### ISSUE THREAD

**Issue by Xieyongmin** [lcobucci/jwt#691]
example jwt:
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTQwNjcyNDEsIm5iZiI6MTYxNDA2NzI0MSwiZXhwIjoxNjE0MDcwODQxLCJkYXRhIjoiYTozOntzOjQ6XCJ1dWlkXCI7czozMjpcImVmMmM0ZjBiOGNiNDQzNzk4ZTJmZTIzNWViMjgyMzc3XCI7czo3OlwidW5pb25pZFwiO3M6Mjg6XCJvcEJvbXc2WGEzdkRVY2xZOWhMVWNfT2llekgwXCI7czoxNDpcIm9mZmljaWFsT3BlbklkXCI7czoxOlwiMVwiO30ifQ.JqoOq0a6_fXkYMT7xaGP36ZPTnCTgybRey3DnJmCc-o

version: 3.4.5

File src/Parser.php method **convertItems**

parsed result like this, timezone is not correct.  
```["exp"]=>
object(DateTimeImmutable)#50 (3) {
	["date"]=>
	string(26) "2021-02-23 09:00:41.000000"
	["timezone_type"]=>
	int(1)
	["timezone"]=>
	string(6) "+00:00"
}
```

if fixed to like this :
```
$dateTime = new DateTimeImmutable();
        foreach (RegisteredClaims::DATE_CLAIMS as $name) {
            if (! array_key_exists($name, $items)) {
                continue;
            }

            $items[$name] = $dateTime->setTimestamp((int) $items[$name]);
      }
```

then parsed result is correct:
```
["exp"]=>
object(DateTimeImmutable)#51 (3) {
	["date"]=>
	string(26) "2021-02-23 17:00:41.000000"
	["timezone_type"]=>
	int(3)
	["timezone"]=>
	string(13) "Asia/Shanghai"
}
```

**Comment by Ocramius** [comment]
In your token (from the above post):

```
"exp": 1614070841,
```

That is indeed correct when represented as `2021-02-23 09:00:41.000000+00:00`.

Converting the `DateTimeImmutable` to your local timezone is up to your app.
