### ISSUE TITLE
Can version v3.4.x support PHP8? 

### ISSUE THREAD

**Issue by Yurunsoft** [lcobucci/jwt#695]

**Comment by lcobucci** [comment]
@Yurunsoft no, v3.x is closed for security only fixes. v4 is the way forward.

There were similar issues where I elaborate more but, in a nutshell, the v3.x API already supports 2 major PHP versions and doesn't support things we value on a library.

I'd, therefore, recommend you to migrate your code to v4. Alternatively, feel free to fork the repository and apply the necessary changes.
