### ISSUE TITLE
issue with creating custom token on PHP 8.0 when using Firebase admin SDK

### ISSUE THREAD

**Issue by WaseemRakab** [lcobucci/jwt#697]
when trying to create custom token i get the following error when running in php 8.
```
It was not possible to parse your key, reason:
```
i looked into the source code, went over to ```vendor/lcobucci/jwt/src/Signer/OpenSSL.php``` file
at method "validateKey($key)"

the key parameter now is of type OpenSSLAsymmetricKey object (in php 9 and above).
the code below needs to be changed.
if you look into this link
https://www.php.net/manual/en/function.openssl-pkey-get-private.php into the changelog.

this method returns an object of OpenSSLAsymmetricKey instead of a resource type.
thanks

**Comment by lcobucci** [comment]
@WaseemRakab it looks like you're using v3.x series on an incompatible platform - perhaps you didn't install it via composer as our documentation says?

v3.x **won't support** PHP 8.0 -  and it's closed for security patches only. Upgrade to v4 to have PHP 8 support 👍
