### ISSUE TITLE
3.4.x composer.json says ^7.0 but JsonException is a 7.3 feature

### ISSUE THREAD

**Issue by ergomesh** [lcobucci/jwt#698]
[JsonException](https://www.php.net/manual/en/class.jsonexception.php) is only since 7.3 so your composer.json is wrong and the library out the box only supports 7.3 and above Probably won't support 5.6 either but not tested.

https://github.com/lcobucci/jwt/blob/3.4.x/composer.json#L20

Several other spots but here is reference to JsonException

https://github.com/lcobucci/jwt/blob/3.4.x/src/Parsing/Decoder.php#L10

**Comment by Ocramius** [comment]
https://github.com/lcobucci/jwt/blob/511629a54465e89a31d3d7e4cf0935feab8b14c1/compat/json-exception-polyfill.php#L3-L4
