### ISSUE TITLE
openssl_pkey_get_details() expects parameter 1 to be resource, boolean given

### ISSUE THREAD

**Issue by KylePalko** [lcobucci/jwt#70]
This code from the readme:

```
use Lcobucci\JWT\Builder;
use Lcobucci\JWT\Signer\Hmac\Sha256;

$signer = new Sha256();

$token = (new Builder())->setIssuer('http://example.com') // Configures the issuer (iss claim)
                        ->setAudience('http://example.org') // Configures the audience (aud claim)
                        ->setId('4f1g23a12aa', true) // Configures the id (jti claim), replicating as a header item
                        ->setIssuedAt(time()) // Configures the time that the token was issue (iat claim)
                        ->setNotBefore(time() + 60) // Configures the time that the token can be used (nbf claim)
                        ->setExpiration(time() + 3600) // Configures the expiration time of the token (exp claim)
                        ->set('uid', 1) // Configures a new claim, called "uid"
                        ->sign($signer, 'testing') // creates a signature using "testing" as key
                        ->getToken(); // Retrieves the generated token
```

Is causing this exception:

```
ErrorException: openssl_pkey_get_details() expects parameter 1 to be resource, boolean given
```

I have the extension installed / enabled. Is this a problem on my end? I am requiring version 3.1 of lcobucci/jwt.

Thanks for writing this library. Besides this issue it has been great!

**Comment by Ocramius** [comment]
@KylePalko was this supposed to be closed? What was the resolution?

**Comment by KylePalko** [comment]
I didn't want to blast my ignorance all over the internet, but since you asked ;) I was including the RSA namespace version of the Sha256 object. When I copy/pasted I must have left the RSA version in from my previous tests.

So, the solution was to pay attention and include the correct Sha256 object, hah.

Thanks for your concern!

**Comment by Ocramius** [comment]
@KylePalko no shame in that, this is just for the records/for others having a similar issue.

**Comment by KylePalko** [comment]
Great idea, thanks!
