### ISSUE TITLE
SodiumBase64Polyfill and libsodium differance

### ISSUE THREAD

**Issue by eugene-borovov** [lcobucci/jwt#701]
The polyfill and the library handle incorrectly encoded base64url differently. I tested on docker `php:7.4-cli-alpine`

Test code:
```php
$enc = SodiumBase64Polyfill::bin2base64($data, SodiumBase64Polyfill::SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING);
$enc .= 'foo'; // add suffix to make string invalid base64

$dec1 = base64_decode(strtr($enc, '-_', '+/'), true);
var_dump($dec1);

try {
    $dec2 = \Lcobucci\JWT\SodiumBase64Polyfill::base642binFallback(
        $enc,
        SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING,
        ''
    );
    var_dump($dec2);
} catch (\Exception $e) {
    var_dump($e->getMessage());
}

try {
    $dec3 = sodium_base642bin($enc, SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING, '');
    var_dump($dec3);
} catch (\SodiumException $e) {
    var_dump($e->getMessage());
}
```

Test results:

`$data = 'a'`
```
bool(false)
string(71) "Error while decoding from Base64Url, invalid base64 characters detected"
string(21) "invalid base64 string"
```

`$data = 'ab'`
```
string(4) "ab�"
string(4) "ab�"
string(21) "invalid base64 string"
```

`$data = 'abc'`
```
string(5) "abc~�"
string(5) "abc~�"
string(5) "abc~�"
```

`$data = 'abcd'`
```
bool(false)
string(71) "Error while decoding from Base64Url, invalid base64 characters detected"
string(21) "invalid base64 string"
```

`$data = 'abcde'`
```
string(7) "abcde�"
string(7) "abcde�"
string(21) "invalid base64 string"
```

`$data = 'abcdef'`
```
string(8) "abcdef~�"
string(8) "abcdef~�"
string(8) "abcdef~�"
```

I encountered this behavior in the [thephpleague/oauth2-server](https://github.com/thephpleague/oauth2-server/issues/1197#issue-823919509) library.

**Comment by lcobucci** [comment]
@eugene-borovov we were aware that libsodium is stricter and more accurate than PHP's `base64_decode`.

Reproducing libsodium's behaviour would lead to a more complicated code that probably won't give us much. So, that's a trade-off we're willing to accept - given we can't really control the version of the underlying C lib.

Therefore, I consider this a non-issue.

**Comment by eugene-borovov** [comment]
Thank you for the clarification.
