### ISSUE TITLE
Not possible to parse your key

### ISSUE THREAD

**Issue by michelvermeulen** [lcobucci/jwt#703]
Hey there,

I keep bumping into an issue using this to create a client_id for Apple Sign In:

Here's the code:

```
$applePrivateKeyFilePath = app_path('AuthKey_XXXXX.p8'); //private key, downloaded from developers.apple.com
    // if (file_exists($applePrivateKeyFilePath)) {
    //   $clientSecretPrepared = 'file://' . $applePrivateKeyFilePath;
    // }
    $signer = new Sha256();
    $privateKey = new Key('file://' . $applePrivateKeyFilePath);

    $time = new DateTimeImmutable();
    $expiry = new DateTimeImmutable();
    $interval = new DateInterval('P1D');
    $expiry->add($interval);
    $appleTeamId = "XXXXX";
    $client_id = "com.xxxxxx.web";
    $keyId = "XXXXXXX";
    $token = (new Builder())->issuedBy($appleTeamId) // Configures the issuer (iss claim)
      ->withHeader('kid', $keyId)
      ->withHeader('type', 'JWT')
      ->withHeader('alg', 'ES256')
      ->issuedAt($time)
      ->expiresAt($expiry)
      ->setAudience('https://appleid.apple.com')
      ->setSubject($client_id)
      ->getToken($signer, $privateKey); // Retrieves the generated token

    return (string) $token;
```

And I get this error:

`It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line
`

Any idea what I'm doing wrong? Thanks!

**Comment by lcobucci** [comment]
Your key must be in the PEM format, it seems you're using a key in the p8 format.

Check https://github.com/lcobucci/jwt/issues/244

**Comment by michelvermeulen** [comment]
Thanks @lcobucci I commented on the thread, I'm having another issue converting the key.

**Comment by michelvermeulen** [comment]
It's weird though, I'm using this package with https://socialiteproviders.com/Apple/ which is supposed to handle Apple callback seamlessly, and in my case it really doesn't work :/
