### ISSUE TITLE
Why PHP 7.4 and 8.* ?!

### ISSUE THREAD

**Issue by shehi** [lcobucci/jwt#705]
This package is a polyfill. So why its `composer.json` lists following PHP version requirement in https://github.com/lcobucci/jwt/blob/4.1.2/composer.json#L20:

```
"require": {
    "php": "^7.4 || ^8.0",
    ....
}
```

It should specifically require only PHP <7.3. It is completely unnecessary for PHP >=7.3

**Comment by SvenRtbg** [comment]
I'm confused. You are referring to the main lib composer.json, and this lib doesn't do polyfilling.

Anyways, even polyfills have to account for the fact that they may be included in situations where their work isn't required, but that does not mean you can simply exclude them by having "php < 7.3" as the requirement. This will not skip installation, but fail for everything.

**Comment by lcobucci** [comment]
@shehi I think you created this in the wrong repository. Closing for now.

**Comment by shehi** [comment]
Nah, I just did incomplete research. The problem is `JsonException` which should be extracted to a separate polyfill component so that we could exclude it in our projects, via composer's `replace` field.

Should I create proper ticket which recommends the code refactoring - namely, extraction of the polyfill into a separate component?

**Comment by lcobucci** [comment]
No, that polyfill only exists for the old versions. Users are encouraged to use v4.x where that class doesn't exist.

**Comment by lcobucci** [comment]
Just to make it explicit, you're talking about https://github.com/lcobucci/jwt/tree/3.4.x/compat and it was a conscious decision to have them in the repository instead of increasing the amount of dependencies. As you can see there, the class is only defined if it doesn't already exist (PHP 7.3+).

v3.x supports PHP 5.6+, hence the need there.

**Comment by shehi** [comment]
Yea, but it sucks little bit, coz v4.1.x requires PHP 7.4, whereas that specific polyfill isn't needed starting PHP 7.3. My project is PHP 7.3 one: so don't want to have v3.x of this lib, and can't use v4.1.x either. Can't use v4.0.0 either, coz it's buggy: only alpha fits the bill but it doesn't have https://github.com/lcobucci/jwt/tree/4.2.x/src/Encoding folder. 
![image](https://user-images.githubusercontent.com/653569/111663611-48ac3900-8811-11eb-9ef2-517a945140c6.png)

Ah well, thanks. :)

**Comment by lcobucci** [comment]
> whereas that specific polyfill isn't needed starting PHP 7.3

Let me just understand where you're coming from... are you concerned about the impact of running an opcacheable `if` statement on the beginning of your request cycle? The class definition is skipped on PHP 7.3+, so is this your concern?

**Comment by lcobucci** [comment]
> Can't use v4.0.0 either, coz it's buggy: only alpha fits the bill but it doesn't have https://github.com/lcobucci/jwt/tree/4.2.x/src/Encoding folder.

It's not buggy, your composer configuration is likely to be wrong ([minimum-stability](https://getcomposer.org/doc/04-schema.md#minimum-stability) isn't set to `stable`). Composer is only following your instructions 😄

**Comment by shehi** [comment]
> > whereas that specific polyfill isn't needed starting PHP 7.3
> 
> Let me just understand where you're coming from... are you concerned about the impact of running an opcacheable `if` statement on the beginning of your request cycle? The class definition is skipped on PHP 7.3+, so is this your concern?

Don't worry about it: I just hate seeing weak warnings all over my code just because IDE detects "two implementations of JsonException". Nothing big, will live with that.

**Comment by pluk77** [comment]
> 
> 
> > Can't use v4.0.0 either, coz it's buggy: only alpha fits the bill but it doesn't have https://github.com/lcobucci/jwt/tree/4.2.x/src/Encoding folder.
> 
> It's not buggy, your composer configuration is likely to be wrong ([minimum-stability](https://getcomposer.org/doc/04-schema.md#minimum-stability) isn't set to `stable`). Composer is only following your instructions 😄

I think the statement here is that Alpha3 has a PHP dependency of ^7.2 while all subsequent version have ^7.4.

https://packagist.org/packages/lcobucci/jwt#4.0.0-alpha3


As a PHP 7.3 user, you are then left with the option to run a buggy alpha release of 4.0 or use the 3.4 branch.

@shehi How did you resolve this? Which version are you running on your PHP 7.3 install?

**Comment by Ocramius** [comment]
If you are on 7.3, `lcobucci/jwt:^3` works just fine.

I endorse upgrading to PHP 7.4 though: the jump from 7.3 to 7.4 is quite
minimal.

**Comment by shehi** [comment]
> If you are on 7.3, `lcobucci/jwt:^3` works just fine. I endorse upgrading to PHP 7.4 though: the jump from 7.3 to 7.4 is quite minimal.

Not a generally applicable sentiment I am afraid. In most production-grade projects, just stating what you stated there and upgrading would be ludacrous :) It never happens no matter how much we want that. Higher ups always come up with "we gotta test everything with this language upgrade, it is such a huge task ... blah blah blah". Arghhh, anyway.

**Comment by Ocramius** [comment]
You should indeed be testing: that is what allows for smoother upgrades.

If that has been neglected, it will get worse over time: we've all been
there.

**Comment by lcobucci** [comment]
That's also why we ship a forward compatibility layer in v3.4. Once you adopt that, migrating to v4 should be 100% headache free - allowing you to focus on upgrading language.
