### ISSUE TITLE
Catch exceptions when token is being injected

### ISSUE THREAD

**Issue by mnicolas80** [lcobucci/jwt#71]
Is there any way to catch specific or multiple exceptions in case of token injection?

In details, when I change a generated token, the lib throws exceptions like:
- RuntimeException in Decoder.php line 36
- OutOfBoundsException in Token.php line 110

As a result, I cannot proceed to token validation.

Thank you

**Comment by lcobucci** [comment]
@mnicolas80 the `RuntimeException` happens when there's an error when parsing the JSON content and the `OutOfBoundException` when you're trying to get a header that don't exists.

What do you mean by "when I change a generated token"? Can you provide more details about that - maybe your code?

**Comment by mnicolas80** [comment]
@lcobucci thank you for your quick response!

I am writing a API that a part of it is the JWT authentication. Any authorized user has his token that must be sent to any future request. Everything worked successfully, till the moment I changed(injected/removed) some characters of the generated token.

I am using the following method to validate the token:
``
$token = (new Parser())->parse((string) $givenToken);
``
where the injected token is the ``$givenToken`` in base64 format.
I believe, that due to the invalid/injected token, the decoder cannot decode and process the information.
I tried to add some try/catch code in my code, but it couldn't work...

Part of errors (from Laravel 5.2 debugger):
``
RuntimeException in Decoder.php line 36:
Error while decoding to JSON: Malformed UTF-8 characters, possibly incorrectly encoded

in Decoder.php line 36
at Decoder->jsonDecode('{"typ":"JWT̍M����H����Y̌�LL�XH�') in Parser.php line 112
at Parser->parseHeader('eyJ0eXAiOiJKV1QUzI1NiIsImp0aSI6IjRmMWcyM2ExMmFhIn0') in Parser.php line 60
``
Reproduce steps:
1) generate a token
2) pass the token for validation
3) try to inject the token by adding or removing characters to token string

Thank you

**Comment by lcobucci** [comment]
If you add/remove characters from the `$givenToken` your base64Url string will not be correct and you'll have parsing errors. To catch them just put the `Parser#parse()` call in a try/catch block and expect the `\RuntimeException`:

```php
try {
    $token = (new Parser())->parse((string) $givenToken); 
} catch (\RuntimeException $e) {
    echo 'Hey, we have something here!';
}
```

You're probably trying to catch that exception without the "use" statement or the "\", then PHP will try to find an exception with that name within the namespace that your class was declared. You can learn more on http://php.net/manual/en/language.namespaces.php

**Comment by mnicolas80** [comment]
Now, my new try/catch code is the following and works:
```
       try {
            // Parse token
            $token = (new Parser())->parse((string) $givenToken); // Parses from a string

            // Validate data
            $data = new ValidationData(); // It will use the current time to validate (iat, nbf and exp)
            $data->setIssuer($token->getClaim('iss'));
            $data->setAudience($token->getClaim('aud'));
            $data->setId($token->getHeader('jti'));

            if (!$token->validate($data)) {
                return false;
            }
        } catch(\RunException $e) {
            return false;
        } catch(\OutOfBoundsException $e) {
            return false;
        }
```

Thank you @lcobucci for your help!

**Comment by lcobucci** [comment]
@mnicolas80 your validation is a bit naive since you're using the data (`iss`, `aud` and `jti`) stored in the token to validate it.
The ideia is to use information you know to make sure that the token has them. Check the RFC to understand better the meaning of each claim. 

It's also important to verify the token signature, take a look at the README ;-).

I'll close this issue, if you need something else related to this please re-open.
