### ISSUE TITLE
Feature request: PHP8 support for 3.4.5 while updating other libraries?

### ISSUE THREAD

**Issue by Richard87** [lcobucci/jwt#714]
Hi!

Would it be possible to support PHP8 in ^3.4.5? 

I'm trying to update to PHP8, and https://github.com/steverhoades/oauth2-openid-connect-server is a blocker (latest release only support jwt ^3.3.0...

https://github.com/steverhoades/oauth2-openid-connect-server/issues/34

**Comment by lcobucci** [comment]
We decided not to support PHP 8 on v3.x because of maintenance costs and the fact that v3.x is not actively maintained anymore (open for security fixes only).

Libs should support 3.4 and 4.0 to allow users to use PHP 5.6-8.0 support.

I can help you with the migration process, if needed.

**Comment by Richard87** [comment]
Thanks for answering so fast :)
