### ISSUE TITLE
Http code status 0

### ISSUE THREAD

**Issue by halie412** [lcobucci/jwt#715]
Hi i´m trying to use this library but i get http status code zero int(0) and no success on sending notifications...

I´m using:
Centos: 8 (clean installation only for this)
PHP: 7.2.24
CURL: 7.61.1
CURL with http2: yes
Apache: 2.4.37
OpenSSL: 1.1.1c

My App are on production, and already can send push notifications using binary protocol so i know than the Device Token are fine and also App are fine

var_dump($response) => bool(false)
var_dump($httpcode) => int(0)

This is my script:

$team_id = 'MYTEAM_IN_APPLE';
$key_id = 'KEY_FROM_APPLE';
$device_token = "AN_WORKING_TESTED_CODE";
$apns_topic = 'com.myapp';

$private_key_pem_str = '
-----BEGIN PRIVATE KEY-----
ALLCERTIFICATE
-----END PRIVATE KEY-----
';

//// start of original code
function base64url_encode($binary_data) { return strtr(rtrim(base64_encode($binary_data), '='), '+/', '-_'); }

function apns_jwt_token($team_id, $key_id, $private_key_pem_str) {
    if (! function_exists('openssl_get_md_methods') || ! in_array('sha256', openssl_get_md_methods())) throw new Exception('Requires openssl with sha256 support');

    $private_key = openssl_pkey_get_private($private_key_pem_str);
    if (! $private_key) throw new Exception('Cannot decode private key');

    $msg = base64url_encode(json_encode([ 'alg' => 'ES256', 'kid' => $key_id ])) . '.' . base64url_encode(json_encode([ 'iss' => $team_id, 'iat' => time() ]));
    openssl_sign($msg, $der, $private_key, 'sha256');

    // DER unpacking from https://github.com/firebase/php-jwt
    $components = [];
    $pos = 0;
    $size = strlen($der);
    while ($pos < $size) {
        $constructed = (ord($der[$pos]) >> 5) & 0x01;
        $type = ord($der[$pos++]) & 0x1f;
        $len = ord($der[$pos++]);
        if ($len & 0x80) {
            $n = $len & 0x1f;
            $len = 0;
            while ($n-- && $pos < $size) $len = ($len << 8) | ord($der[$pos++]);
        }

        if ($type == 0x03) {
            $pos++;
            $components[] = substr($der, $pos, $len - 1);
            $pos += $len - 1;
        } else if (! $constructed) {
            $components[] = substr($der, $pos, $len);
            $pos += $len;
        }
    }
    foreach ($components as &$c) $c = str_pad(ltrim($c, "\x00"), 32, "\x00", STR_PAD_LEFT);

    return $msg . '.' . base64url_encode(implode('', $components));
}

$token = apns_jwt_token($team_id, $key_id, $private_key_pem_str);

$payloadArray['aps'] = [
    'alert' => [
      'title' => "Dev.To Push Notification", // title of the notification
      'body' => "Visit SamAuto.nl for more awesome scripts", // content/body of the notification
    ],
    'sound' => 'default',
    'badge' => 1
  ];
  
  $payloadJSON = json_encode($payloadArray);
  
  $url = "https://api.push.apple.com:443/3/device/$device_token";
  $ch = curl_init($url);
  
  curl_setopt($ch, CURLOPT_POSTFIELDS, $payloadJSON);
  curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_2);
  curl_setopt($ch, CURLOPT_HTTPHEADER, ["Authorization: Bearer $token","apns-topic: $apns_topic"]);
  curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
  curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
  $response = curl_exec($ch);
  $httpcode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
  
  // On successful response you should get true in the response and a status code of 200
  // A list of responses and status codes is available at
  // https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/TheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH107-SW1

//// end of original code

echo 'response <br><br>';
  var_dump($response);
echo '<hr>';
echo 'httpcode <br><br>';
  var_dump($httpcode);
echo '<hr>';

**Comment by lcobucci** [comment]
I'm not sure what you are trying to accomplish here, however that snippet does not use this library. Perhaps you opened the issue in the wrong repo?

Closing here as invalid.

**Comment by halie412** [comment]
Excuse me, you're right... Have a great day! and thanks for fast reply!
