### ISSUE TITLE
Composer should only suggest ext-sodium

### ISSUE THREAD

**Issue by mantis** [lcobucci/jwt#717]
Composer.json currently has:

`
"require": { 
  "ext-sodium": "*",
}
`

This seems to mean that the package will not install if sodium is missing from PHP.

However, a polyfill was added to provide a fallback if sodium was missing. Therefore should the requirement for ext-sodium not be moved to "suggests" ?  This would allow a user to install the package when sodium is not in PHP, and to use the polyfill ?

**Comment by Ocramius** [comment]
Considering that the polyfill is additional code to ease a migration,
dropping it from the next minor would be best (making sodium mandatory)

**Comment by Slamdunk** [comment]
Polyfill was added only for base64 functions, that are missing in older libsodium versions.
The require is mandatory for EdDSA signer however, read more about the decision here: https://github.com/lcobucci/jwt/pull/605#issuecomment-745591616

**Comment by Ocramius** [comment]
Closing as per @Slamdunk's comment: until we bump requirements, the polyfill should stay then.

**Comment by lcobucci** [comment]
The polyfill was only added because the required function is only available in an specific version of libsodium (the C lib), which we don't have control over.

I hope to be able to remove the polyfill - eventually.

**Comment by mantis** [comment]
Also, I raised this as I thought that sodium was **just** a PECL extension - so it seemed a really strange requirement - hadn't realised that it was shipping with core php's (as of 7.2).

So yea, agree that this should be closed :) - sry

**Comment by ejseguinte** [comment]
I understand that this is an old and closed issue. I was just curious would there be a work around for using this library without the extension. It seems like RedHat has removed the extension and is no longer properly supporting it. It can be installed from another repo but due to customer constraints we cannot use that repo at this time.

**Comment by SvenRtbg** [comment]
You can always fork and modify old versions as you like, I guess.

**Comment by lcobucci** [comment]
@ejseguinte you can knowingly ignore the requirement during installation with something like `--ignore-platform-req=ext-sodium` or force composer to consider the extension as installed via https://getcomposer.org/doc/06-config.md#platform.

Either way should work fine for base64url encoding. You won't be able to use EdDSA, though.

**Comment by ejseguinte** [comment]
I will have to try that. Thank you for the quick reply.

**Comment by ejseguinte** [comment]
Did want to let you know, that did work for my use case. Thank you.
