### ISSUE TITLE
New Function Names aren't "natural" and easy to understand

### ISSUE THREAD

**Issue by hparadiz** [lcobucci/jwt#718]
I don't understand why you broke backwards compatibility for this????

I need to find the "issuer". I hit Ctrl + F and type in "issuer". Nothing comes up. Now it's "issuedBy"???? Why???? None of this makes any sense. setIssuer was more natural English. Your library is now harder to teach to people.

**Comment by lcobucci** [comment]
This name convention has been reviewed by other people who agreed it's more natural for the pattern being applied and that it reveals the intention behind the claim names - not to mention avoiding the `set` prefix. 

Thanks for sharing your opinion. We respectfully disagree and won't be changing it.

**Comment by hparadiz** [comment]
![image](https://user-images.githubusercontent.com/195216/114213084-4748ca80-98fe-11eb-80d9-8b156d806fab.png)
You might as well just type hint DateTimeImmutable here because throwing a deprecated warning on modern systems where even deprecation errors bubble up and throw alerts in front of people's faces cause problems. So I honestly had to extend your classes and override it cause it's wasting too many resources checking every single timestamp for DateTimeImmutable object during run time.

Your library is the only one that broke my tests in an entire year. Not exactly very nice for a JWT library for an RFC that literally never changes. What new features were added or are you just shuffling things around????

**Comment by lcobucci** [comment]
These and other questions are answered by the documentation - even the deprecations.

**Comment by lcobucci** [comment]
It would be great if you could show a bit of appreciation, or at least respect, to the result of the work you get for free.

Also, nobody is forcing you to update the library - or even use it. Feel free to maintain a fork of the old v3.x stuff with the naming structure you prefer, I'm glad to know this lib helped you so far and happy to part ways. 

I'm gonna lock this thread because it's not going anywhere 👍
