### ISSUE TITLE
Importance of Validation Constraints

### ISSUE THREAD

**Issue by maikonmatheus** [lcobucci/jwt#721]
The Documentation brings setValidationConstraints as Customization but, in fact, it is mandatory. In addition, not using the Constraint\SignedWith is a huge security vulnerability, because when unused, any token created with any key becomes valid. At a minimum, this should be highlighted in the documentation. I even suggest making Constraint\SignedWith mandatory.

**Comment by Slamdunk** [comment]
I agree: https://github.com/lcobucci/jwt/pull/680

**Comment by Ocramius** [comment]
Closing as duplicate of #680 - agree as well that there should be a more "hardened" API in this lib for these inconsistent details of JWT that are also why the entire PASETO shitstorm started :-)

**Comment by maikonmatheus** [comment]
I understand the wish to keep the API without the proposed restriction. But I still beliveing in the beneftis of include a highlighted description about the importance of SignedWith constraint in the docs. ;)

**Comment by Ocramius** [comment]
Please do send a patch, if you think it can be improved there as a start 👍
