### ISSUE TITLE
Target [Lcobucci\JWT\Configuration] is not instantiable

### ISSUE THREAD

**Issue by fylzero** [lcobucci/jwt#726]
Target [Lcobucci\JWT\Configuration] is not instantiable while building [App\Http\Controllers\Auth\SSOController]

Using the basic recommended setup from the upgrade docs and receiving this error.  Not sure what is causing this.  Running Laravel 8 on Valet, PHP 7.4.  Any help is appreciated.

```
<?php

namespace App\Http\Controllers;

use Lcobucci\JWT\Configuration;

final class SSOController
{
    private Configuration $config;

    public function __construct(Configuration $config)
    {
        $this->config = $config;
    }
}
```

**Comment by lcobucci** [comment]
@fylzero sorry but I'm no Laravel user. I'd recommend you to check the docs there to try and understand the issue. 

It sounds like it expects you to define the configuration object on the DI container so it can be used by your controller.

**Comment by lcobucci** [comment]
I'll close the issue as it's not related to this lib.
