### ISSUE TITLE
Add `claims` method to Token interface

### ISSUE THREAD

**Issue by carusogabriel** [lcobucci/jwt#753]
Hey there!

While upgrading to the latest version of this library, we noticed that https://github.com/lcobucci/jwt/blob/4.2.x/src/Token.php does not have a `claims` method declared there. But, its implementations have it:

- https://github.com/lcobucci/jwt/blob/207955dfbce28b4fbdc12367fbccf9546c66eb2d/src/UnencryptedToken.php#L11-L14
- https://github.com/lcobucci/jwt/blob/207955dfbce28b4fbdc12367fbccf9546c66eb2d/src/Token/Plain.php#L32-L35

Can we declare that method in the interface? This should also help to fix static analyzers warnings like:

```
phpstan: Call to an undefined method Lcobucci\JWT\Token::claims().
```

Thanks!

**Comment by carusogabriel** [comment]
My bad, duplicated from #611

**Comment by lcobucci** [comment]
> My bad

That's alright 😄
