### ISSUE TITLE
Missing info in doc: what is '$container' ?

### ISSUE THREAD

**Issue by realtebo** [lcobucci/jwt#755]
About this page

https://lcobucci-jwt.readthedocs.io/en/stable/parsing-tokens/

It starts with

    $config = $container->get(Configuration::class);

But there is not explanation of how to instantiate the container.

**Comment by lcobucci** [comment]
@realtebo there's a note on every page saying:

> The examples here fetch the configuration object from a **hypothetical dependency injection container**. You can create it in the same script or require it from a different file. It basically depends on how your system is bootstrapped.

So, the `$container` is an example of how you would integrate with modern frameworks that use containers. If you don't have a container, then you create the configuration object manually.

Feel free to send a PR clarifying this further :+1:

**Comment by realtebo** [comment]
First thanks for reply. I am here asking for more doc because I am not able to understand. Sorry. I have laravel and I was not able to use dependency injection with your package . Again, thanks, but did is not enough. Also. If I had no framework, I can create configuration.... How?

Scarica Outlook per Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by lcobucci** [comment]
@realtebo the page you sent has a link to the configuration documentation:

> To parse a token you must create a new parser (easier when using the [configuration object](https://lcobucci-jwt.readthedocs.io/en/stable/configuration/)) and ask it to parse a string

Alternatively, you may click on the `Usage -> Configuration` session of the docs:

![image](https://user-images.githubusercontent.com/201963/121089491-85237b80-c7e7-11eb-8ee8-5e4f4f3c13c4.png)

I understand that the navigation/content of the docs might be confusing. So, please, do send a PR if you think you have an idea on how to improve. Things are always obvious in my mind but I understand it's not obvious to everybody - I just can't find something better now :smile:

**Comment by realtebo** [comment]
I still need help, sorry

I must decode a JWT I receive, but it's not created from my app

Header is

```
{
  "typ": "JWT",
  "alg": "RS256",
  "x5t": "nOo3ZDrODXEK1jKWhXslHR_KXEg",
  "kid": "nOo3ZDrODXEK1jKWhXslHR_KXEg"
}
```

I simply need to do something like 

     $payload = $something->getPayloadFromJwtString($jwt);

I do not need validations of any kind.

**Comment by realtebo** [comment]
I resolved !!

    use Lcobucci\JWT\Configuration;

    $configuration = Configuration::forUnsecuredSigner();
    $token = $configuration->parser()->parse( $my_received_token_string);


Thanks !!!!!!!!!!!!
