### ISSUE TITLE
Cannot instantiate interface 'Builder'

### ISSUE THREAD

**Issue by Dongmo880** [lcobucci/jwt#756]
this is related to token generation using the lcobocci/jwt package.
"Cannot instantiate interface 'Builder'"

this is my code.

<?php

namespace App\Controller;
use Lcobucci\JWT\Builder;
use Lcobucci\JWT\Signer\Hmac\Sha256;
use Lcobucci\JWT\Signer\Key;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Cookie;
use Symfony\Component\Routing\Annotation\Route;

class IndexController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index()
    {
        $username = $this->getUser()->getUsername();
        $token = (new Builder())
            ->withClaim('mercure', ['subscribe' => [sprintf("/%s", $username)]])
            ->getToken(
                new Sha256(),
                new Key($this->getParameter('mercure_secret_key'))
            )
        ;

        $response =  $this->render('index/index.html.twig', [
            'controller_name' => 'IndexController',
        ]);

        $response->headers->setCookie(
            new Cookie(
                'mercureAuthorization',
                $token,
                (new \DateTime())
                    ->add(new \DateInterval('PT2H')),
                '/.well-known/mercure',
                null,
                false,
                true,
                false,
                'strict'
            )
        );

        return $response;
    }
}

**Comment by Ocramius** [comment]
Closing: `Builder` is indeed an interface, not a class.

Please read the docs at https://github.com/lcobucci/jwt/tree/4.1.4/docs

**Comment by Dongmo880** [comment]
> Clôture : `Builder`est bien une interface, pas une classe.
> 
> Veuillez lire les documents sur https://github.com/lcobucci/jwt/tree/4.1.4/docs

thank you

**Comment by Dongmo880** [comment]
Hello to all 

please i come back again with my problem i followed the documentation but i still have the same error 

please help me

**Comment by Ocramius** [comment]
@Dongmo880 check if you are running `4.x` (I linked the docs for `4.1.4`) or `3.x` (for which docs can be found at https://github.com/lcobucci/jwt/tree/3.4.5/docs )
