### ISSUE TITLE
Cannot mock classes marked final

### ISSUE THREAD

**Issue by ol1s** [lcobucci/jwt#761]
@lcobucci I know that this is 100% intentional and that you probably have many reasons why you do not want others to extend your classes 😁 

But......does every class really need to be marked as `final` !!!

This is especially painful when trying to mock these classes in my unit tests as I get the following error from PHPUnit:

```
The class is marked final and its methods cannot be replaced
```

Any chance you could consider removing the `final` declarations?

**Comment by lcobucci** [comment]
@ol1s I'll convert this into a discussion because it makes more sense 👍
