### ISSUE TITLE
Unencrypted Token API Not Visible In Parsed Result

### ISSUE THREAD

**Issue by XedinUnknown** [lcobucci/jwt#775]
## The Problem
[`Parser#parse()`][] [returns][1] an [`UnencryptedToken`][], but only guarantees a [`Token`][]. This makes it impossible to retrieve essential information, such as claims, from the parsed result, because it is not declared in the guaranteed result's interface.

[`Parser#parse()`]: https://github.com/lcobucci/jwt/blob/4.2.x/src/Token/Parser.php#L29
[`Token`]: https://github.com/lcobucci/jwt/blob/4.2.x/src/Token.php
[`UnencryptedToken`]: https://github.com/lcobucci/jwt/blob/4.2.x/src/UnencryptedToken.php
[1]: https://github.com/lcobucci/jwt/blob/4.2.x/src/Token/Parser.php#L35

**Comment by t0mmy742** [comment]
It was already discussed on #186 and #203

> Since parse() deals with untrusted data, users are supposed to verify if they have the expected type of token

You can try something like this:

```PHP
$token = $this->parser->parse($jwt);

if (!$token instanceof UnencryptedToken) {
    throw new \RuntimeException('Invalid token');
}
```

You can use your own exception of course

**Comment by lcobucci** [comment]
@t0mmy742 thanks for the help here :+1:

@XedinUnknown as said above, this is a forward compatibility layer.
It was added to avoid having to break the API when implementing encryption.

#759 is adding a high-level API that will always return an unencrypted token, and we'll soon be shipping it.

**Comment by XedinUnknown** [comment]
@t0mmy742, that's exactly what I did. It's fine, but sub-optimal of course.

@lcobucci, thanks, understood 👍
