### ISSUE TITLE
InMemory cannot implement Lcobucci

### ISSUE THREAD

**Issue by betysam55** [lcobucci/jwt#781]
`{
    "message": "Lcobucci\\JWT\\Signer\\Key\\InMemory cannot implement Lcobucci\\JWT\\Signer\\Key - it is not an interface",
"exception": "Symfony\\Component\\Debug\\Exception\\FatalErrorException",
    "file": "/Users/sam/Desktop/easy/easy-ethiopia-web/vendor/lcobucci/jwt/src/Signer/Key/InMemory.php",
    "line": 14,
    "trace": []
}`

can any one  help

**Comment by lcobucci** [comment]
@betysam55 which version of `lcobucci/jwt` you have installed and how did you install it?
