### ISSUE TITLE
libsodium requirement issue

### ISSUE THREAD

**Issue by sarfarazsavvy** [lcobucci/jwt#783]
Hello Community,
we are facing issue, this package requires libsodium previously ext-libsodium was available to install in php 7.2 but in php 7.4 libsodium is not installing. is there any way to ignore libsodium is there any alternative way.

**Comment by SvenRtbg** [comment]
Libsodium is supposed to be bundled with PHP since 7.2, so you have to fix the issue with whatever your PHP provider has done to make it a problem.

The extension provides modern cryptographic functions and is essential to this library.
-- 
Viele Grüße
Sven Rautenberg

**Comment by lcobucci** [comment]
@sarfarazsavvy you can use composer's `--ignore-platform-req=ext-sodium` (https://getcomposer.org/doc/03-cli.md#install-i) and check if you can run things but you'd essentially be on your own.

The recommended approach is to have the extension installed (that depends on the OS you have).
