### ISSUE TITLE
`claims()` missing in Token interface

### ISSUE THREAD

**Issue by Patrick-Remy** [lcobucci/jwt#786]
The Token interface of 4.x does not include the `claims()` method, as suggested to use in migration guide https://lcobucci-jwt.readthedocs.io/en/latest/upgrading/#use-the-new-token-api

It only includes the `headers()` method.

https://github.com/lcobucci/jwt/blob/52c43b2ba8aa30efcc3a38b7aa7d0c4f560dfe19/src/Token.php#L11-L14

**Comment by SvenRtbg** [comment]
`claims()` is present in the `UnencryptedToken` interface, and I think it may make sense because you'd probably be unable to access them if the token is encrypted.

But what is your case here? Do you have any code that may illustrate what you want to do?

**Comment by Patrick-Remy** [comment]
My static analysis engine pointed out
```
$token = $jwtConfig->parser()->parse($jwtString);
$foo = $token->claims()->get('bar'); // Undefined method 'claims'
```

As `parse()` method does return just a `Token`.

**Comment by lcobucci** [comment]
@Patrick-Remy your static analysis is reminding you to validate user input.

Parse will potentially return encrypted tokens in the future, so you need to make sure that what you received as literal string is what your application expects.

**Comment by lcobucci** [comment]
Closing as invalid as per my comment
