### ISSUE TITLE
Signers are not marked as implementing the Signer interface

### ISSUE THREAD

**Issue by jbuchmann-castor** [lcobucci/jwt#795]
The various Signers (src/Signer/Hmac/Sha256.php, src/Signer/Ecdsa/Sha512.php, etc) are not marked as implementing the Signer interface (Lcobucci\JWT\Singer) even though they actually do. This is not a functional problem, but it can cause IDEs (and humans) to be confused.

Would you like a PR to address this?

**Comment by Slamdunk** [comment]
All the classes you mention extend a different abstract class, which in turn implement the `Signer` interface.

Most IDE I know of correctly recognize interface inheritance, check yours if needed.

**Comment by Ocramius** [comment]
Closing: Github also allows navigating the inheritance tree (use CTRL+CLICK), and correctly recognizes that signers implement `Signer`.
