### ISSUE TITLE
can we invalidate a token when user logout?

### ISSUE THREAD

**Issue by devkiran** [lcobucci/jwt#80]
I have been using this library for the last 2 week. Its working perfectly fine. I have one question about how can we invalidate a token we already created when user logout ? 

Thanks

**Comment by Ocramius** [comment]
The only way to do that is to assign identifiers to each token, and then track those ids and mark them as "logged-out". Otherwise, deleting the token from the client system is the quickest solution.

**Comment by Art4** [comment]
You could also reset the key for the signer, but this will invalidate every token for the user.

**Comment by lcobucci** [comment]
As @Ocramius said, the token revocation is the easiest way to deal with that.
Read https://auth0.com/blog/2015/03/10/blacklist-json-web-token-api-keys/ and https://dadario.com.br/revoking-json-web-tokens/ to get some ideas.

I like to use a cache engine to stored the "blacklisted" tokens, setting the expiration of the item on the cache with the same date of the token, this way your revoked tokens list would never get soooo huge.

**Comment by devkiran** [comment]
Okay. I will try above said methods.
