### ISSUE TITLE
PHP 7 Compatibility

### ISSUE THREAD

**Issue by dangaffey** [lcobucci/jwt#800]
It looks like now that lcboucci/clock's release version 2.1 is requiring PHP 8, that this projects dependencies of ^2.0 breaks PHP 7 compatibility because it pulls in version 2.1.  This has broken my usage of a dependent library 'LexikJWTAuthenticationBundle' with use of PHP 7.4

**Comment by Ocramius** [comment]
Heyo,

`composer update` will pick a set of compatible dependencies: you probably did run `composer update` on a system running PHP 8, then deployed with that set of dependencies on PHP 7.
