### ISSUE TITLE
Feature Request - Add a way to reset permittedFor on Builder

### ISSUE THREAD

**Issue by donatj** [lcobucci/jwt#802]
It would be very helpful to add a way to empty `permittedFor` audience claim on Builder. 

I'm in process of upgrading from 3.2 to latest and our code constructs a rough token before passing it and adding the final touches which in some places involves changing the audience. 

Calling `$builder->permittedFor('foo.com')` currently appends it to the default audience rather just having `foo.com`

It would be great if there were just a `resetPermittedFor()` or some such call? I would have done a PR but I'm not sure the preferred way to label it.

**Comment by lcobucci** [comment]
@donatj have you thought about cloning the builder to be passed around before doing the final touches? That should achieve the isolation you're looking for, without having to deal with state control.

**Comment by donatj** [comment]
The problem isn't that I'm accidentally using the same instance of a builder in two places, which a clone would help.

The problem is I have a function that uses the builder to set a handful of defaults, including an audience, and then hands that builder on for you to change. Even if I cloned it, the default audience is already set. 

I know it sounds like I should just _not_ set the default audience in the builder, but this description is a oversimplification and there's a lot more to it.

A `withoutClaim( string $name )` seems like an easy win, though I suppose changing the `BuilderInterface` might be considered a breaking change? 

If you decide this is a will-not-fix I totally understand. 😉

**Comment by Ocramius** [comment]
>  changing the `BuilderInterface` might be considered a breaking change?

Very much so - not possible to add methods there.

**Comment by lcobucci** [comment]
> I know it sounds like I should just not set the default audience in the builder, but this description is a oversimplification and there's a lot more to it.

@donatj your case sounds a lot like an edge-case. I'd like to understand it better before discussing changes to the library. Based on what you're describing, it sounds like you have a library that wraps this one. Is this correct?
