### ISSUE TITLE
Deprecated Notice spamming logs

### ISSUE THREAD

**Issue by Rikcon** [lcobucci/jwt#807]
Hello, first of all i want to thank author of this package and all involved people for their great work !

Issue:
My cloudwatch logs got spammed with 
`NOTICE: PHP message: PHP Deprecated:  Return type of Lcobucci\JWT\Claim\Basic::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/medcenter/webapp/vendor/lcobucci/jwt/src/Claim/Basic.php on line 61`

I'm running PHP 8.1 in docker ( i don't think docker is relevant but anyway ).

Thanks in advance !

**Comment by lcobucci** [comment]
It seems you are running version 3.x on an incompatible php version. Please upgrade to v4.x if you want to run it on php 8.0+
