### ISSUE TITLE
Encoder converts 'aud' string to array

### ISSUE THREAD

**Issue by nschmoyer** [lcobucci/jwt#808]
After upgrading to the newest version of this library, the 'aud' portion of my payload is being converted to an array, rather than keeping the single item as a string. Per the standard, an array is optional for single audiences. Unfortunately, the client I am trying to pass my token to is now resulting in an error because of an "invalid audience".

Is it possible to maintain the string type when passing 'aud' in the payload?

Example code:

```
$payload = [
    'iss' => 'abc',
    'sub' => 'username',
    'aud' => 'api.example.com',
    'iat' => $time,
    'exp' => $time + 3600,
];

$token = $this->encoder->encode($payload);
```

And when I decode it on jwt.io, it looks something like this:

```
{
  "iat": 1639607652,
  "exp": 1639611252,
  "sub": "username",
  "iss": "abc",
  "aud": [
    "api.example.com"
  ]
}
```

Instead of the following, which is the required format for my specifc use case:

```
{
  "iat": 1639607652,
  "exp": 1639611252,
  "sub": "username",
  "iss": "abc",
  "aud": "api.example.com"
}
```

Downgrading to the 3.4 version is not an option as it does not support PHP 8.

**Comment by lcobucci** [comment]
@nschmoyer your snippets don't show how are you creating your builder object. However, since v4 we have the concept of formatters and there's one which unifies the audiences.

Check the named constructors in to see what can help you https://github.com/lcobucci/jwt/blob/4.2.x/src/Encoding/ChainedFormatter.php

**Comment by shriram-terrificminds** [comment]
@lcobucci In the documentation we can see

> By default, we provide formatters that:
>
> - unify the audience claim, making sure we use strings when there's only one item in that claim

So I assumed this would be done automatically if only a single string is passed. But even I'm getting the output in a similar format as @nschmoyer where the aud claim has an array with single string present in it.
```php
"aud" => array:1 [
        0 => "mystring"
      ]
```

Attaching a snippet of my Builder object:
```php
$algorithm = new Sha256();
$signingKey = InMemory::plainText(random_bytes(32));
$tokenBuilder = (new Builder(new JoseEncoder(), ChainedFormatter::default()));
$token = $tokenBuilder
            ->issuedBy('<iss>')
            ->permittedFor('mystring')
            ->identifiedBy('unique-id')
            ->relatedTo('<sub>')
            ->getToken($algorithm, $signingKey);
```

Could an example be shared to understand how to use the `ClaimsFormatter.php` to implement this (as I did found it difficult to understand it from the official documentation) OR could this handling be done within the `permittedFor()` in `Lcobucci\JWT\Token\Builder.php` itself

**Comment by lcobucci** [comment]
@shriram-terrificminds I think there's a misunderstanding (probably because of the docs 😄)

Did you get that array from the encoded string or from the Token object?

I'm asking because it's expected from the formatter to kick in when we're encoding to JSON, which means the `aud` claim will always be represented as an array on the token object.

**Comment by shriram-terrificminds** [comment]
Thanks @lcobucci for reaching back. You are correct, I was able to verify this from https://jwt.io/. Sorry for the troubles.

**Comment by lcobucci** [comment]
> Thanks @lcobucci for reaching back. You are correct, I was able to verify this from https://jwt.io/. Sorry for the troubles.

@shriram-terrificminds no worries, glad that everything is fine 👍
