### ISSUE TITLE
Version 4.0.x is not supported for 7.4 because underlyin dependency lcobucci/clock needed php 8.0

### ISSUE THREAD

**Issue by dolwindavis** [lcobucci/jwt#816]
version 4.0.x is not supported for php.7.4 since the dependency lcobucci/clock is using version 2.2.x.you need to update composer.json file and add "lcobucci/clock": "^2.0.0" instead of "lcobucci/clock": "^2.0"

**Comment by lcobucci** [comment]
Composer resolves the correct dependency version depending on the php version you are using.

If you analyse the lock file in this repository, you will confirm the behaviour.

Are you perhaps manipulating the lock with php 8.0? If that's the case, you will get the newest version of clock.

Make sure you run composer using the php version you have on production or to use the [platform property](https://getcomposer.org/doc/06-config.md#platform) to override composer's php version detection.

**Comment by lcobucci** [comment]
Closing here as per my comment.
