### ISSUE TITLE
Deploying to Google App Engine fails  : ext-sodium is required by lcobucci/jwt

### ISSUE THREAD

**Issue by dev-mansonthomas** [lcobucci/jwt#821]
Hi,
I'm upgrading from 3.x to 4.1.5 and when I'm deploying on Google App Engine (PHP 7.4), it fails because of a Sodium Dependency required by lcobucci/jwt.

I didn't see it documented here : https://lcobucci-jwt.readthedocs.io/en/latest/installation/

```
ERROR: (gcloud.app.deploy) Error Response: [9] Cloud build 1542b104-2b7f-4837-b151-b747c0ae0fd5 status: FAILURE
You are using the deprecated option "--no-suggest". It has no effect and will break in Composer 3.
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - Root composer.json requires PHP extension ext-sodium * but it is missing from your system. Install or enable PHP's sodium extension.
  Problem 2
    - lcobucci/jwt is locked to version 4.1.5 and an update of this package was not requested.
    - lcobucci/jwt 4.1.5 requires ext-sodium * -> it is missing from your system. Install or enable PHP's sodium extension.
  Problem 3
    - lcobucci/jwt 4.1.5 requires ext-sodium * -> it is missing from your system. Install or enable PHP's sodium extension.
    - kreait/firebase-tokens 2.2.0 requires lcobucci/jwt ^4.1.5 -> satisfiable by lcobucci/jwt[4.1.5].
    - kreait/firebase-tokens is locked to version 2.2.0 and an update of this package was not requested.

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

```

Is it possible to have the 4.x running without sodium extension ? 
Or should I stick to the 3.x ?  any risk of doing so ?

**Comment by Ocramius** [comment]
`ext-sodium` is bundled with newer PHP versions since a while (7.2 onwards - see https://wiki.php.net/rfc/libsodium ).

It is reasonable to expect it to be installed: contact GCP support and ask for help there.

**Comment by dev-mansonthomas** [comment]
well, so the answer is I'm stuck with 3.x because I don't see GCP making a move for me...
(but I'll open a ticket to GCP support)

**Comment by Ocramius** [comment]
Have you checked custom runtimes? I used to run similar runtime replacements on Heroku, and it is akin to providing a `Dockerfile` to build a base image/substrate for installation.

**Comment by dev-mansonthomas** [comment]
I've started with that custom runtime, but it was painful (at that time at least), and honestly, I'm volunteering developing the project, I don't have much time for that. 
So I'll stay on 3.x for now.

Thanks for trying to help though :) 

I don't have access to google support, so I've posted on Google Community:
https://www.googlecloudcommunity.com/gc/Serverless/Google-App-Engine-to-support-Sodium-Extension-required-for/m-p/395094#M231

**Comment by SvenRtbg** [comment]
It seems like Google App Engine only scans the root composer.json for required extensions, but libsodium definitly is listed as being available and activated by default: https://cloud.google.com/appengine/docs/flexible/php/runtime#using_php_extensions

**Comment by Ocramius** [comment]
So adding `ext-sodium` to your root `composer.json` could do the trick :)

**Comment by dev-mansonthomas** [comment]
I'm missed it on the Extension page.
I've tried to set the ext-sodium:"*" in composer.json + php.ini, but this didn't worked.

    "require": {
        "php": "^7.4",
        "ext-PDO": "*",
        "ext-bz2": "*",
        "ext-json": "*",
        "ext-zip": "*",
        "ext-sodium": "*",

**Comment by lcobucci** [comment]
> Is it possible to have the 4.x running without sodium extension ?

It's possible but not desirable - we have a polyfill for the critical functions but you won't be able to use EdDSA.
You can use the `config.platform` setting in your composer.json file: https://getcomposer.org/doc/06-config.md#platform

**Comment by dev-mansonthomas** [comment]
Thanks @lcobucci ,

Adding the platform statement apparently helped deploying (I've retried twice, with and without, and for Google App Engine it's required to have the platform for sodium extension to work), here is the full working composer.json :


```
{
    "name": "rcq/redcrossquest",
    "description": "French Red Cross yearly fundraising rest backend",
    "keywords": ["RedCross","CroixRouge","FundRaising"],
    "homepage": "https://github.com/dev-mansonthomas/RedCrossQuest",
    "license": "GPL-3.0-or-later",
    "type": "project",
    "authors": [
        {
            "name": "Thomas Manson",
            "email": "cv@mansonthomas.com",
            "homepage": "http://www.mansonthomas.com/"
        }
    ],
    "require": {
        "php": "^7.4",
        "ext-PDO": "*",
        "ext-bz2": "*",
        "ext-json": "*",
        "ext-zip": "*",
        "ext-sodium": "*",
        "doctrine/annotations": "^1.13.2",
        "egulias/email-validator": "3.1.2",
        "google/apiclient": "^v2.12.1",
        "google/cloud": "^v0.175.0",
        "google/protobuf": "^v3.19.4",
        "google/recaptcha": "^1.2.4",
        "grpc/grpc": "^1.42.0",
        "guzzlehttp/guzzle": "^7.4.1",
        "jolicode/slack-php-api": "^v4.4.1",
        "kreait/firebase-php": "^6.1.0",
        "lcobucci/jwt": "^4.1.5",
        "nesbot/carbon": "^2.56.0",
        "nyholm/psr7": "^1.5.0",
        "php-di/php-di": "^6.3.5",
        "phpmailer/phpmailer": "^v6.5.3",
        "ramsey/uuid": "^4.2.3",
        "robmorgan/phinx": "^0.12.10",
        "sendgrid/sendgrid": "^7.11.4",
        "slim/php-view": "^3.1.0",
        "slim/psr7": "^1.3.0",
        "slim/slim": "^4.9.0",
        "symfony/http-client": "^v5.3.14",
        "symfony/validator": "^v5.4.3",
        "zircote/swagger-php": "^4.2.8"
    },
    "autoload": {
      "psr-4": {"RedCrossQuest\\": "src/"}
    },

    "config": {
        "optimize-autoloader": true,
        "classmap-authoritative": true,
        "sort-packages": true,
        "preferred-install": {
            "*": "dist"
        },
        "platform": {
            "php": "7.4",
            "ext-sodium": "7.4"
        }
    }
}

```
