### ISSUE TITLE
"message": "Key cannot be empty",

### ISSUE THREAD

**Issue by bekee** [lcobucci/jwt#834]
"message": "Key cannot be empty",
    "exception": "Lcobucci\\JWT\\Signer\\InvalidKeyProvided",
    "file": "/var/www/html/vendor/lcobucci/jwt/src/Signer/InvalidKeyProvided.php",
    "line": 23,

This error occurs on laravel 8.61 and laravel passport 10.3.

Any solution to this problem?

**Comment by bekee** [comment]
@Slamdunk 
Please any resolution to this?

**Comment by Slamdunk** [comment]
I guess you are using `dev-master` version of this library, since https://github.com/lcobucci/jwt/pull/833 has yet to be released.

As the error message says, you either use a non-empty key or explicitly instantiate an empty key with `InMemory::empty()`.

**Comment by Ocramius** [comment]
This change is intentional - see #833

**Comment by bekee** [comment]
This was caused by laravel passport requiring the dev-master branch, I had to fix it at "lcobucci/jwt": "4.1.5" and it's all fine now

**Comment by Ocramius** [comment]
Note that you will still need to switch to a non-empty key, as the next upgrade will require that for security reasons.

**Comment by SvenRtbg** [comment]
Any version of laravel/passport that I can see in that version range on Github is requiring `"lcobucci/jwt": "^3.4|^4.0"`, so this most likely is not broken because of Laravel.

**Comment by Ocramius** [comment]
@SvenRtbg the branch name is `4.2.x`, which will be picked up when running with `minimum-stability: dev` during `composer update`
