### ISSUE TITLE
InMemory cannot implement Lcobucci\JWT\Signer\Key

### ISSUE THREAD

**Issue by anshulCoder** [lcobucci/jwt#838]
Getting this error in latest version please help
`
Fatal error: Lcobucci\JWT\Signer\Key\InMemory cannot implement Lcobucci\JWT\Signer\Key - it is not an interface in /var/www/wmd/current/wmdcore-nightly/vendor/lcobucci/jwt/src/Signer/Key/InMemory.php on line 14`

Laravel version: 8.x
JWT: 4.1.5
php: 7.4.28

**Comment by Ocramius** [comment]
`Lcobucci\JWT\Signer\Key` **is** an interface:

https://github.com/lcobucci/jwt/blob/00c96d7e4b36c8c72c0c818db0945ab13e9d9658/src/Signer/Key.php#L4-L6

Can you check your `composer.lock` for installed packages?

**Comment by anshulCoder** [comment]
<img width="956" alt="Screenshot 2022-04-25 at 8 03 29 PM" src="https://user-images.githubusercontent.com/35722795/165110996-77210bc2-4a9a-49d9-bd7d-b6daeef2a5ff.png">
u mean something like this?

**Comment by Ocramius** [comment]
I wonder if autoloading is broken? What's the file location for `Lcobucci\JWT\Signer\Key`, and what are its contents?

**Comment by lcobucci** [comment]
@driesvints do you now if passport or laravel is declaring any class alias or overriding the class definition?

Only Laravel users are reporting this...

**Comment by lcobucci** [comment]
https://github.com/lcobucci/jwt/issues/781 and https://github.com/lcobucci/jwt/discussions/782 were reported in the past but had no input from the reporter.

**Comment by driesvints** [comment]
Hmm no not that I know of. We use `Lcobucci\JWT\Configuration` and `Lcobucci\JWT\Parser` but that's about it.

**Comment by anshulCoder** [comment]
> I wonder if autoloading is broken? What's the file location for `Lcobucci\JWT\Signer\Key`, and what are its contents?

<img width="1295" alt="Screenshot 2022-04-26 at 12 09 59 AM" src="https://user-images.githubusercontent.com/35722795/165153062-f3bc9040-bef6-4356-9cd1-9c896d94e15d.png">
its same under vendor/lcobucci/jwt/src/Signer/Key.php
and content is also same as in screenshot above

P.S. the yellow line on 'Key' indicates duplicate file indication in another project in same folder so ignore that

**Comment by lcobucci** [comment]
@anshulCoder would you please verify what your system says in runtime? Having something like this on the `InMemory.php` file should do the trick as it would be executed when autoloading it =)

```php
$ref = new \ReflectionClass(\Lcobucci\JWT\Signer\Key::class);
var_dump(
    $ref->isInterface(),
    $ref->getFileName()
);
die();
```

**Comment by anshulCoder** [comment]
I did above code in "InMemory.php" and "Configuration.php" but getting same error as soon as I send a request

**Comment by lcobucci** [comment]
Did you completely replace the contents of `InMemory.php`?

**Comment by anshulCoder** [comment]
nope, let me try that

**Comment by anshulCoder** [comment]
it return this
`bool(false) string(76) "/var/www/wmd/current/wmdcore-nightly/vendor/auth0/php-jwt/src/Signer/Key.php"`
now I understood that file is loading from auth0 instead

**Comment by lcobucci** [comment]
There's your culprit :smile: 

https://github.com/auth0/php-jwt seems to be an old fork of my lib... do you need it? Maybe `composer why auth0/php-jwt` can help you understand which package requires it.

**Comment by lcobucci** [comment]
Closing here then :+1:

**Comment by anshulCoder** [comment]
> There's your culprit 😄
> 
> https://github.com/auth0/php-jwt seems to be an old fork of my lib... do you need it? Maybe `composer why auth0/php-jwt` can help you understand which package requires it.

I guess its being used by `auth0/auth0-php  7.9.2  requires  auth0/php-jwt (3.3.4)  `

**Comment by lcobucci** [comment]
Indeed, upgrading that package to v8 should solve the incompatibility =)
