### ISSUE TITLE
PHP 8.1.2 issue

### ISSUE THREAD

**Issue by tajribastudio** [lcobucci/jwt#843]
Root composer.json requires lcobucci/jwt ^3.4.5 -> satisfiable by lcobucci/jwt[3.4.5, 3.4.6, 3.4.x-dev].
    - lcobucci/jwt[3.4.5, ..., 3.4.x-dev] require php ^5.6 || ^7.0 -> your php version (8.1.2) does not satisfy that requirement.

**Comment by Ocramius** [comment]
You need to upgrade to `lcobucci/jwt:^4`
