### ISSUE TITLE
Validation returning false.

### ISSUE THREAD

**Issue by TheConsciousness** [lcobucci/jwt#85]
**SOLVED: Read below**

I'm not sure what I am doing wrong, as I've tried this with the example provided by the page and it was still returning false.

`use Lcobucci\JWT\Builder;
use Lcobucci\JWT\Signer\Hmac\Sha256;
use Lcobucci\JWT\ValidationData;

$signer = new Sha256();

$token = (new Builder())->setIssuer('http://example.com') // Configures the issuer (iss claim)
                        ->setAudience('http://example.com') // Configures the audience (aud claim)
                        ->setId('b2lk2hj3j4', true) // Configures the id (jti claim), replicating as a header item
                        ->setIssuedAt(time()) // Configures the time that the token was issue (iat claim)
                        ->setNotBefore(time() + 60) // Configures the time that the token can be used (nbf claim)
                        ->setExpiration(time() + 3600) // Configures the expiration time of the token (exp claim)
                        ->set('uid', 1) // Configures a new claim, called "uid"
						->set('user', 'jordan')
                        ->sign($signer, 'secretKey') // creates a signature using "testing" as key
                        ->getToken(); // Retrieves the generated token

$token->getHeaders(); // Retrieves the token headers
$token->getClaims(); // Retrieves the token claims

header("Authorization: Bearer " . $token);

echo $token->getHeader('jti');
echo $token->getClaim('iss'); 
echo $token->getClaim('uid'); 

echo $token; // The string representation of the object is a JWT string (pretty easy, right?)

$data = new ValidationData(); // It will use the current time to validate (iat, nbf and exp)
$data->setIssuer('http://example.com');
$data->setAudience('http://example.com');
$data->setId('b2lk2hj3j4');

var_dump($token->validate($data)); // true, because validation information is equals to data contained on the token`

Setting custom claims causes PHP errors to be thrown.

**The reason this was not validating is because ValidationData.php is not set up to handle custom claims. You must edit the file to your liking.**

**Comment by lcobucci** [comment]
@TheConsciousness you shouldn't edit the file to validate non public claims (that feature is not available on v3.x). We're working on a new validation system so you'll also be able to handle those claims but it will only be available for v4.
