### ISSUE TITLE
Cannot find function name getSigner()

### ISSUE THREAD

**Issue by WaylandZhang** [lcobucci/jwt#86]
When I try to use ```Lcobucci\JWT\Signer\Ecdsa\Sha256``` and run the code
 ```$signer = new Sha256();```  it returns error

`Fatal error: Call to undefined method Mdanter\Ecc\EccFactory::getSigner() .. in /jwt/src/Signer/Ecdsa.php on line 49`

Any ideas?

**Comment by lcobucci** [comment]
Humm that's not cool, it seems they changed they API breaking BC. Will see if that is the case.

Which branch are you using?

**Comment by lcobucci** [comment]
I just saw their code and it's all fine, did you installed the suggested dependency (`mdanter/ecc`)?

**Comment by WaylandZhang** [comment]
Hi @lcobucci 

I'm using your **master** branch, and **mdanter/ecc** installed as well, version `"mdanter/ecc" : "~0.1"`

**Comment by lcobucci** [comment]
Can you check on your `composer.lock` file and make sure that you have the same version as required by the tests: https://github.com/lcobucci/jwt/blob/master/composer.json#L30

BTW in production you should use the stable versions since the API on `master` will change a lot for v4.0

**Comment by WaylandZhang** [comment]
Hmm, I tried phpcc `0.3.0` then it seems my Mac doesn't have **php gpm**, I'll try later and let you know :)

**Comment by WaylandZhang** [comment]
Confirmed, it was my local Mac setup, after enabling **php5-gmp** it works just fine..
A great framework, thanks a lot!

**Comment by lcobucci** [comment]
Awesome, thanks 😄
