### ISSUE TITLE
It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line

### ISSUE THREAD

**Issue by reddinan** [lcobucci/jwt#860]
lcobucci/jwt  4.1.5

Getting the following issue when attempting to create a token

`
It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line
`

Here is a class that can be used to recreate this issue

```
<?php

namespace Domain\MetaBase;

use Lcobucci\JWT\Configuration;
use Lcobucci\JWT\Signer\Key\InMemory;
use Lcobucci\JWT\Signer\Rsa\Sha256;

class Metabase
{
    public function generateToken(): string
    {
        $metabaseSiteUrl = "https://potato.metabaseapp.com";
        $metabaseSecretKey = "1690e6bf587bc61b5cdd3897c143291caa48779cc7abef104abf952fec6e8d4a";
        $now = new \DateTimeImmutable();
        $config = Configuration::forSymmetricSigner(new Sha256(), InMemory::plainText($metabaseSecretKey));
        $token = $config->builder()
            ->issuedBy($metabaseSiteUrl)
            ->withHeader('iss', $metabaseSiteUrl)
            ->permittedFor($metabaseSiteUrl)
            ->issuedAt($now)
            ->canOnlyBeUsedAfter($now->modify('+1 minute'))
            ->expiresAt($now->modify('+1 hour'))
            ->withClaim('resource', ['question' => 15])

            //METABASE resource (question, card, dashboard)
            ->withClaim('params', ['cod_usuario' => 1001])

            //METABASE params variables metabase
            ->getToken($config->signer(), $config->signingKey());

        return $metabaseSiteUrl . "/embed/question/" . $token->toString() . "#bordered=true&titled=true";
    }
}
```

Is this a bug in your software or is there something wrong with my config? Thanks

**Comment by SvenRtbg** [comment]
You are importing `Lcobucci\JWT\Signer\Rsa\Sha256`, and if I remember correctly, or go by the name, this is used for asymmetric signing. The error message itself is complaining about the asymmetric key string not containing a starting boundary line like `---------- begin private key ----------` (and similarly the end of the key should have an end line much like the same). These lines are created automatically if you properly create a PEM key pair to be used.

However your code suggests you want to do symmetric signing, so probably you should import `Lcobucci\JWT\Signer\Hmac\Sha256` instead.

**Comment by reddinan** [comment]
Thanks that was exactly the issue much appreciated.
