### ISSUE TITLE
Faile to signe token

### ISSUE THREAD

**Issue by Ciloe** [lcobucci/jwt#863]
Hi, since this commit : https://github.com/lcobucci/jwt/commit/b4290ef2b4d58ef0dd1fabc5bf8a35307f5c04d7
we are enabled to signe token using lexik. I fixed my composer with the previous commit version : https://github.com/lcobucci/jwt/commit/fe3029559cf8ac99ac9475a44b39ccb8123efa4c

Now it's working fine. So, I think, you have breaking change.

My previous composer : 

```
"lexik/jwt-authentication-bundle": "2.x-dev",
```

Now my composer : 

```
"lcobucci/jwt": "4.2.x-dev#b4290ef2b4d58ef0dd1fabc5bf8a35307f5c04d7",
"lexik/jwt-authentication-bundle": "2.x-dev",
```

I generated tockens with : 

`openssl genrsa -out private.pem -aes256 512`
`openssl rsa -in private.pem -outform PEM -pubout -out public.pem`

**Comment by lcobucci** [comment]
We do have a minor BC-break for 4.2.0 that only affects people using insecure keys (https://github.com/lcobucci/jwt/pull/855), which is your case.

This will be released soon (and properly documented on the release notes). You are able to keep issuing tokens with the implementation that doesn't validate the key size but the recommendation is to follow the RFC and using a key with a least 2048 bits.
