### ISSUE TITLE
How to work with externally-provided insufficient public key in 4.2.x?

### ISSUE THREAD

**Issue by SvenRtbg** [lcobucci/jwt#881]
I don't want to add oil into the burning #877 because I agree with the reasoning.
However I encountered a situation now that maybe isn't fully considered.

I'm using this library inside an OpenIdConnect client. JWT tokens are created externally, and also the public keys that I should use to validate the token are provided externally. I am only validating what was given to me.

Given that the external OIDC service is incorrectly set up, using shorter than recommended public keys, I am unable to validate the token using 4.2.x because the exception is informing me that the key is too short.

I can of course switch from `Lcobucci\JWT\Signer\Rsa\Sha256` to `Lcobucci\JWT\Signer\Rsa\UnsafeSha256`, which disables length checks, but I think it would be a bad idea removing that last resort in an upcoming version.

How to resolve such a problem? I understand using services with improper or insecure configuration should be avoided, but sometimes there might be no way around it. The argument for introducing the length check of secrets is to prevent insecure implementation when creating tokens. Consuming them however is a bit different IMHO.

**Comment by Slamdunk** [comment]
~This is indeed a valid argument.~

~@lcobucci We may check key length requirement only on `sign()`, then allow any key length for `verify()`~

Redacted, see below

**Comment by Ocramius** [comment]
> but I think it would be a bad idea removing that last resort in an upcoming version.

You mean the fact that it is `@internal` (and therefore not to be used)?

What about using a custom signer, at that point, putting a clear declaration of "I take full responsibility of talking in an unsafe way with an unsafe system"?

**Comment by Slamdunk** [comment]
> You mean the fact that it is `@internal` (and therefore not to be used)?

I think he was referring to `Unsafe*` alternative classes.

> What about using a custom signer, at that point, putting a clear declaration of "I take full responsibility of talking in an unsafe way with an unsafe system"?

You are right: requiring RFC valid keys for `sign()` isn't enough, `verify()` needs to comply too in order for signature to be effectively safe.

**Comment by SvenRtbg** [comment]
Just to rephrase my understanding of your response: You consider a system that is handing out tokens using keys shorter than the recommended minimum length to be "broken by configuration/choice" and don't want to support even reading/validating them in a future 5.0+ version.

That'd be completely fine by me. Currently I am dealing with some broken unit tests that were using shorter keys probably for  convenience reasons, the real world service seems to be working.

The conclusion then is: Anyone who has to deal with such systems stays on 4.x until their broken system gets better keys.

**Comment by Ocramius** [comment]
> The conclusion then is: Anyone who has to deal with such systems stays on 4.x until their broken system gets better keys.

Seems reasonable, yes :+1:

**Comment by Slamdunk** [comment]
> recommended minimum length

I'd like to emphasize that these lengths are not recommended, they are mandatory.
The RFC uses the word *MUST*: https://www.rfc-editor.org/rfc/rfc7518.html#section-3.2

**Comment by lcobucci** [comment]
> The conclusion then is: Anyone who has to deal with such systems stays on 4.x until their broken system gets better keys.

They can upgrade and maintain the non-compliant algorithm implementation on their system too.
