### ISSUE TITLE
Class 'Lcobucci\JWT\Builder' not found

### ISSUE THREAD

**Issue by david-byng** [lcobucci/jwt#89]
It looks like the latest patch release breaks BC with the new `$config->createBuilder()` syntax.

**Comment by lcobucci** [comment]
It indeed breaks. As you can see on https://github.com/lcobucci/jwt/blob/master/CONTRIBUTING.md#branches `master` is meant for v4 (release that we're currently working).

If you want stable versions you should use the v3.x tags 😄

**Comment by lcobucci** [comment]
And it was not a release, was just an update on the `master` branch.

**Comment by lcobucci** [comment]
Will close this as invalid please let us know if have further problems 😉 .
