### ISSUE TITLE
Encrypting token strings

### ISSUE THREAD

**Issue by geggleto** [lcobucci/jwt#90]
Would you be willing to include a method of encrypting the output of getToken?

I created a basic wrapper around Halite and your JWT package [https://github.com/geggleto/securejwt] ... but I think it should probably be optional in your package.

Just wondering if this is something you might be willing to accept a PR for.

**Comment by moderndeveloperllc** [comment]
@geggleto One issue I see with your implementation is that you are encrypting the the entire token and just outputting the results. At that point it's not longer a JWT. You would need to follow the [examples in the RFC](https://tools.ietf.org/html/rfc7519#page-26) to encrypt and display in the required format. [Nested JWT](https://tools.ietf.org/html/rfc7519#page-26) might be the easiest to implement. It would also need to fulfill the [8. Implementation Requirements](https://tools.ietf.org/html/rfc7519#page-16) in regards to supporting the minimum required algorithms.

**Comment by geggleto** [comment]
@moderndeveloperllc Yep the string you send back is definitely not a JWT. I see your argument :)

I was using it to replace PHP sessions entirely.

**Comment by moderndeveloperllc** [comment]
@geggleto I'm looking to do that too. A few things to think about. With TLS (HTTPS), headers are already encrypted, so you don't need to worry about a MitM attack on the token any more than the normal "HTTPS is buggy" kind of attacks. In my opinion, JWTs main advantage over just providing a UUID is the ability to pass the client info they can easily use (API commands they are authorized for, etc) in a way that is still safe from modification (the signature). Encrypting makes an extra, expensive step for no net gain in security. Good luck and have fun!

**Comment by geggleto** [comment]
@moderndeveloperllc Yeah this goes so far to make the JWT completely hidden from the client.

**Comment by lcobucci** [comment]
Thanks for that discussion guys!

I definitely want to support encrypted and nested JWT's on v4 and on that release the lib will be really redesigned so my effort now is 100% on planning how things will work together (when the paid work allows me HAHAHA).

Would be very nice to have your help on that, I'll be opening some issues on next weeks to discuss some decisions that I made in the past and I'm not so happy 😄

**Comment by geggleto** [comment]
@lcobucci I'll be watching for them.
