### ISSUE TITLE
Can I get data from encoded token string with secret key like other jwt implement?

### ISSUE THREAD

**Issue by nicozhang** [lcobucci/jwt#91]
I am trying to use jwt in PHP,but they are all hard to use.Your implemtent seems much easier.I have used python jwt, it is very easy to use and I can get data with secret key.But I can not find the method in your implment.Did I miss something import?Wish for your help?

**Comment by lcobucci** [comment]
@nicozhang what you mean with "get data with secret key"? Give us some more information so we can help you 😉

**Comment by nicozhang** [comment]
The code below from psecio/jwt:
<?php

require_once 'vendor/autoload.php';

$key = 'example_key';
$encryptKey = 'my-encryption-key';

$header = new \Psecio\Jwt\Header($key);
$jwt = new \Psecio\Jwt\Jwt($header);

$jwt
    ->issuer('http://example.org')
    ->audience('http://example.com')
    ->issuedAt(1356999524)
    ->notBefore(1357000000)
    ->expireTime(time()+3600)
    ->jwtId('id123456')
    ->type('https://example.com/register');

$result = $jwt->encrypt('AES-256-CBC', '1234567812345678', $encryptKey);

echo 'ENCRYPTED: '.var_export($result, true)."\n";
echo "DECRYPTED: ".var_export($jwt->decrypt($result, 'AES-256-CBC', '1234567812345678', $encryptKey), true)."\n";
?>
the header and other data are encrypted with an encryptKey, it also can decrypt with the key. Your implement can do this ?

**Comment by lcobucci** [comment]
We don't have nested and encrypted tokens implemented yet 😞, but it's planned for next major release.

**Comment by nicozhang** [comment]
Awesome,may I be the member of your team? I also can  add other  features to your repo.Your implement is much more grace than others.

**Comment by lcobucci** [comment]
Contributors are usually invited based on their contributions to the project, but you don't need to be a contributor to collaborate you can just fork the repo and send PRs with improvements 😄 

Will close this as `invalid`.
