### ISSUE TITLE
How to set the correct time zone？

### ISSUE THREAD

**Issue by 490626721** [lcobucci/jwt#940]
I use the following code in the project

// Issuing tokens
`        $now = new DateTimeImmutable("now", new DateTimeZone('Asia/Shanghai'));
        //  halt($now);
        // Correct return
        //  ----------------
        // ^ DateTimeImmutable @1665589267 {#85 ▼
        //  date: 2022-10-12 23:41:07.281117 Asia/Shanghai (+08:00)
        //}
        $key = InMemory::base64Encoded(
            'hiG8DlOKvtih6AxlZn5XKImZ06yu8I3mkOzaJrEuW8yAv8Jnkw330uMt8AEqQ5LB'
        );

        $token = (new JwtFacade(null))->issue(
            new Sha256(),
            $key,
            static fn (
                \Lcobucci\JWT\Builder $builder,
                DateTimeImmutable     $issuedAt
            ): Builder => $builder
                ->issuedBy('https://github.com')
                ->issuedAt($now)
                ->canOnlyBeUsedAfter($now)
                ->expiresAt($now->modify('+1 hour'))
                ->withClaim('userid', "userid859325")
                ->withClaim('role', "admin")
        );

        return $token->toString();`

//  token
`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NjU1ODk0MjAsIm5iZiI6MTY2NTU4OTQyMCwiZXhwIjoxNjY1NTkzMDIwLCJpc3MiOiJodHRwczovL2dpdGh1Yi5jb20iLCJ1c2VyaWQiOiJ1c2VyaWQ4NTkzMjUiLCJyb2xlIjoiYWRtaW4ifQ.VukeVhMiGLvEhbcBJB7_UYSYYT0ju2ZgWCYvUPlcRlY`

// Parsing tokens
`$now = new DateTimeImmutable("now", new DateTimeZone('Asia/Shanghai'));
        $clock = new FrozenClock($now);
        $key = InMemory::base64Encoded(
            'hiG8DlOKvtih6AxlZn5XKImZ06yu8I3mkOzaJrEuW8yAv8Jnkw330uMt8AEqQ5LB'
        );

        $token = (new JwtFacade(null, $clock))->parse(
            "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NjU1ODk0MjAsIm5iZiI6MTY2NTU4OTQyMCwiZXhwIjoxNjY1NTkzMDIwLCJpc3MiOiJodHRwczovL2dpdGh1Yi5jb20iLCJ1c2VyaWQiOiJ1c2VyaWQ4NTkzMjUiLCJyb2xlIjoiYWRtaW4ifQ.VukeVhMiGLvEhbcBJB7_UYSYYT0ju2ZgWCYvUPlcRlY",
            new Constraint\SignedWith(new Sha256(), $key),
            new Constraint\StrictValidAt($clock)
        );
        echo json_encode($token->claims()->all());`

// Parsing tokens result
`{"iat":{"date":"2022-10-12 15:43:40.000000","timezone_type":1,"timezone":"+00:00"},"nbf":{"date":"2022-10-12 15:43:40.000000","timezone_type":1,"timezone":"+00:00"},"exp":{"date":"2022-10-12 16:43:40.000000","timezone_type":1,"timezone":"+00:00"},"iss":"https:\/\/github.com","userid":"userid859325","role":"admin"}`

All the dates in the resolved token are not in the set time zone
What should I do if I want to parse the token with the correct time zone?

**Comment by Ocramius** [comment]
@490626721 what was your resolution here?
