### ISSUE TITLE
How to get Refresh token?

### ISSUE THREAD

**Issue by KyoungKyuPark** [lcobucci/jwt#97]
thanks to you, I made access token. 
When the "access token" is invalid, I want to get "new access token" through Refresh token.
Do u have a solution about this?

thank you in advance.

**Comment by lcobucci** [comment]
@KyoungKyuPark sorry about the delay...

Well, refresh tokens are totally out of scope of the JWT RFC... I mean we have a self-contained token that you can also use to create your authentication/authorization mechanism, but the RFC don't define how you could/should do it.

To answer your question, you could just follow what others are doing (OAuth2 implementations for instance) or create your own mechanism.

If you decided to create your own, you should question yourself about:

1. How will you bind the access token to the refresh token?
1. How will you ensure that, once refreshed, the access token cannot be used?
1. Will you need to set an expiration time for your refresh token?
1. Will you allow your refresh token to be used before the expiration of your access token?

That's it, happy coding 😉

**Comment by lcobucci** [comment]
Will close this as 'invalid' because is not related to the goals of this lib.
