### ISSUE TITLE
Class "Lcobucci\JWT\JwtFacade" not found

### ISSUE THREAD

**Issue by RosaLeaveMeAlone** [lcobucci/jwt#975]
I'm new at this library, and I'm having an error with the [quickstart](https://lcobucci-jwt.readthedocs.io/en/4.2.x/quick-start/), the example code gives me an error: **Class "Lcobucci\JWT\JwtFacade" not found**, this is my code:

```
<?php

namespace App\Http\Services;

use DateTimeImmutable;
use Lcobucci\JWT\Builder;
use Lcobucci\JWT\JwtFacade;
use Lcobucci\JWT\Signer\Hmac\Sha256;
use Lcobucci\JWT\Signer\Key\InMemory;

class JWTService
{
    public static function test()
    {
        $key = InMemory::base64Encoded(
            'hiG8DlOKvtih6AxlZn5XKImZ06yu8I3mkOzaJrEuW8yAv8Jnkw330uMt8AEqQ5LB'
        );

        $token = (new JwtFacade())->issue(
            new Sha256(),
            $key,
            static fn (
                Builder $builder,
                DateTimeImmutable $issuedAt
            ): Builder => $builder
                ->issuedBy('https://api.my-awesome-app.io')
                ->permittedFor('https://client-app.io')
                ->expiresAt($issuedAt->modify('+10 minutes'))
        );
        return $token->toString();
    }
}
```

What can I do to solve this?

**Comment by Ocramius** [comment]
Are you on the right major version of this library? Check your `composer.lock`

**Comment by RosaLeaveMeAlone** [comment]
> 
Thank you for your response, this is in my **composer.lock** file:
```
            "name": "lcobucci/jwt",
            "version": "4.0.4",
```

And this is in my **composer.json** file:
```
"lcobucci/jwt": "^4.0"
```

**Comment by RosaLeaveMeAlone** [comment]
> > 
> 
> Thank you for your response, this is in my **composer.lock** file:
> 
> ```
>             "name": "lcobucci/jwt",
>             "version": "4.0.4",
> ```
> 
> And this is in my **composer.json** file:
> 
> ```
> "lcobucci/jwt": "^4.0"
> ```

Ok, I solve my problem by adding this to my php.ini file:
`extension=php_sodium.dll`

And then run `composer update`

Thanks to @Ocramius to answer my issue.
