### ISSUE TITLE
Lcobucci\JWT\Signer\InvalidKeyProvided: Key provided is shorter than 256 bits, only 120 bits provided......

### ISSUE THREAD

**Issue by andyzu** [lcobucci/jwt#980]
"lcobucci/jwt": "^4.1"
When I call $token = JwtAuth::createToken($data['mobile']); , an error is reported.
I need help, thanks!

Lcobucci\JWT\Signer\InvalidKeyProvided: Key provided is shorter than 256 bits, only 120 bits provided in file /var/www/zhianbao/vendor/lcobucci/jwt/src/Signer/InvalidKeyProvided.php on line 39

**Comment by SvenRtbg** [comment]
The error message says it all: Your signing key is too short. Make it longer, and it will work. JWT standard requires 256 bits of key length for your signature method.

**Comment by aeadedoyin** [comment]
For anyone that stumbles here.
If you are using Laravel [Tymon JWT-Auth](https://github.com/tymondesigns/jwt-auth). This will generate a key that fits the new requirement:
`php artisan jwt:secret`

**Comment by lcobucci** [comment]
> For anyone that stumbles here. This will generate key that feats the new requirement
> `php artisan jwt:secret`

This is only valid for projects using Laravel.

**Comment by aeadedoyin** [comment]
@lcobucci Thanks, that's very true. I have edited it.
