### ISSUE TITLE
Phpstan static analyze failed on incorrect @param annotation

### ISSUE THREAD

**Issue by anikeevda** [lcobucci/jwt#982]
Hello!

Many methods in lib contains **@param** annotation with content **non-empty-string** which is incorrect because this annotation should contain only PHP primitive or object type.

From **InMemory** class
```php
    /** @param non-empty-string $contents */
    public static function plainText(string $contents, string $passphrase = ''): self
    {
        return new self($contents, $passphrase);
    }
```

 Phpstan static analyze is throwing error at such constructions
`
Parameter #1 $contents of static method Lcobucci\JWT\Signer\Key\InMemory::plainText() expects non-empty-string, string given.
`

**Comment by Ocramius** [comment]
PHPStan understands `non-empty-string` just fine: https://phpstan.org/r/6f4b1a68-ac03-4162-b094-49c94ab278ab

 > `Parameter #1 $contents of static method Lcobucci\JWT\Signer\Key\InMemory::plainText() expects non-empty-string, string given.`

This means that you haven't verified if the input string is empty, before passing it to `InMemory::plainText()` :) 

EDIT: something like this works, for example

```php
if ($input === '') {
    throw new \InvalidArgumentException('Provided key is empty');
}

return InMemory::plainText($input);
```
