### ISSUE TITLE
It was not possible to parse your key, reason: error:1E08010C:DECODER routines::unsupported

### ISSUE THREAD

**Issue by juanmanko** [lcobucci/jwt#983]
Hi,everybody,
can someone help me with this error? please?
`
<?php

namespace Common\Helpers;
use App\Models\User;
use Lcobucci\JWT\Builder;
use Lcobucci\JWT\Parser;
use Lcobucci\JWT\Signer\Key;
use Lcobucci\JWT\Signer\Rsa\Sha256;
use Config;
use Ramsey\Uuid\Uuid; 

class Jwt{
    /**
     * Retorna el token basado en la llave publica y privada
     * @param User $usuario
     * @return string
     */
    public static function crearToken($usuario){
        
        $token = Uuid::uuid1();

        $signer = new Sha256(); 
        $privateKey = new Key('file:/'. Config::get('jwt.keys.private'),Config::get('jwt.keys.passphrase'));
        
        $token = (new Builder())
            
            ->issuedBy(env('JWT_ISSUER_URL')) // Configures the issuer (iss claim)
            ->permittedFor(env('JWT_AUDIENCE_URL'))
            ->identifiedBy('3a12aa4f1g2', true) // Configures the id (jti claim), replicating as a header item
            ->issuedAt(time()) // Configures the time that the token was issue (iat claim)
            ->canOnlyBeUsedAfter(time()) // Configures the time that the token can be used (nbf claim)
            ->expiresAt(time() + Config::get('jwt.ttl')) // Configures the expiration time of the token (nbf claim)
            ->withClaim('data',$usuario)   //->getJWTCustomClaims()
            ->getToken($signer,  $privateKey);
        return $token->__toString();
    }
`

**Comment by Ocramius** [comment]
See https://github.com/openssl/openssl/issues/17378#issuecomment-1003353845 perhaps?

**Comment by juanmanko** [comment]
Thank you for helping

I'm going to check
