### ISSUE TITLE
Deprecated empty key

### ISSUE THREAD

**Issue by ol1s** [lcobucci/jwt#989]
Whilst I understand the motivation behind deprecating `InMemory::empty()` it is still a bit of a shame.

For instance, what if we only use the library for verification and not signing. Do we now have to create an arbitrary key that is not used to sign anything?

**Comment by Ocramius** [comment]
Yep 👍

**Comment by lcobucci** [comment]
@ol1s if you're only using the library for verification, you don't need to create a "dummy object" (aka empty key object) for signing (check https://lcobucci-jwt.readthedocs.io/en/stable/validating-tokens/ and https://lcobucci-jwt.readthedocs.io/en/stable/quick-start/#parsing-tokens).
